### ISSUE TITLE
Humidity profile user question 2:  Variability of vertically resolved Tropospheric Humidity

### ISSUE THREAD

**Issue by gmandorl** [bopen/c3s-eqc-toolbox-template#101]
### Notebook description

Hi Mattia,

This notebook answers the user question n 2 of the dataset "Tropospheric humidity profiles averaged monthly and zonally from 2006 to present derived from satellite observations".

The user question is:
"What is the inter-annual variability of the vertically resolved Tropospheric Humidity?"

The method is:
"Plotting the time-series (x-axis) vs latitude (y-axis) of Tropospheric Humidity at several pressure levels : anomaly with respect to climatology"

Could you give me some feedback?

Thank you very much

### Notebook link or upload

[Humidity_Profile_User_question_2.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/12606301/Humidity_Profile_User_question_2.zip)

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Hi @gmandorl,

Sorry about the delay, I was attending the General Assembly in Brno.

The notebook is already in good shape. I've created a template for your use case.
I only made minor changes mainly to make it easier for us to maintain the template (e.g., infer all attrs from metadata, use the same structure of the other notebooks, ...). This is just a template, so it should be easy for you to make changes and tune the plot.

Here is the template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/tropospheric_humidity_variability.ipynb
Here is the notebook executed: https://gist.github.com/malmans2/1297db26de72a21368a5b063c73fbfd9

Please test the notebook on the VM and let me know if everything is OK.

**Comment by gmandorl** [comment]
Hi @malmans2,

Thank you for the help.
I modified the notebook according to your example and I checked that it worked on the VM. I am attaching the new notebook.

[Humidity_Profile_User_question_2.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/12648166/Humidity_Profile_User_question_2.zip)

If it is ok for you, I would like to proceed with the publication of the finalized notebook, but I do not understand what I should do. Should I open a new issue?

In addition, I would like to report a few small technical issues of the dataset that I found while answering the user question. Is it possible? How can I do it?

**Comment by malmans2** [comment]
Hi @gmandorl,

In this repository we only provide technical support to the evaluators. With technical support, I mean anything that has to do with the VM or the python code used to analyse the data. The goal of this repository is to help you out developing the notebooks, and make sure the code is optimised. This is why we only upload templates here, where templates are minimal notebooks with no text nor figures.

Looks like the template we made for your use case is working OK and you've been able to develop your full notebook starting from it, so I suggest we close this issue if that's OK with you.

> If it is ok for you, I would like to proceed with the publication of the finalized notebook, but I do not understand what I should do. Should I open a new issue?

The notebook looks in good shape to me. You need to coordinate with Chunxue to start the review process of the finalizsed notebook (i.e., the notebook that includes figures and comments).

> In addition, I would like to report a few small technical issues of the dataset that I found while answering the user question. Is it possible? How can I do it?

What do you mean with technical issues? If you mean issues that you need to report to the data-provider, you need to coordinate with Chunxue.

**Comment by gmandorl** [comment]
Hi @malmans2,

I understand, thank you very much for your support.
I agree on closing this issue.
