### ISSUE TITLE
Maps of UTH - Can I improve the speed?

### ISSUE THREAD

**Issue by gmandorl** [bopen/c3s-eqc-toolbox-template#104]
### Notebook description

Hi,

I am producing maps of mean and standard deviation of the upper tropospheric humidity.
The code works. However, it is slow and the kernel dies often while executing, therefore it is hard to obtain the plots.

Is there a way I can improve the speed?
Are there other suggestions for this notebook?

### Notebook link or upload

[UTH_maps_1.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/12713922/UTH_maps_1.zip)

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Hi @gmandorl,

The processing step takes some time, but plotting is quite fast.
This is why we cache both the row data and the processed data.

I've revised your notebook:

- Here is the template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/upper_tropospheric_humidity_variability.ipynb
- Here is the notebook executed: https://gist.github.com/malmans2/ed58af86d858505985b75c5f25b94e0e

In only cached `"mhs_on_noaa_18"` so far. Could you please check on the VM that the template works OK and the results are correct?

If everything looks good, let me know which sensors you need to analyse, and I will run the scripts to populate the cache.
Please also double check that `time_dict` is correct.

**Comment by gmandorl** [comment]
Hi @malmans2,


Thank you very much for the help!

The template works well. The dictionary "time_dict" is correct, and the results are correct.


I can submit the notebook using "mhs_on_noaa_18" only, however, I would like to verify that also all the other sensors look ok.
I can populate the cache by running the notebook, however, could you (or the main user) agree to the required terms and conditions of all the sensors?

The link should be this one:
https://cds.climate.copernicus.eu/cdsapp/#!/terms/eumetsat-cm-saf-uth

**Comment by malmans2** [comment]
I don't know who's the main user, but you should use your own credentials as discussed here: https://github.com/bopen/c3s-eqc-toolbox-template/issues/94

Let me populate the cache. I usually run scripts overnight and/or over the weekend that use concurrent requests and multiprocessing. It's faster, but most importantly we don't stress the VM too much during the day when there are several users connected.

I will let you know when everything is cached.

**Comment by malmans2** [comment]
BTW, a detail I forgot to mention. In you original notebook you were computing time weighted mean/std (it's computationally more expensive than unweighted diagnostics).

But I believe you don't need it as you are dealing with daily data. So I switched it off with the argument `weights=False`.

**Comment by malmans2** [comment]
Hi @gmandorl,

Everything is cached. Note that I had to slightly change the template because `mhs_on_metop_a` is missing 1 month.
Please use the latest template from now on.

Same urls:

- Here is the template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/upper_tropospheric_humidity_variability.ipynb
- Here is the notebook executed: https://gist.github.com/malmans2/ed58af86d858505985b75c5f25b94e0e

**Comment by gmandorl** [comment]
Hi @malmans2 ,

Thank you very much.
I did not know that the weighted mean/std was computationally much more expensive. Thank you for pointing it out.

Thank you very much for the new notebook.
I was trying to solve the problem by using "chunks": {"year": 1}, but I will use your example now.
