### ISSUE TITLE
Merging of data from various versions of the "satellite-aerosol-properties" catalog

### ISSUE THREAD

**Issue by FaezehKarimian** [bopen/c3s-eqc-toolbox-template#106]
### Notebook description

This notebook's main objective is to demonstrate how the SLSTR dataset across southern Italy for the years 2017 to 2022 may be used to capture the seasonal trends of AOD and fAOD. 

### Notebook link or upload

[South ItalyAOD.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/12816797/South.ItalyAOD.zip)

### Anything else we need to know?

There are several versions can be used for slstr sensor . For the data generated from one version, I was able to generate NBs. I now need to merge or combine two datasets coming from separate versions in order to cover a longer time period as v2.1 covers data for the years (2017-06 to 2020-06) and v2.2 for (2020-06 to 2022-12). I'd like to know if you recommend merging the two datasets after downloading them or defining both datasets of various versions at the beginning of the code in the request part. As you can see in the shared file I tried the first approach several times without success. I appreciate your help in advance.

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Hi, I think you should download them separately.

You could concatenate them in a single xarray Dataset with additional dimension "version", but because they cover different time periods that's not ideal (it would add NaN values in missing time stamps).

**Comment by FaezehKarimian** [comment]
Exactly as it happened, the results are also available in the zip file. By adding the "version" dimension, "nan" values appeared. Please let me know your suggestions.

**Comment by malmans2** [comment]
Hi, sorry about the confusion. This is what I was suggesting:
```python
from c3s_eqc_automatic_quality_control import download

collection_id = "satellite-aerosol-properties"
request = {
    "format": "zip",
    "time_aggregation": "monthly_average",
    "variable": "aerosol_optical_depth",
    "sensor_on_satellite": "slstr_on_sentinel_3a",
    "algorithm": "ens",
}

time_dict = {
    "v2.1": {"start": "2018-01", "stop": "2020-06"},
    "v2.2": {"start": "2020-07", "stop": "2022-12"},
}

ds_dict = {}
for version, kwargs in time_dict.items():
    requests = download.update_request_date(
        request | {"version": version}, **kwargs, stringify_dates=True
    )
    ds_dict[version] = download.download_and_transform(
        collection_id, requests, chunks={"year": 1, "month": 1}
    )

print(ds_dict)
```

**Comment by FaezehKarimian** [comment]
Hi, Mattia, I appreciate your help. I was able to get the merged data.

**Comment by malmans2** [comment]
Awesome!
