### ISSUE TITLE
Problem with Jupyter server

### ISSUE THREAD

**Issue by Cri-dei** [bopen/c3s-eqc-toolbox-template#109]
### What happened?

Hi,

I have problem to not connect to the jupyter notebook in my folder.

![thumbnail_image](https://github.com/bopen/c3s-eqc-toolbox-template/assets/56677048/9bcb8c94-2907-447a-8a01-47e8968c874a)
![thumbnail_image-1](https://github.com/bopen/c3s-eqc-toolbox-template/assets/56677048/696221ee-7219-4265-b602-09d3db434444)

Copying the link in the browser it tell me: unable to connect.
Am I doing something wrong or it is changed something?

Thanks!

### Environment

<details>

</details>

**Comment by malmans2** [comment]
It might be that your session is old and/or broken. Try this:
From the VM:
```
jupyter lab stop 8846
```
From your local machine, kill all ssh tunnels:
```
pkill ssh
```

Now re-connect to the VM, and re-do everything from scratch (`jupyter_server` then follow the instructions).
Note that very likely the port assigned to you will change, so make sure you copy/paste the new commands printed on terminal.

Let me know if that works.

**Comment by malmans2** [comment]
@Cri-dei Did it work?

**Comment by malmans2** [comment]
You need to stop your own server.
In the screenshot you attached, the terminal says: `jupyter lab stop 8894` while you attempted to kill 8846.

Make sure you follow the command printed on terminal, otherwise you are going to kill the server of other users. In this case, you tried to kill the former server of Cristina. Luckily, it looks like right now that port is not assigned to anyone.

**Comment by malmans2** [comment]
If you don't care about any ssh, you can just run `pskill ssh` to kill all of them.
Otherwise, you can determine which one too kill using this command:
```
ps aux | grep ssh
```

**Comment by FaezehKarimian** [comment]
<img width="636" alt="Screenshot 2023-10-30 120416" src="https://github.com/bopen/c3s-eqc-toolbox-template/assets/139398543/4b6ff284-b4c3-4fac-b06e-a09ddc55d94f">
Here is the result.

**Comment by malmans2** [comment]
`pkill`, I had a typo in my previous comment.
(Also, that was explained in my previous comment to Cristina: https://github.com/bopen/c3s-eqc-toolbox-template/issues/109#issuecomment-1782625656)

I do not know Windows, so I don't know.

**Comment by FaezehKarimian** [comment]
Thank you so much Mattia. I appreciate your time and support. I could connect the VM.

**Comment by Cri-dei** [comment]
> @Cri-dei Did it work?

Sorry I read very late and I saw it was already solved the comment! It worked and I am able to enter to the jupyter again! Thank you so much!!
