### ISSUE TITLE
Notebook with Use Case 2 for Land Cover Dataset

### ISSUE THREAD

**Issue by inesgirao** [bopen/c3s-eqc-toolbox-template#111]
### Notebook description

Trends and Variability: urbanization trends 

Use Case: Assessment of urbanization trends.

User Question: Can we measure urbanization trends in the Iberian Peninsula? Are we able to disclose significant regional contrasts?

Method: Time series plots of urban area trends, based on pixel-wise Mann-Kendall and Theil-Sen estimations, shall be produced for specific AoI. Maps of Total Urban Area per year, Urban Area change per year, Total Variation in Urban Area between 1992 and 2020, and the Percentage difference of Urban Area between 1992 and 2020 were also performed.

### Notebook link or upload

[C3S2_D520.5.3.14b_Quality_Assessment_User_Questions_LULC_UQ2_v1.3.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/13307611/C3S2_D520.5.3.14b_Quality_Assessment_User_Questions_LULC_UQ2_v1.3.zip)

### Anything else we need to know?

1. please note that this new jupyter notebook for Use case 2 version uses the NUTs2021 (20m resolution) shapefile to aggregate statistics - we re-use B-OPEN function to do that step.
 
2. Regarding the Land Cover dataset download, we also used the same done by B-OPEN.
 
3. In this notebook, we show the temporal trends for all regions and then we give a zoom-in for the hotspot regions, i.e., which presents the higher trends. 

4. We have in common with Fire the same approach regarding the calculation of the trend - we use the methodology of Mann-Kendall Test and Theil-Sen Estimation.

### Environment

<details>
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
accessible-pygments       0.0.4              pyhd8ed1ab_0    conda-forge
affine                    2.4.0              pyhd8ed1ab_0    conda-forge
aiohttp                   3.8.5           py310h2372a71_0    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
alabaster                 0.7.13             pyhd8ed1ab_0    conda-forge
alsa-lib                  1.2.8                h166bdaf_0    conda-forge
ansiwrap                  0.8.4                      py_0    conda-forge
antlr-python-runtime      4.7.2           py310hff52083_1003    conda-forge
anyio                     3.7.1              pyhd8ed1ab_0    conda-forge
argon2-cffi               23.1.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0          py310h5764c6d_3    conda-forge
arrow                     1.2.3                    pypi_0    pypi
arrow-cpp                 10.0.1          ha770c72_22_cpu    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
astroid                   2.15.6          py310hff52083_0    conda-forge
asttokens                 2.0.5              pyhd3eb1b0_0  
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.3              pyhd8ed1ab_0    conda-forge
attr                      2.5.1                h166bdaf_1    conda-forge
attrs                     23.1.0                   pypi_0    pypi
aws-c-auth                0.6.26               h2c7c9e7_6    conda-forge
aws-c-cal                 0.5.26               h71eb795_0    conda-forge
aws-c-common              0.8.17               hd590300_0    conda-forge
aws-c-compression         0.2.16               h4f47f36_6    conda-forge
aws-c-event-stream        0.2.20               h69ce273_6    conda-forge
aws-c-http                0.7.7                h7b8353a_3    conda-forge
aws-c-io                  0.13.21              hcccde9c_3    conda-forge
aws-c-mqtt                0.8.6               h3a1964a_15    conda-forge
aws-c-s3                  0.2.8                h0933b68_4    conda-forge
aws-c-sdkutils            0.1.9                h4f47f36_1    conda-forge
aws-checksums             0.1.14               h4f47f36_6    conda-forge
aws-crt-cpp               0.19.9               h85076f6_5    conda-forge
aws-sdk-cpp               1.10.57             hf40e4db_10    conda-forge
babel                     2.12.1             pyhd8ed1ab_1    conda-forge
backcall                  0.2.0              pyhd3eb1b0_0  
backports                 1.1                pyhd3eb1b0_0  
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0  
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
black                     23.7.0          py310hff52083_1    conda-forge
blas                      1.0                    openblas  
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
blosc                     1.21.3               h6a678d5_0  
bokeh                     3.2.2              pyhd8ed1ab_0    conda-forge
boost-cpp                 1.78.0               h6582d0a_3    conda-forge
bottleneck                1.3.5           py310ha9d4c09_0  
brotli                    1.0.9                h5eee18b_7  
brotli-bin                1.0.9                h5eee18b_7  
brotlipy                  0.7.0           py310h7f8727e_1002  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.19.0               h5eee18b_0  
c3s-eqc-automatic-quality-control 0.1.2.dev84+ga57fc76          pypi_0    pypi
c3s-eqc-toolbox-template  0.2.2.dev320+g3e5c724          pypi_0    pypi
ca-certificates           2023.7.22            hbcca054_0    conda-forge
cacholote                 0.4.1                    pypi_0    pypi
cads-toolbox              0.0.2b0                  pypi_0    pypi
cairo                     1.16.0            h35add3b_1015    conda-forge
cartopy                   0.22.0          py310h7cbd5c2_0    conda-forge
cdsapi                    0.6.1              pyhd8ed1ab_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cf-units                  3.2.0           py310h278f3c1_0    conda-forge
cf_xarray                 0.8.4              pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h5eee18b_3  
cfgrib                    0.9.10.4           pyhd8ed1ab_0    conda-forge
cfgv                      3.3.1              pyhd8ed1ab_0    conda-forge
cfitsio                   4.2.0                hd9d235c_0    conda-forge
cftime                    1.6.2           py310ha9d4c09_0  
cgul                      0.0.4                    pypi_0    pypi
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4           py310h06a4308_0  
click-plugins             1.1.1              pyhd3eb1b0_0  
cligj                     0.7.2              pyhd3eb1b0_0  
cloudpickle               2.2.1           py310h06a4308_0  
colorama                  0.4.6           py310h06a4308_0  
comm                      0.1.4                    pypi_0    pypi
conda-merge               0.2.0              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.5           py310hdb19cb5_0  
coucal                    0.0.1b3                  pypi_0    pypi
coverage                  7.3.0           py310h2372a71_0    conda-forge
cryptography              41.0.2          py310h22a60cf_0  
curl                      8.1.1                hdbd6064_2  
cycler                    0.11.0             pyhd3eb1b0_0  
cytoolz                   0.12.0          py310h5eee18b_0  
dask                      2023.6.0           pyhd8ed1ab_0    conda-forge
dask-core                 2023.6.0        py310h06a4308_0  
dbus                      1.13.18              hb2f20db_0  
debugpy                   1.6.7           py310h6a678d5_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
descartes                 1.1.0                    pypi_0    pypi
distlib                   0.3.7              pyhd8ed1ab_0    conda-forge
distributed               2023.6.0        py310h06a4308_0  
docutils                  0.19            py310hff52083_1    conda-forge
eccodes                   2.30.0               h95353b9_0    conda-forge
emohawk                   0.0.4b0                  pypi_0    pypi
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
esmf                      8.4.2           nompi_h20110ff_0    conda-forge
esmpy                     8.4.2              pyhc1e730c_0    conda-forge
exceptiongroup            1.1.3              pyhd8ed1ab_0    conda-forge
executing                 0.8.3              pyhd3eb1b0_0  
expat                     2.5.0                hcb278e6_1    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
filelock                  3.12.2             pyhd8ed1ab_0    conda-forge
findlibs                  0.0.5              pyhd8ed1ab_0    conda-forge
fiona                     1.9.1           py310h1128e8f_0  
flit-core                 3.9.0              pyhd8ed1ab_0    conda-forge
flox                      0.7.2              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hd3eb1b0_0  
font-ttf-inconsolata      2.001                hcb22688_0  
font-ttf-source-code-pro  2.030                hd3eb1b0_0  
font-ttf-ubuntu           0.83                 h8b1ccd4_0  
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-anaconda            1                    h8fa9717_0  
fonts-conda-ecosystem     1                    hd3eb1b0_0  
fonttools                 4.25.0             pyhd3eb1b0_0  
fqdn                      1.5.1                    pypi_0    pypi
freeglut                  3.2.2                h9c3ff4c_1    conda-forge
freetype                  2.12.1               h4a9f257_0  
freexl                    1.0.6                h27cfd23_0  
frozenlist                1.4.0           py310h2372a71_0    conda-forge
fsspec                    2023.6.0           pyh1a96a4e_0    conda-forge
gdal                      3.6.4           py310hf0ca374_0    conda-forge
geopandas                 0.14.0                   pypi_0    pypi
geopandas-base            0.9.0                      py_1  
geos                      3.11.2               hcb278e6_0    conda-forge
geotiff                   1.7.1                h480ec47_8    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gflags                    2.2.2                he6710b0_0  
giflib                    5.2.1                h5eee18b_3  
glib                      2.76.2               hfc55251_0    conda-forge
glib-tools                2.76.2               hfc55251_0    conda-forge
glog                      0.6.0                h6f12383_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
graphite2                 1.3.14               h295c915_1  
greenlet                  2.0.1           py310h6a678d5_0  
gst-plugins-base          1.22.0               h4243ec0_2    conda-forge
gstreamer                 1.22.0               h25f0c4b_2    conda-forge
harfbuzz                  6.0.0                h3ff4399_1    conda-forge
hdf4                      4.2.15               h501b40f_6    conda-forge
hdf5                      1.14.0          nompi_hb72d44e_103    conda-forge
heapdict                  1.0.1              pyhd3eb1b0_0  
icu                       72.1                 hcb278e6_0    conda-forge
identify                  2.5.26             pyhd8ed1ab_0    conda-forge
idna                      3.4             py310h06a4308_0  
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        6.0.0           py310h06a4308_0  
importlib_metadata        6.0.0                hd3eb1b0_0  
importlib_resources       6.0.1              pyhd8ed1ab_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.25.0          py310h2f386ee_0  
ipython                   8.12.2          py310h06a4308_0  
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.1.0                    pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
jasper                    4.0.0                h32699f2_1    conda-forge
jedi                      0.18.1          py310h06a4308_1  
jinja2                    3.1.2           py310h06a4308_0  
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
json-c                    0.16                 h5eee18b_0  
json5                     0.9.14             pyhd8ed1ab_0    conda-forge
jsonpointer               2.4                      pypi_0    pypi
jsonschema                4.18.6                   pypi_0    pypi
jsonschema-specifications 2023.7.1                 pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-console           6.6.3                    pypi_0    pypi
jupyter-events            0.7.0                    pypi_0    pypi
jupyter-lsp               2.2.0              pyhd8ed1ab_0    conda-forge
jupyter-server            2.7.2                    pypi_0    pypi
jupyter_client            8.1.0           py310h06a4308_0  
jupyter_core              5.3.0           py310h06a4308_0  
jupyter_events            0.6.3              pyhd8ed1ab_0    conda-forge
jupyter_server            2.7.1              pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyterlab                4.0.5              pyhd8ed1ab_0    conda-forge
jupyterlab-widgets        3.0.8                    pypi_0    pypi
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.24.0             pyhd8ed1ab_0    conda-forge
kaleido                   0.2.1                    pypi_0    pypi
kealib                    1.5.0                he7a6254_1    conda-forge
kiwisolver                1.4.4           py310h6a678d5_0  
krb5                      1.20.1               h143b758_1  
lame                      3.100                h7b6447c_0  
lazy-object-proxy         1.9.0           py310h1fa729e_0    conda-forge
lcms2                     2.15                 haa2dc70_1    conda-forge
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20230125.0      cxx17_hcb278e6_1    conda-forge
libaec                    1.0.6                hcb278e6_1    conda-forge
libarrow                  10.0.1          h2112b9f_22_cpu    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h5eee18b_7  
libbrotlidec              1.0.9                h5eee18b_7  
libbrotlienc              1.0.9                h5eee18b_7  
libcap                    2.67                 he9d0100_0    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libclang                  16.0.2          default_h83cc7fd_0    conda-forge
libclang13                16.0.2          default_hd781213_0    conda-forge
libcrc32c                 1.1.2                h6a678d5_0  
libcups                   2.3.3                h36d4200_3    conda-forge
libcurl                   8.1.1                h251f7ec_2  
libdeflate                1.18                 h0b41bf4_0    conda-forge
libedit                   3.1.20221030         h5eee18b_0  
libev                     4.33                 h7f8727e_1  
libevent                  2.1.10               h28343ad_4    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.4                h6a678d5_0  
libflac                   1.4.2                h27087fc_0    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgcrypt                 1.10.1               h166bdaf_0    conda-forge
libgdal                   3.6.4                h7239d12_0    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libglib                   2.76.2               hebfc3b9_0    conda-forge
libglu                    9.0.0                hf484d3e_1  
libgomp                   12.2.0              h65d4601_19    conda-forge
libgoogle-cloud           2.9.1                hac9eb74_0    conda-forge
libgpg-error              1.46                 h620e276_0    conda-forge
libgrpc                   1.54.1               hcf146ea_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libjpeg-turbo             2.1.5.1              h0b41bf4_0    conda-forge
libkml                    1.3.0             h37653c0_1015    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libllvm11                 11.1.0               h9e868ea_6  
libllvm16                 16.0.2               hbf9e925_0    conda-forge
libnetcdf                 4.9.2           nompi_hdf9a29f_104    conda-forge
libnghttp2                1.52.0               h2d74bed_1  
libnsl                    2.0.0                h5eee18b_0  
libnuma                   2.0.16               h0b41bf4_1    conda-forge
libogg                    1.3.5                h27cfd23_1  
libopenblas               0.3.21               h043d6bf_0  
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.39               h5eee18b_0  
libpq                     15.2                 hb675445_0    conda-forge
libprotobuf               3.21.12              h3eb15da_0    conda-forge
librttopo                 1.1.0               h0d5128d_13    conda-forge
libsndfile                1.2.0                hb75c966_0    conda-forge
libsodium                 1.0.18               h7b6447c_0  
libspatialindex           1.9.3                h2531618_0  
libspatialite             5.0.1               h7d1ca68_25    conda-forge
libsqlite                 3.40.0               h753d276_1    conda-forge
libssh2                   1.10.0               hdbd6064_2  
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libsystemd0               253                  h8c4010b_1    conda-forge
libthrift                 0.18.1               h5e4af38_0    conda-forge
libtiff                   4.5.0                ha587672_6    conda-forge
libutf8proc               2.8.0                h166bdaf_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libvorbis                 1.3.7                h7b6447c_0  
libwebp-base              1.3.0                h0b41bf4_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              1.5.0                h79f4944_1    conda-forge
libxml2                   2.10.4               hfdac1af_0    conda-forge
libzip                    1.9.2                hc929e4a_1    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
llvmlite                  0.39.1          py310h58363a5_1    conda-forge
locket                    1.0.0           py310h06a4308_0  
lz4                       4.3.2           py310h5eee18b_0  
lz4-c                     1.9.4                h6a678d5_0  
make                      4.3                  hd18ef5c_1    conda-forge
mapclassify               2.5.0           py310h06a4308_0  
markdown-it-py            2.2.0           py310h06a4308_1  
markupsafe                2.1.1           py310h7f8727e_0  
matplotlib                3.7.1           py310hff52083_0    conda-forge
matplotlib-base           3.7.1           py310h1128e8f_1  
matplotlib-inline         0.1.6           py310h06a4308_0  
mdit-py-plugins           0.4.0              pyhd8ed1ab_0    conda-forge
mdurl                     0.1.0           py310h06a4308_0  
mistune                   3.0.1              pyhd8ed1ab_0    conda-forge
mpg123                    1.31.3               hcb278e6_0    conda-forge
msgpack-python            1.0.3           py310hd09550d_0  
multidict                 6.0.4           py310h1fa729e_0    conda-forge
munch                     2.5.0              pyhd3eb1b0_0  
munkres                   1.1.4                      py_0  
mypy                      1.5.1           py310h2372a71_0    conda-forge
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
mysql-common              8.0.32               ha901b37_1    conda-forge
mysql-libs                8.0.32               hd7da12d_1    conda-forge
myst-parser               1.0.0              pyhd8ed1ab_0    conda-forge
nbclient                  0.8.0              pyhd8ed1ab_0    conda-forge
nbconvert                 7.7.3                    pypi_0    pypi
nbconvert-core            7.7.4              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.7.4              pyhd8ed1ab_0    conda-forge
nbformat                  5.9.2              pyhd8ed1ab_0    conda-forge
nco                       1.1.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nest-asyncio              1.5.6           py310h06a4308_0  
netcdf-fortran            4.6.0           nompi_h3142581_105    conda-forge
netcdf4                   1.6.4           nompi_py310hde23a83_100    conda-forge
networkx                  3.1             py310h06a4308_0  
nodeenv                   1.8.0              pyhd8ed1ab_0    conda-forge
notebook                  7.0.2                    pypi_0    pypi
notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
nspr                      4.35                 h6a678d5_0  
nss                       3.89.1               h6a678d5_0  
numba                     0.56.4          py310h0e39c9b_1    conda-forge
numcodecs                 0.11.0          py310heca2aa9_1    conda-forge
numexpr                   2.8.4           py310h757a811_1  
numpy                     1.23.5          py310h53a5b5f_0    conda-forge
numpy_groupies            0.9.22             pyhd8ed1ab_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   3.1.2                hd590300_0    conda-forge
orc                       1.8.3                hfdbbad2_0    conda-forge
overrides                 7.4.0              pyhd8ed1ab_0    conda-forge
packaging                 23.0            py310h06a4308_0  
pandas                    2.0.3           py310h1128e8f_0  
pandoc                    3.1.3                h32600fe_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
papermill                 2.3.4              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd3eb1b0_0  
partd                     1.2.0              pyhd3eb1b0_1  
pathspec                  0.11.2             pyhd8ed1ab_0    conda-forge
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.5.0           py310h065c6d2_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h7f8727e_1  
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              3.10.0          py310h06a4308_0  
plotly                    5.16.1             pyhd8ed1ab_0    conda-forge
pluggy                    1.2.0              pyhd8ed1ab_0    conda-forge
ply                       3.11            py310h06a4308_0  
pooch                     1.7.0              pyha770c72_3    conda-forge
poppler                   23.04.0              hf052cbe_1    conda-forge
poppler-data              0.4.11               h06a4308_1  
postgresql                15.2                 h3248436_0    conda-forge
pre-commit                3.3.3              pyha770c72_0    conda-forge
proj                      9.2.0                h8ffa02c_0    conda-forge
prometheus_client         0.17.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.36          py310h06a4308_0  
prompt_toolkit            3.0.36               hd3eb1b0_0  
properscoring             0.1                        py_0    conda-forge
psutil                    5.9.0           py310h5eee18b_0  
pthread-stubs             0.3                  h0ce48e5_1  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pulseaudio-client         16.1                 h5195f5e_3    conda-forge
pure_eval                 0.2.2              pyhd3eb1b0_0  
pyarrow                   10.0.1          py310h468efa6_0  
pycparser                 2.21               pyhd3eb1b0_0  
pydantic                  1.10.12         py310h2372a71_1    conda-forge
pydata-sphinx-theme       0.13.3             pyhd8ed1ab_0    conda-forge
pygments                  2.15.1          py310h06a4308_1  
pymannkendall             1.4.3                    pypi_0    pypi
pyopenssl                 23.2.0          py310h06a4308_0  
pyparsing                 3.0.9           py310h06a4308_0  
pyproj                    3.6.0           py310ha254fea_0    conda-forge
pyqt                      5.15.7          py310hab646b1_3    conda-forge
pyqt5-sip                 12.11.0         py310heca2aa9_3    conda-forge
pyrsistent                0.19.3          py310h1fa729e_0    conda-forge
pyshp                     2.1.3              pyhd3eb1b0_0  
pysocks                   1.7.1           py310h06a4308_0  
pytest                    7.4.0              pyhd8ed1ab_0    conda-forge
pytest-cov                4.1.0              pyhd8ed1ab_0    conda-forge
python                    3.10.10         he550d4f_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-dotenv             1.0.0              pyhd8ed1ab_0    conda-forge
python-eccodes            1.5.1           py310h0a54255_0    conda-forge
python-fastjsonschema     2.18.0             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-lmdb               1.4.1           py310h6a678d5_0  
python-tzdata             2023.3             pyhd3eb1b0_0  
python_abi                3.10                    3_cp310    conda-forge
pytz                      2022.7          py310h06a4308_0  
pyyaml                    6.0             py310h5764c6d_5    conda-forge
pyzmq                     25.1.0          py310h6a678d5_0  
qt-main                   5.15.8               h5c52f38_9    conda-forge
qtconsole                 5.4.3                    pypi_0    pypi
qtpy                      2.3.1                    pypi_0    pypi
rasterio                  1.3.6                    pypi_0    pypi
re2                       2023.02.02           hcb278e6_0    conda-forge
readline                  8.2                  h5eee18b_0  
referencing               0.30.1                   pypi_0    pypi
regionmask                0.10.0             pyhd8ed1ab_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rich                      13.5.1             pyhd8ed1ab_0    conda-forge
rioxarray                 0.14.1                   pypi_0    pypi
rpds-py                   0.9.2                    pypi_0    pypi
rtree                     1.0.1           py310h06a4308_0  
s2n                       1.3.42               h3358134_0    conda-forge
scikit-learn              1.3.0           py310h1128e8f_0  
scipy                     1.11.1          py310heeff2f4_0  
seaborn                   0.12.2               hd8ed1ab_0    conda-forge
seaborn-base              0.12.2             pyhd8ed1ab_0    conda-forge
send2trash                1.8.2              pyh41d4057_0    conda-forge
setuptools                68.0.0          py310h06a4308_0  
shapely                   2.0.1           py310h056c13c_1    conda-forge
shellingham               1.5.0           py310h06a4308_0  
sip                       6.7.9           py310hc6cd4ac_0    conda-forge
six                       1.16.0             pyhd3eb1b0_1  
snappy                    1.1.10               h9fff704_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.4.0              pyhd3eb1b0_0  
soupsieve                 2.4.1                    pypi_0    pypi
sparse                    0.14.0             pyhd8ed1ab_0    conda-forge
sphinx                    6.2.1              pyhd8ed1ab_0    conda-forge
sphinx-autoapi            2.1.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.7              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     1.0.5              pyhd8ed1ab_0    conda-forge
sphinxcontrib-dotnetdomain 0.4                        py_0    conda-forge
sphinxcontrib-golangdomain 0.2.0.dev0                 py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.4              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-qthelp      1.0.6              pyhd8ed1ab_0    conda-forge
sphinxcontrib-serializinghtml 1.1.9              pyhd8ed1ab_0    conda-forge
sqlalchemy                2.0.20          py310h2372a71_0    conda-forge
sqlite                    3.41.2               h5eee18b_0  
stack_data                0.2.0              pyhd3eb1b0_0  
statsmodels               0.14.0          py310h278f3c1_1    conda-forge
structlog                 23.1.0             pyhd8ed1ab_0    conda-forge
tblib                     1.7.0              pyhd3eb1b0_0  
tenacity                  8.2.2           py310h06a4308_0  
terminado                 0.17.1             pyh41d4057_0    conda-forge
textwrap3                 0.9.2                      py_0    conda-forge
threadpoolctl             2.2.0              pyh0d69192_0  
tiledb                    2.13.2               hd532e3d_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h1ccaba5_0  
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1           py310h06a4308_0  
toolz                     0.12.0          py310h06a4308_0  
tornado                   6.3.2           py310h5eee18b_0  
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.7.1           py310h06a4308_0  
typer                     0.9.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.7.1           py310h06a4308_0  
typing_extensions         4.7.1           py310h06a4308_0  
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzcode                    2023c                h0b41bf4_0    conda-forge
tzdata                    2023c                h04d1e81_0  
ucx                       1.14.0               h3484d09_2    conda-forge
udunits2                  2.2.28               hc3e0081_0    conda-forge
ukkonen                   1.0.1           py310hbf28c38_3    conda-forge
unidecode                 1.3.6              pyhd8ed1ab_0    conda-forge
uri-template              1.3.0                    pypi_0    pypi
urllib3                   1.26.16         py310h06a4308_0  
virtualenv                20.24.3            pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyhd3eb1b0_0  
webcolors                 1.13                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.6.1              pyhd8ed1ab_0    conda-forge
wheel                     0.38.4          py310h06a4308_0  
widgetsnbextension        4.0.8                    pypi_0    pypi
wrapt                     1.15.0          py310h1fa729e_0    conda-forge
xarray                    2023.8.0           pyhd8ed1ab_0    conda-forge
xarraymannkendall         1.4.5              pyhd8ed1ab_0    conda-forge
xcb-util                  0.4.0                h166bdaf_0    conda-forge
xcb-util-image            0.4.0                h166bdaf_0    conda-forge
xcb-util-keysyms          0.4.0                h166bdaf_0    conda-forge
xcb-util-renderutil       0.3.9                h166bdaf_0    conda-forge
xcb-util-wm               0.4.1                h166bdaf_0    conda-forge
xerces-c                  3.2.4                h8d71039_2    conda-forge
xesmf                     0.7.1              pyhd8ed1ab_0    conda-forge
xhistogram                0.3.2              pyhd8ed1ab_0    conda-forge
xkeyboard-config          2.38                 h0b41bf4_0    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.8.4                h0b41bf4_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxi                1.7.10               h7f98852_0    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xf86vidmodeproto     2.3.1             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h27cfd23_1007  
xskillscore               0.0.24             pyhd8ed1ab_0    conda-forge
xyzservices               2022.9.0        py310h06a4308_1  
xz                        5.4.2                h5eee18b_0  
yaml                      0.2.5                h7b6447c_0  
yarl                      1.9.2           py310h2372a71_0    conda-forge
zarr                      2.16.1             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.4                h2531618_0  
zict                      2.2.0           py310h06a4308_0  
zipp                      3.11.0          py310h06a4308_0  
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.5                hc292b87_0
</details>

**Comment by malmans2** [comment]
is this for WP5, correct?

**Comment by inesgirao** [comment]
Yes, in Satellite data - ECV Land_Biosphere

**Comment by malmans2** [comment]
Hi @inesgirao,

You template is ready. I didn't tune much the plots, but you should be able to easily customize it (e.g., change colors, ...).

- Here is the template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/LULC_land_cover_urbanization_trends.ipynb
- Here is the notebook executed: https://gist.github.com/malmans2/d3ebd832f7f00c05628852f56a29e773

Let me know if it works OK.

**Comment by inesgirao** [comment]
Hi @malmans2 

Thank you. I will run it and let you know if it works ok.

**Comment by malmans2** [comment]
Hi @inesgirao,

Could you please let me know whether this notebooks works OK?
Can we close this issue?

**Comment by inesgirao** [comment]
Hey @malmans2,

Yes, everything is working properly.

Thank you
