### ISSUE TITLE
Jupyter notebook for glacier ECVs

### ISSUE THREAD

**Issue by yoniv1** [bopen/c3s-eqc-toolbox-template#112]
### Notebook description

**Notebook 1 (C3S_glaciers_MC_UC1):**

Quality assessment: Glacier mass change gridded data from 1976 to present derived from the Fluctuations of Glaciers Database
Use Case: A study on the global cumulative mass balance of all glaciers and its uncertainty in the dataset.
User Question: How accurate are the glacier mass change products on the CDS when used to derive the global cumulative mass balance of all glaciers in the dataset?

**Notebook 2 (C3S_glaciers_MC_UC2):**

Quality assessment: Glacier mass change gridded data from 1976 to present derived from the Fluctuations of Glaciers Database
Use Case: A study on the annual variability of the glacier mass change product and its trend over time.
User Question: How well is the glacier mass change product on the CDS suited to derive mean values, temporal variability and trends?

**Notebook 3 (C3S_glaciers_RGI_UC1):**

Quality assessment: Glaciers distribution data from the Randolph Glacier Inventory for year 2000
Use Case: Defining how close the glacier characteristics in the dataset are situated near the year 2000 AD.
User Question: How close in time are the different digitized glacier data situated to the year 2000 AD?

### Notebook link or upload

[C3S_glaciers_MC_UC1.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/13319378/C3S_glaciers_MC_UC1.zip)
[C3S_glaciers_MC_UC2.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/13319379/C3S_glaciers_MC_UC2.zip)
[C3S_glaciers_RGI_UC1.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/13319380/C3S_glaciers_RGI_UC1.zip)

### Anything else we need to know?

* Download folder is still listed as my local folder

* There might a problem with the world maps, it shows the following warning:
_/var/folders/1b/ytl_sf9s35q0md30ts7pq53r0000gq/T/ipykernel_61639/567343771.py:22: FutureWarning: The geopandas.dataset module is deprecated and will be removed in GeoPandas 1.0. You can get the original 'naturalearth_lowres' data from https://www.naturalearthdata.com/downloads/110m-cultural-vectors/.
  gpd.datasets.get_path("naturalearth_lowres"));_

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Which WP is this notebook for?

**Comment by malmans2** [comment]
@yoniv1 Looks like the notebooks you shared are corrupted.
After unzipping them, I ged this error when I try to open them:
```
NotJSONError("Notebook does not appear to be JSON: '<!DOCTYPE HTML>\\n<html>\\n\\n<head>\\n ...")
```

**Comment by yoniv1** [comment]
> Which WP is this notebook for?

This is WP5!

**Comment by yoniv1** [comment]
> @yoniv1 Looks like the notebooks you shared are corrupted. After unzipping them, I ged this error when I try to open them:
> 
> ```
> NotJSONError("Notebook does not appear to be JSON: '<!DOCTYPE HTML>\\n<html>\\n\\n<head>\\n ...")
> ```

Can you try with this?
[C3S_glaciers_JN.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/13311096/C3S_glaciers_JN.zip)

**Comment by yoniv1** [comment]
Or if not this:
[C3S_glaciers_JN2.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/13311151/C3S_glaciers_JN2.zip)

**Comment by malmans2** [comment]
Second one works. Could you please edit you very first comment and replace the corrupted zip files?
Same for the other issue you opened.

I'll take a look either tomorrow or next week.

**Comment by yoniv1** [comment]
> The last one works. Could you please edit you very first comment and replace the corrupted zip files? Same for the other issue you opened.
> 
> I'll take a look either tomorrow or next week.

Done!

**Comment by malmans2** [comment]
Hi @yoniv1,

It looks like none of the notebooks is using the EQC software (mainly designed to handle the row data and the cache on the VM), and they've not been executed on the VM.
Did you encounter problems on the VM or using `c3s_eqc_automatic_quality_control` on the VM?

**Comment by malmans2** [comment]
Hi @yoniv1,

I'm looking at the first notebook. For the timeseries, looks like you are just summing values, but the units become Gt/yr.
Just checking that this is correct.

**Comment by malmans2** [comment]
Hi again,

The first template is ready.
- Here is the template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/glacier_mass_balance_and_uncertainty.ipynb
- Here is the notebook executed: https://gist.github.com/malmans2/f69c800c2189a1896432adc4067dd651

As you submitted a large number of notebooks that are not in line with the other templates, it would be helpful if you start revising some of them. You should be able to do so by looking at the code structure in this template. Please start from the templates in #113 so we don't duplicate efforts.

Let me know if this notebook is OK!

**Comment by yoniv1** [comment]
> Hi again,
> 
> The first template is ready.
> 
> * Here is the template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/glacier_mass_balance_and_uncertainty.ipynb
> * Here is the notebook executed: https://gist.github.com/malmans2/f69c800c2189a1896432adc4067dd651
> 
> As you submitted a large number of notebooks that are not in line with the other templates, it would be helpful if you start revising some of them. You should be able to do so by looking at the code structure in this template. Please start from the templates in #113 so we don't duplicate efforts.
> 
> Let me know if this notebook is OK!

Hi! Thank you for the first template, it looks good! So what do you exactly expect from me to do now? That I integrate the c3s_eqc_automatic_quality_control in all of the notebooks?

**Comment by yoniv1** [comment]
> Hi again,
> 
> The first template is ready.
> 
> * Here is the template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/glacier_mass_balance_and_uncertainty.ipynb
> * Here is the notebook executed: https://gist.github.com/malmans2/f69c800c2189a1896432adc4067dd651
> 
> As you submitted a large number of notebooks that are not in line with the other templates, it would be helpful if you start revising some of them. You should be able to do so by looking at the code structure in this template. Please start from the templates in #113 so we don't duplicate efforts.
> 
> Let me know if this notebook is OK!

Hi,
There seems to be an error in the formulation of the request:

```
collection_id = "derived-gridded-glacier-mass-change"
request = {
    "variable": "glacier_mass_change",
    "product_version": "wgms_fog_2022_09",
    "format": "zip",
    "hydrological_year": [
        f"{year}_{str(year + 1)[-2:] if year + 1 != 2000 else str(year + 1)[:2]}"
        for year in range(year_start, year_stop + 1)
    ],
}
print(request)

{'variable': 'glacier_mass_change', 'product_version': 'wgms_fog_2022_09', 'format': 'zip', 'hydrological_year': ['1975_76', '1976_77', '1977_78', '1978_79', '1979_80', '1980_81', '1981_82', '1982_83', '1983_84', '1984_85', '1985_86', '1986_87', '1987_88', '1988_89', '1989_90', '1990_91', '1991_92', '1992_93', '1993_94', '1994_95', '1995_96', '1996_97', '1997_98', '1998_99', '1999_20', '2000_01', '2001_02', '2002_03', '2003_04', '2004_05', '2005_06', '2006_07', '2007_08', '2008_09', '2009_10', '2010_11', '2011_12', '2012_13', '2013_14', '2014_15', '2015_16', '2016_17', '2017_18', '2018_19', '2019_20', '2020_21']}

```

If you print the request, one of the variable names says '1999_20', which I think should be '1999_00'.

**Comment by malmans2** [comment]
Good news! Looks like ECMWF fixed it. It was 1999_20 until Friday, so I reported it to ECMWF. I'll update the template tomorrow. 

Re how to update the notebooks: Yes, I'd use c3s_eqc_automatic_quality_control and xarray as much as possible. For example, I replaced most of your loops with ds.sum, which is more efficient.

**Comment by malmans2** [comment]
Good morning @yoniv1,

I've update the template with the latest form (1999_00).
I'll work on the other 2 templates later today.

In case you missed my previous message about it, could you please confirm that this is intended?
```python
# Timeseries
ds_timeseries = ds.sum(("latitude", "longitude"), keep_attrs=True).compute()
for da in ds_timeseries.values():
    da.attrs["units"] += " yr$^{-1}$"
```
So just a sum over lat/lon but change units from Gt to Gt/yr?

**Comment by malmans2** [comment]
Hi @yoniv1,

I realised that there's a lot of duplicated code in notebook 1 and 2, so I refactored the templates.
There's now one template for producing maps, and one template for producing timeseries. All figures you made should be available in the templates. It should be easy for you to tune details (colors, labels, ...) and to decide how to organize the final notebooks (copy/paste code from the templates to produce both maps and timeseries in a single notebook).

Here are the templates:
- https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/glacier_mass_balance_maps.ipynb
- https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/glacier_mass_balance_timeseries.ipynb

Here are the notebooks executed:
- https://gist.github.com/malmans2/f69c800c2189a1896432adc4067dd651

Let me know if they're OK!

**Comment by malmans2** [comment]
Hi,

The third notebook is also ready. If you are not using the VM, make sure you are using the latest version of the eqc software (I made un update to handle shapefiles as well).

Templates:
- https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/glacier_mass_balance_maps.ipynb
- https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/glacier_mass_balance_timeseries.ipynb
- https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/glacier_distribution.ipynb

Notebooks executed:
- https://gist.github.com/malmans2/f69c800c2189a1896432adc4067dd651

Please let me know if we need to change anything or we can close the issue.

**Comment by yoniv1** [comment]
> Good morning @yoniv1,
> 
> I've update the template with the latest form (1999_00). I'll work on the other 2 templates later today.
> 
> In case you missed my previous message about it, could you please confirm that this is intended?
> 
> ```python
> # Timeseries
> ds_timeseries = ds.sum(("latitude", "longitude"), keep_attrs=True).compute()
> for da in ds_timeseries.values():
>     da.attrs["units"] += " yr$^{-1}$"
> ```
> 
> So just a sum over lat/lon but change units from Gt to Gt/yr?

Hi Mattia @malmans2,

Thanks for the remark. I think it is correct given that all mass changes are annual values, i.e. they account for each hydrological year. In that sense, I think it is correct to assign units of Gt yr-1 if you sum all mass changes over the globe for 1 specific year, as this then accounts for the total mass change of the glaciers (Gt) over that specific hydrological year (yr^-1), especially when you express it as a time series with the years on the x-axis. If you would express it as a cumulative value ( a summation over the years), it would be Gt in stead of Gt yr^-1.

**Comment by yoniv1** [comment]
> Hi,
> 
> The third notebook is also ready. If you are not using the VM, make sure you are using the latest version of the eqc software (I made un update to handle shapefiles as well).
> 
> Templates:
> 
> * https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/glacier_mass_balance_maps.ipynb
> * https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/glacier_mass_balance_timeseries.ipynb
> * https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/glacier_distribution.ipynb
> 
> Notebooks executed:
> 
> * https://gist.github.com/malmans2/f69c800c2189a1896432adc4067dd651
> 
> Please let me know if we need to change anything or we can close the issue.

Hi Mattia,

Thank you for the updates! You really did a good job cleaning up the code and make it more efficient, nice! I will try to run the notebooks later today or on monday and let you know if it works for me.

**Comment by malmans2** [comment]
OK, I just wanted to make sure that it was done on purpose.

There's probably a couple of figures in the template with wrong units then (you had a mix of Gt and Gt/yr, I wasn't exactly sure what was the criteria).

When you run the notebooks, could you please double check all units, and let me know which figures have wrong units?

**Comment by malmans2** [comment]
I've updated the units in the timeseries notebook.
Please have a look and let me know if this issue can be closed.

**Comment by yoniv1** [comment]
Hi @malmans2 

Just 1 remark:
- in the Mass balance of all glaciers: Maps notebook, the last plot has an incorrect label of the colorbar, it should be the acceleration with units Gt yr^-2. Also, the acceleration is 2 times the term in the quadratic equation that corresponds to x^2. So if the quadratic equation is 8x^2 - 4x + 2, the acceleration is 16. Please change this quantity in what is plotted on the worldmap.
For the rest, the glacier notebooks seem OK!

**Comment by malmans2** [comment]
Done: https://github.com/bopen/c3s-eqc-toolbox-template/commit/718f9a1997c1e9ba1f5126c80054b3a0a8e497a9

**Comment by yoniv1** [comment]
Hi Mattia,
Sorry to re-open a closed issue. I wonder if it is possible to change the colorbar from this map from a continuous one to a discrete one (i.e. with blocks instead of a color gradient) in blocks per 10 years starting from 1940 to 2020.

[(https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/glacier_distribution.ipynb)]

Plot glaciers distribution over years: Map
ax = plot_map(
    gdf,
    var_name="year",
    cmap="turbo",
    label="year",
    title="Glacier distribution around the year 2000 according to the RGI v6.0",
)

Thanks!

**Comment by malmans2** [comment]
Hi @yoniv1,

Done: 
![image](https://github.com/bopen/c3s-eqc-toolbox-template/assets/22245117/12947770-2ecd-4963-a5d8-993dba2c8ef5)

You can find the updated notebook at the same url.
Note that I had to change the naturalearthdata url as it was broken, hopefully the new one is more stable.

Let me know if the new plot looks OK!

**Comment by malmans2** [comment]
Closing. Feel free to re-open though if anything is not right.

**Comment by yoniv1** [comment]
HI Mattia, @malmans2 

I have a new request to be included into the Jupyter Notebook for the glacier distribution data (wp5/glacier_distribution.ipynb). 

The .shp file that is downloaded from the CDS (rgi60_global.shp) in that notebook contains an attribute table (216429x17) with information for each digitized glacier. The important columns ones are "BGNDATE", "ENDDATE", "RGIID" and "AREA". What I want to do is to calculate the area-weighted average of the year of digitization (BGNDATE+ENDDATE / 2) for each RGI region (these have a number varying from 1 to 19).

I include below the Matlab code (ran in version 2022a) that I made (it may be a bit inefficient though, but I tried to explain each step I take with some comments). 

```
clear all

T = readtable('rgi_table.csv');   % Read in the attribute table from the shape file
date_year=T(:,4);      % Extract "BGNDATE" given as YYYYMMDD
% Here I try to convert the dates given in the table to fractional years (rounded year + month/12)
% Some months in the dates are invalid (e.g. 19789999 and I discard them)
date_year = table2array(date_year);   % Convert to array
date_year_dec = (mod(date_year,10000));    % Delete first 4 digits
date_year_dec = floor(date_year_dec/100)/12;    % Remove last 2 digits so you have the number of the month left and divide it by 12 to get fractional/decimal year
date_year_dec(date_year_dec>1)=0;          % Remove fraction higher than 1 (dates with '9999') to get final fractional year
date_year = (date_year - (mod(date_year,10000))) / 10000;   % Get first 4 digits (rounded year)
date_year = date_year+date_year_dec;          % Add decimal/fractional year to rounded year

date_year_end = T(:,5);        % Extract "ENDDATE" and apply same procedure
date_year_end = table2array(date_year_end);
date_year_end_dec = (mod(date_year_end,10000));
date_year_end_dec = floor(date_year_end_dec/100)/12;
date_year_end_dec(date_year_end_dec>1)=0;
date_year_end = (date_year_end - (mod(date_year,10000))) / 10000;
date_year_end = date_year_end+date_year_end_dec;

for i = 1:size(date_year_end,1)    % Average BGNDATE+ENDDATE, only for ENDDATE that is not -9999999
    if date_year_end(i) > 0
        date_year(i) = (date_year(i)+date_year_end(i)) / 2;
    end
end

date_year(date_year<0)=NaN;      % Set remaining invalid data to NaN
glacier_area=T(:,10);       % Get glacier area
glacier_area=table2array(glacier_area);
rgi_number=T(:,2);        % Get RGI number
rgi_number=table2array(rgi_number);
newStr = extractAfter(rgi_number,"RGI60-");
newStr = extractBefore(newStr,".");
rgi_number=str2double(newStr);    % Extract RGI region number
idx=find(isnan(date_year));   % Remove remaining invalid data that were set to NaN
date_year(idx)=[];
glacier_area(idx)=[];
rgi_number(idx)=[];

clearvars newStr i date_year_end date_year_dec date_year_end_dec idx

%% Globally

% Regular mean

mean(date_year(:))
std(date_year(:));

% Weighted mean

weights = glacier_area/sum(glacier_area(:));
weighted_mean = sum(weights.*date_year)

%% For each region

rgi_region = 19;
weighted_mean = zeros(1,rgi_region);
normal_mean = zeros(1,rgi_region);
weighted_std = zeros(1,rgi_region);
normal_std = zeros(1,rgi_region);
area_region = zeros(1,rgi_region);

for i = 1:rgi_region
    date_year_region = date_year(rgi_number(:,1)==i);
    glacier_area_region = glacier_area(rgi_number(:,1)==i);
    rgi_number_region = rgi_number(rgi_number(:,1)==i);
    weights_region = glacier_area_region/sum(glacier_area_region(:));
    weighted_mean(i) = sum(weights_region.*date_year_region,'omitnan');
    weighted_std(i) = std(date_year_region,weights_region);
    normal_mean(i) = mean(date_year_region);
    normal_std(i) = std(date_year_region);
    area_region(i) = sum(glacier_area_region(:));
end

clearvars i rgi_region ans

plot(normal_mean,'b','LineWidth',2), hold on, plot(weighted_mean,'r','LineWidth',2), hold on
yline(2000,'k--','LineWidth',2)
xlabel('RGI region number');
ylabel('(Area-weighted) mean of year of digitization (AD)')
legend('Arithmetic mean','Weighted mean','Location','SouthWest')
xlim([1 19])
set(gca,'FontSize',14)
set(gcf,'color','w')
grid on, box on
```

I get the following result:

<img width="264" alt="rgi_year" src="https://github.com/bopen/c3s-eqc-toolbox-template/assets/48556227/26786ed6-c725-4133-b530-a32ab0b0c6cf">

Please let me know if anything is unclear.

Thank you!

Yoni

**Comment by yoniv1** [comment]
Hi Mattia @malmans2 

apart from my earlier request above, is it also possible to implement something in the code of the https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/glacier_mass_balance_timeseries.ipynb notebook to select a subset of the data to be plotted in the time series? For example with lat, lon, time bounds. Let’s say I want to plot the glacier mass change time series only for New-Zealand (32-50°S, 165-180°E) in the period 1978-2000? How would I do it in your code?

thanks
Yoni

**Comment by yoniv1** [comment]
> HI Mattia, @malmans2
> 
> I have a new request to be included into the Jupyter Notebook for the glacier distribution data (wp5/glacier_distribution.ipynb).
> 
> The .shp file that is downloaded from the CDS (rgi60_global.shp) in that notebook contains an attribute table (216429x17) with information for each digitized glacier. The important columns ones are "BGNDATE", "ENDDATE", "RGIID" and "AREA". What I want to do is to calculate the area-weighted average of the year of digitization (BGNDATE+ENDDATE / 2) for each RGI region (these have a number varying from 1 to 19).
> 
> I include below the Matlab code (ran in version 2022a) that I made (it may be a bit inefficient though, but I tried to explain each step I take with some comments).
> 
> ```matlab
> clear all
> 
> T = readtable('rgi_table.csv');   % Read in the attribute table from the shape file
> date_year=T(:,4);      % Extract "BGNDATE" given as YYYYMMDD
> % Here I try to convert the dates given in the table to fractional years (rounded year + month/12)
> % Some months in the dates are invalid (e.g. 19789999 and I discard them)
> date_year = table2array(date_year);   % Convert to array
> date_year_dec = (mod(date_year,10000));    % Delete first 4 digits
> date_year_dec = floor(date_year_dec/100)/12;    % Remove last 2 digits so you have the number of the month left and divide it by 12 to get fractional/decimal year
> date_year_dec(date_year_dec>1)=0;          % Remove fraction higher than 1 (dates with '9999') to get final fractional year
> date_year = (date_year - (mod(date_year,10000))) / 10000;   % Get first 4 digits (rounded year)
> date_year = date_year+date_year_dec;          % Add decimal/fractional year to rounded year
> 
> date_year_end = T(:,5);        % Extract "ENDDATE" and apply same procedure
> date_year_end = table2array(date_year_end);
> date_year_end_dec = (mod(date_year_end,10000));
> date_year_end_dec = floor(date_year_end_dec/100)/12;
> date_year_end_dec(date_year_end_dec>1)=0;
> date_year_end = (date_year_end - (mod(date_year,10000))) / 10000;
> date_year_end = date_year_end+date_year_end_dec;
> 
> for i = 1:size(date_year_end,1)    % Average BGNDATE+ENDDATE, only for ENDDATE that is not -9999999
>     if date_year_end(i) > 0
>         date_year(i) = (date_year(i)+date_year_end(i)) / 2;
>     end
> end
> 
> date_year(date_year<0)=NaN;      % Set remaining invalid data to NaN
> glacier_area=T(:,10);       % Get glacier area
> glacier_area=table2array(glacier_area);
> rgi_number=T(:,2);        % Get RGI number
> rgi_number=table2array(rgi_number);
> newStr = extractAfter(rgi_number,"RGI60-");
> newStr = extractBefore(newStr,".");
> rgi_number=str2double(newStr);    % Extract RGI region number
> idx=find(isnan(date_year));   % Remove remaining invalid data that were set to NaN
> date_year(idx)=[];
> glacier_area(idx)=[];
> rgi_number(idx)=[];
> 
> clearvars newStr i date_year_end date_year_dec date_year_end_dec idx
> 
> %% Globally
> 
> % Regular mean
> 
> mean(date_year(:))
> std(date_year(:));
> 
> % Weighted mean
> 
> weights = glacier_area/sum(glacier_area(:));
> weighted_mean = sum(weights.*date_year)
> 
> %% For each region
> 
> rgi_region = 19;
> weighted_mean = zeros(1,rgi_region);
> normal_mean = zeros(1,rgi_region);
> weighted_std = zeros(1,rgi_region);
> normal_std = zeros(1,rgi_region);
> area_region = zeros(1,rgi_region);
> 
> for i = 1:rgi_region
>     date_year_region = date_year(rgi_number(:,1)==i);
>     glacier_area_region = glacier_area(rgi_number(:,1)==i);
>     rgi_number_region = rgi_number(rgi_number(:,1)==i);
>     weights_region = glacier_area_region/sum(glacier_area_region(:));
>     weighted_mean(i) = sum(weights_region.*date_year_region,'omitnan');
>     weighted_std(i) = std(date_year_region,weights_region);
>     normal_mean(i) = mean(date_year_region);
>     normal_std(i) = std(date_year_region);
>     area_region(i) = sum(glacier_area_region(:));
> end
> 
> clearvars i rgi_region ans
> 
> plot(normal_mean,'b','LineWidth',2), hold on, plot(weighted_mean,'r','LineWidth',2), hold on
> yline(2000,'k--','LineWidth',2)
> xlabel('RGI region number');
> ylabel('(Area-weighted) mean of year of digitization (AD)')
> legend('Arithmetic mean','Weighted mean','Location','SouthWest')
> xlim([1 19])
> set(gca,'FontSize',14)
> set(gcf,'color','w')
> grid on, box on
> ```
> 
> I get the following result:
> 
> <img alt="rgi_year" width="264" src="https://private-user-images.githubusercontent.com/48556227/312841159-26786ed6-c725-4133-b530-a32ab0b0c6cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MDUzMzgsIm5iZiI6MTcxMDcwNTAzOCwicGF0aCI6Ii80ODU1NjIyNy8zMTI4NDExNTktMjY3ODZlZDYtYzcyNS00MTMzLWI1MzAtYTMyYWIwYjBjNmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE5NTAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYzBjZmI0NWYzMmQyNzdiMjJiZThiOTZjN2Q3ODMwNWZhZjRkMjRkNGJiMjJiNjZlMGUyODdiOGU4NGFmYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VmjfxNlrtKPbs1M4I7l5BlkDTzicbxpKm4nS0OcAqUo">
> Please let me know if anything is unclear.
> 
> Thank you!
> 
> Yoni

Hi Mattia,

I managed to do something in Python, I guess it is very inefficient though it works:

[
[glacier_distribution (1).ipynb.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/14628676/glacier_distribution.1.ipynb.zip)
](url)

**Comment by malmans2** [comment]
Got it, thanks.
I should be able to work on this either today in the afternoon or tomorrow morning.

**Comment by malmans2** [comment]
Hi @yoniv1,
What's the new code I need to revise in you notebook. I don't see anything new.

**Comment by malmans2** [comment]
I implemented the area weighted mean in the template:
```python
def weighted_average(df, field_name, weights_name):
    df = df[df[field_name].notnull() & df[weights_name].notnull()]
    weights = df[weights_name]
    return (df[field_name] * weights).sum() / weights.sum()


gdf["region"] = gdf["RGIID"].str[6:8].astype(int)
grouped = gdf[["year", "AREA", "region"]].groupby("region")
arithmetic_year = grouped["year"].mean()
weighted_year = grouped.apply(weighted_average, "year", "AREA", include_groups=False)

ax = arithmetic_year.plot(label="arithmetic")
ax = weighted_year.plot(label="weighted")
ax.set_xlabel("RGI region number")
ax.set_ylabel("Year of digitalization")
ax.grid()
_ = ax.legend()
```
![image](https://github.com/bopen/c3s-eqc-toolbox-template/assets/22245117/2cb75582-751e-452b-9b23-5ca1a639833c)

I'll take a look a [this](https://github.com/bopen/c3s-eqc-toolbox-template/issues/112#issuecomment-2000045038) later today.

(Your issues have many notebooks/requests/discussions unrelated to each other, it's very hard for us to keep track of the progress. From now on please open separate issues for each notebook)

**Comment by malmans2** [comment]
@yoniv1 you can now select a subset of regions in [this notebook](https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/glacier_mass_balance_timeseries.ipynb).
For example, if you set `regions_abbrev = ["NZL"]` it will only select New Zeland.

I'm going to close this issue. Please open new issues if there's any problem with the modifications or you need further help.
