### ISSUE TITLE
Jupyter notebooks for ice sheet ECVs

### ISSUE THREAD

**Issue by yoniv1** [bopen/c3s-eqc-toolbox-template#113]
### Notebook description

**Notebook 1 (C3S_IC_GrIS_IV_UC1):**

Quality assessment: Greenland ice sheet annual gridded velocity data from 2017 to present derived from satellite observations
Use Case: A study on the spatial variability of the uncertainty and fitness-for-purpose of the GrIS ice velocity product.
Use Question: How accurate is the GrIS ice velocity product and how does the uncertainty vary in space across the ice sheet?

**Notebook 2 (C3S_IC_GMB_UC1):**

Quality assessment: Gravimetric mass balance data for the Antarctic and Greenland ice sheets from 2003 to 2020 derived from satellite observations
Use Case: A study on the monthly and annual variability of the Greenland (GrIS) and Antarctic Ice Sheet (AIS) gravimetric mass balance (GMB) and its trend over time.
User Question: How well are the GrIS and AIS GMB products on the CDS suited to derive mean values, temporal variability and trends?

**Notebook 3 (C3S_IC_GMB_UC2):**

Quality assessment: Gravimetric mass balance data for the Antarctic and Greenland ice sheets from 2003 to 2020 derived from satellite observations
Use Case: A study on the accuracy of the GrIS and AIS gravimetric mass balance.
User Question: How accurate are the ice sheet gravimetric mass balance data for the GrIS and the AIS?

**Notebook 4 (C3S_IC_SEC_UC1):**

Quality assessment: Ice sheet surface elevation change rate for Greenland and Antarctica from 1992 to present derived from satellite observations
Use Case: A study on the monthly and annual variability of the Greenland (GrIS) and Antarctic Ice Sheet (AIS) surface elevation change (SEC) and its trend over time.
User Question: How well are the GrIS and AIS SEC products on the CDS suited to derive mean values, temporal variability and trends?

**Notebook 5 (C3S_IC_SEC_UC2):**

Quality assessment: Ice sheet surface elevation change rate for Greenland and Antarctica from 1992 to present derived from satellite observations
Use Case: A study on the spatial variability of the uncertainty / fitness-for-purpose of the GrIS and AIS surface elevation change product.
User Question: How accurate are the GrIS and AIS surface elevation change products and how does the uncertainty vary in space across the ice sheets?

### Notebook link or upload

[C3S_IC_GMB_UC1.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/13319397/C3S_IC_GMB_UC1.zip)
[C3S_IC_GMB_UC2.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/13319398/C3S_IC_GMB_UC2.zip)
[C3S_IC_GrIS_IV_UC1.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/13319399/C3S_IC_GrIS_IV_UC1.zip)
[C3S_IC_SEC_UC1.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/13319400/C3S_IC_SEC_UC1.zip)
[C3S_IC_SEC_UC2.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/13319401/C3S_IC_SEC_UC2.zip)

### Anything else we need to know?

Download folder is still listed as my local folder

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Hi @yoniv1,

The first template is ready. This one changed quite a bit, so please carefully check it and let me know if I'm doing anything wrong.

The main difference is that there's no need to use astropy nor convert the time axis.
Most of xarray, pandas, and numpy methods support datetime64 data (under the hood, they are stored in nanoseconds).
Therefore, we can use the original data. Note that the original data does not have monthly frequency (there are missing months as you pointed out in the notebook, but there's also a few months with more samples).

- Here is the template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/gravimetric_mass_balance_trends.ipynb
- Here is he notebook executed: https://gist.github.com/malmans2/0b0ac8de9d4888b21f1c177dc811ef42

**Comment by malmans2** [comment]
Hi there,

The second notebook is ready. I integrated it to the first template, so same links as above.
Could you please check the errors units. In your notebook you compute the mean error, but then the units are changed from Gt to Gt/month. Is that right?

**Comment by malmans2** [comment]
Hello,

The third notebook is also ready. I think the zoom in you notebook was wrong (y axis is flipped). I fixed it in the template.

Here are the templates:

- https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/gravimetric_mass_balance_trends.ipynb
- https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/greenland_ice_velocity.ipynb

Here are the notebooks executed:
- https://gist.github.com/malmans2/0cf65fb6673840d8f145ea23208bfad8

**Comment by malmans2** [comment]
Hi @yoniv1,

Unfortunately I can not work on the last two notebooks at the moment.
The product you are using is currently under maintenance: https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-ice-sheet-elevation-change?tab=overview

I'll let you know when I'm able to download those data.

**Comment by yoniv1** [comment]
> Hi @yoniv1,
> 
> The first template is ready. This one changed quite a bit, so please carefully check it and let me know if I'm doing anything wrong.
> 
> The main difference is that there's no need to use astropy nor convert the time axis. Most of xarray, pandas, and numpy methods support datetime64 data (under the hood, they are stored in nanoseconds). Therefore, we can use the original data. Note that the original data does not have monthly frequency (there are missing months as you pointed out in the notebook, but there's also a few months with more samples).
> 
> * Here is the template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/gravimetric_mass_balance_trends.ipynb
> * Here is he notebook executed: https://gist.github.com/malmans2/0cf65fb6673840d8f145ea23208bfad8

Hi @malmans2 

Looks good! I'll run it on monday. Is there any way we can make those 14.1% missing months in the time series visible? For example by a shaded interval in the background of the time series if a temporal data point is missing?

Thanks!

**Comment by yoniv1** [comment]
> Hi there,
> 
> The second notebook is ready. I integrated it to the first template, so same links as above. Could you please check the errors units. In your notebook you compute the mean error, but then the units are changed from Gt to Gt/month. Is that right?

Hi Mattia @malmans2,

I think the units of individual monthly GMB measurements and their errors have units Gt month-1 (as the temporal resolution is more or less a month (not exactly though) and thus also their mean value have those units) whereas seen cumulatively, the units change to Gt (as in the time series)

**Comment by malmans2** [comment]
Hi,

Please have a look at the latest template and let me know if any units is not correct.
I've added markers to the timeseries so it's easy to spot when there's larger time gaps (shades would require some sort of interpolation). Also, I've added a plot with the time difference in month.

**Comment by yoniv1** [comment]
> * https://gist.github.com/malmans2/0cf65fb6673840d8f145ea23208bfad8

Hi @malmans2 

Looks good! Just a few remarks:
- in the GMB notebook in your new time gap plot, what does it mean if there is a time gap of 0 months? Does this mean 2 measurements were conducted in the same month? In that case, it might be a bit confusing, since this could be for example 2 measurements on 1 January and 31 January respectively, and then you would still have a time gap of 0 months between two measurements. 
- Can you put units [yr] for time series which have time on the x-axis?
- Can you change the units for the error estimate time series to Gt month^-1 as well (not the error bars, but the graph above it)?
- In the printed out text of the acceleration of the mass changes, can you change the acceleration to 2*x^2 (as with the glacier mass change notebook, see my other issue on Github). So the equation for Antarctica is -1.177x^2 + ..., the acceleration is then -2.354 Gt yr^-2.
- In the velocity notebook, can you make the Greenland maps a bit more elongated along the y-axis (i.e. so the map get stretched out a bit more above and below, it looks quite compressed now).

Thanks!

**Comment by malmans2** [comment]
> * in the GMB notebook in your new time gap plot, what does it mean if there is a time gap of 0 months? Does this mean 2 measurements were conducted in the same month? In that case, it might be a bit confusing, since this could be for example 2 measurements on 1 January and 31 January respectively, and then you would still have a time gap of 0 months between two measurements.

That's the point I was tying to make about units. Sometimes the gap is much less then a month. This is what I was doing:
compute gap (in ns), convert to months, round to integer. I removed the rounding step, so you can see the exact gap. The minimum gap is 0.35month, which is about 11 days.

> * Can you put units [yr] for time series which have time on the x-axis?

Done, but be careful! The time unit is encoded in the datetime object, technically speaking it's not correct to hardcode it. When you plot time axis, xarray/matplolib/pandas are quite smart and pick a sensible string format for the ticks. Because you have a long timeseries, YYYY is chosen. If your timeseries was shorter (e.g., 1 month), you'd see YYYY-DD-MM.

> * Can you change the units for the error estimate time series to Gt month^-1 as well (not the error bars, but the graph above it)?

Done

> * In the printed out text of the acceleration of the mass changes, can you change the acceleration to 2*x^2 (as with the glacier mass change notebook, see my other issue on Github). So the equation for Antarctica is -1.177x^2 + ..., the acceleration is then -2.354 Gt yr^-2.

Done

> * In the velocity notebook, can you make the Greenland maps a bit more elongated along the y-axis (i.e. so the map get stretched out a bit more above and below, it looks quite compressed now).

Data is cached, you should be able to tune the plots yourself and decide how you want to present the results (e.g., change labels, figure sizes, colors, ...). The goal of these templates is just to help you out developing efficient notebooks, so they are quite general.
Side note: I'm using equal aspect ration for x/y axis. I thought that's the right way to plot using the underlying projection (I believe it's ESPG4326). If that's not the right projection, you should probably reproject (e.g., get a lat/lon projection rather than x/y), and plot using cartopy. If you don't care about the projection, you can just remove the equal axis constraint in the plotting function.

Let me know if the new template looks OK. In the meantime, I'll work on the last 2 notebooks. Looks like those data is now available on the CDS.

**Comment by yoniv1** [comment]
> > * in the GMB notebook in your new time gap plot, what does it mean if there is a time gap of 0 months? Does this mean 2 measurements were conducted in the same month? In that case, it might be a bit confusing, since this could be for example 2 measurements on 1 January and 31 January respectively, and then you would still have a time gap of 0 months between two measurements.
> 
> That's the point I was tying to make about units. Sometimes the gap is much less then a month. This is what I was doing: compute gap (in ns), convert to months, round to integer. I removed the rounding step, so you can see the exact gap. The minimum gap is 0.35month, which is about 11 days.
> 
> > * Can you put units [yr] for time series which have time on the x-axis?
> 
> Done, but be careful! The time unit is encoded in the datetime object, technically speaking it's not correct to hardcode it. When you plot time axis, xarray/matplolib/pandas are quite smart and pick a sensible string format for the ticks. Because you have a long timeseries, YYYY is chosen. If your timeseries was shorter (e.g., 1 month), you'd see YYYY-DD-MM.
> 
> > * Can you change the units for the error estimate time series to Gt month^-1 as well (not the error bars, but the graph above it)?
> 
> Done
> 
> > * In the printed out text of the acceleration of the mass changes, can you change the acceleration to 2*x^2 (as with the glacier mass change notebook, see my other issue on Github). So the equation for Antarctica is -1.177x^2 + ..., the acceleration is then -2.354 Gt yr^-2.
> 
> Done
> 
> > * In the velocity notebook, can you make the Greenland maps a bit more elongated along the y-axis (i.e. so the map get stretched out a bit more above and below, it looks quite compressed now).
> 
> Data is cached, you should be able to tune the plots yourself and decide how you want to present the results (e.g., change labels, figure sizes, colors, ...). The goal of these templates is just to help you out developing efficient notebooks, so they are quite general. Side note: I'm using equal aspect ratio for x/y axis. I thought that's the right way to plot using the underlying projection (I believe it's ESPG4326). If that's not the right projection, you should probably reproject (e.g., get a lat/lon projection rather than x/y), and plot using cartopy. If you don't care about the projection, you can just remove the equal axis constraint in the plotting function.
> 
> Let me know if the new template looks OK. In the meantime, I'll work on the last 2 notebooks. Looks like those data is now available on the CDS.

Hi Mattia,

Thanks for the changes, it looks good!

**Comment by malmans2** [comment]
Hi @yoniv1,

The ice sheet templates are also ready.
I've added 3 new templates:

1. https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/ice_sheet_all_data.ipynb
2. https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/ice_sheet_maps.ipynb
3. https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/ice_sheet_timeseries.ipynb

Here are the notebook executed: https://gist.github.com/malmans2/2e65212b09ce252edcab3fed63b92677

Please let me know if they work OK.

**Comment by yoniv1** [comment]
> Hi @yoniv1,
> 
> The ice sheet templates are also ready. I've added 3 new templates:
> 
> 1. https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/ice_sheet_all_data.ipynb
> 2. https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/ice_sheet_maps.ipynb
> 3. https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/ice_sheet_timeseries.ipynb
> 
> Here are the notebooks executed: https://gist.github.com/malmans2/2e65212b09ce252edcab3fed63b92677
> 
> Please let me know if they work OK.

Hi @malmans2 

This looks great, thanks!
