### ISSUE TITLE
Problem with port22 and connection to VM

### ISSUE THREAD

**Issue by FaezehKarimian** [bopen/c3s-eqc-toolbox-template#114]
### What happened?

Hi,
I have problem to not connect to the VM. I receive the error :  "Connection timed out"
<img width="792" alt="Connection time out problem" src="https://github.com/bopen/c3s-eqc-toolbox-template/assets/139398543/d06f5252-0872-49bb-ab0e-f6ab82614282">
 Should I change something in my local machine?
Thanks!

### Environment

<details>

</details>

**Comment by FaezehKarimian** [comment]
Okay, thanks.

**Comment by malmans2** [comment]
Looks like the VM is back
