### ISSUE TITLE
[CMIP6] notebook to see when Arctic shipping routes would be clear

### ISSUE THREAD

**Issue by tdcwilliams** [bopen/c3s-eqc-toolbox-template#116]
### Notebook description

Evaluate extent inside masks corresponding to transpolar shipping route and northern sea route - if 0 it is clear > check consensus between models.

### Notebook link or upload

[cmip6_sea_ice_Arctic_shipping.ipynb.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/13422030/cmip6_sea_ice_Arctic_shipping.ipynb.zip)

### Anything else we need to know?

I have noticed problems in interpolation of some models. This will also affect #103, #102 and  #24.

Models not interpolated correctly:
access_cm2
canesm5
canesm5_canoe
cmcc_cm2_sr5
cmcc_esm2
cnrm_cm6_1
cnrm_esm2_1
hadgem3_gc31_ll
hadgem3_gc31_mm
ipsl_cm6a_lr
kiost_esm
miroc6
noresm2_lm
noresm2_mm
ukesm1_0_ll
access_esm1_5
cams_csm1_0

### Environment

wp4 environment in VM

**Comment by tdcwilliams** [comment]
If you work on the interpolation issue I can work on the plotting and then you could run the full time period 2015-2100.
Unfortunately you'd need to rerun #102 and #24 once the interpolation is fixed.

**Comment by malmans2** [comment]
Hi @tdcwilliams,

I'm just glancing through it, I will work on this tomorrow, and hopefully I'll be able to cache everything over the weekend.

Let me make sure I'm understanding it correctly. The final notebook will be very similar to [this](https://gist.github.com/malmans2/3db833049d5bed834759113179ddb8ce), however instead of computing the diagnostics for the whole Arctic/Antarctic you need to mask out the grid points outside tsr and nsr. The mask is defined in the get tsr/nsr functions.

Because ERA5 and CMIP6 are interpolated to the satellite grid, can we apply the mask after interpolation?

I thought in the latest version of the notebook we fixed the interpolation issue. I will double check though!

**Comment by tdcwilliams** [comment]
Hi @malmans2,

- yes that's right about the masking outside tsr and nsr. This is how I implemented it as interpolating first and then applying the masks. Could you also add a figure `diagnostics.plot` showing the 2 masks? I wasn't quite sure how to do it, but maybe I can figure it out.
- we did fix the interpolation of era5 (and similar output grids), but it looks like this did not work for the models I mentioned above. Maybe the original conservative method works for these ones? I guess there are other options too. The notebook has a test function to show how every model looks after interpolation.
- can you let me know when you are rerunning #24 notebook? I have a small change to the code that would let me add some maps.

Thanks a lot!

**Comment by tdcwilliams** [comment]
Hi @malmans2,

- yes that's right about the masking outside tsr and nsr. This is how I implemented it as interpolating first and then applying the masks. Could you also add a figure `diagnostics.plot` showing the 2 masks? I wasn't quite sure how to do it, but maybe I can figure it out.
- we did fix the interpolation of era5 (and similar output grids), but it looks like this did not work for the models I mentioned above. Maybe the original conservative method works for these ones? I guess there are other options too. The notebook has a test function to show how every model looks after interpolation.
- can you let me know when you are rerunning #24 notebook? I have a small change to the code that would let me add some maps.

Thanks a lot!

**Comment by tdcwilliams** [comment]
Hi @malmans2 ,
I had a look at the interpolation myself last night.
With `interpolation_kwargs = {'method': 'nearest_s2d', 'periodic': True, 'ignore_degenerate': True}`,
only 3 failed (changed from bilinear interp)
```
new_bad = [
    "fio_esm_2_0", #weird, OK with bilinear
    "kiost_esm", # weird
    'noresm2_lm',#zero everywhere
]
```
I couldn't get conservative interp to work. If you have time you could try to see what is happening with these 3, but if not we could just leave them out.

**Comment by tdcwilliams** [comment]
Hi again @malmans2,
for the notebook in #24, can the code be changed to this?
```
def interpolate_to_satellite_grid(obj, region, **regrid_kwargs):
    collection_id = "satellite-sea-ice-concentration"
    request = {
        "version": "v2",
        "variable": "all",
        "format": "zip",
        "origin": "esa_cci",
        "cdr_type": "cdr",
        "year": "2002",
        "month": "06",
        "day": "01",
        "region": region,
    }
    grid_out = download.download_and_transform(collection_id, request).drop_dims("time")
    return diagnostics.regrid(obj, grid_out, **regrid_kwargs)


def compute_interpolated_sea_ice_extent_and_area(ds, sic_threshold, **regrid_kwargs):
    """
    Interpolate to 25x25km grid and return sea ice diagnostics.

    Parameters
    ----------
    ds: xr.Dataset
        Dataset to process
    sic_threshold: float
        Sea ice concentration threshold (%)
    **regrid_kwargs: Any
        xesmf regrid kwargs

    Returns
    -------
    xr.Dataset
        Dataset with siarea and siextend (km2)
    """
    ds = ds.cf[["latitude", "longitude", "sea_ice_area_fraction"]]

    # Monthly resample
    ds = ds.sortby("time").resample(time="MS").mean()
    ds["time"].attrs["long_name"] = "time"

    if regrid_kwargs:
        interpolated_objs = []
        for region in ("northern_hemisphere", "southern_hemisphere"):
            obj_out = interpolate_to_satellite_grid(ds, region, **regrid_kwargs)
            interpolated_objs.append(obj_out.expand_dims(region=[region]))
        ds = xr.concat(interpolated_objs, "region")

    return compute_extent_and_area_from_sic(ds, sic_threshold, grid_cell_area=25**2)
```

When I am trying to make maps I want to be able to do one region at a time since combining the Arctic and Antarctic regions into one dataset means the spatial coverage goes back to the whole globe again (filled with missing data).

For #102 I'd need the same interpolation function before it was rerun with the new `interpolation_kwargs`

**Comment by malmans2** [comment]
Hi @tdcwilliams,

It looks to me that xesmf is not very robust in interpolations with curvilinear periodic grids at the poles.
Nevertheless, it seems that using a nearest interpolation after filling nans with 0 works out OK with all of them (still exploring it).

Do you see any downside in replacing all NaNs with zeros? Should be OK for variables such as sea ice concentration, right?

**Comment by tdcwilliams** [comment]
Hi @malmans2, yes zeros on land etc should be OK for concentration.

**Comment by malmans2** [comment]
Just a note about nearest interpolation filling with zeros. When the input resolution is quite small, you can get this kind of results:

![Screenshot 2023-11-24 at 13 59 41](https://github.com/bopen/c3s-eqc-toolbox-template/assets/22245117/629761aa-c53e-48b5-a795-8aa793486950)

Is it OK to do this to fix it?
```python
sic_cmip6_interpolated = sic_cmip6_interpolated.where(sic_satellite.notnull())
```
Alternatively, we could do this:
```python
mask = (sic_cmip6_interpolated != 0) & (sic_satellite.fillna(0) != 0)
sic_cmip6_interpolated = sic_cmip6_interpolated.where(mask)
sic_satellite = sic_satellite.where(mask)
```

What do you think?

**Comment by tdcwilliams** [comment]
Hi @malmans2 - I think maybe better not then (the Antarctic one especially looks quite weird). Then we can just leave out the 3 models that were failing before.
I didn't look at the Antarctica maps with those options though - do they look OK?

**Comment by malmans2** [comment]
Hi @tdcwilliams,

I agree, better to retain NaNs. Actually, I just realised why we get sea ice on land.
It's because in that model they removed the southern rows with land only, so nearest interpolation results in sea points assigned to Antarctica. Let me know if you prefer to skip that model or implement an ad-hoc solution (I think the only general solution would be to mask out land using satellite data after the interpolation).

There's another issue that I was able to fix. Some of the models (CNR) have a column of nans on the eastern side. So I just removed that before interpolating.

Here are a few and quick and dirty plots: https://gist.github.com/malmans2/8fb36b1022daa153a3459feb50a75943

Let me know if nearest interpolation is OK, and which models you'd like to skip.

**Comment by malmans2** [comment]
> Hi again @malmans2, for the notebook in #24, can the code be changed to this?
> 
> ```
> def interpolate_to_satellite_grid(obj, region, **regrid_kwargs):
>     collection_id = "satellite-sea-ice-concentration"
>     request = {
>         "version": "v2",
>         "variable": "all",
>         "format": "zip",
>         "origin": "esa_cci",
>         "cdr_type": "cdr",
>         "year": "2002",
>         "month": "06",
>         "day": "01",
>         "region": region,
>     }
>     grid_out = download.download_and_transform(collection_id, request).drop_dims("time")
>     return diagnostics.regrid(obj, grid_out, **regrid_kwargs)
> 
> 
> def compute_interpolated_sea_ice_extent_and_area(ds, sic_threshold, **regrid_kwargs):
>     """
>     Interpolate to 25x25km grid and return sea ice diagnostics.
> 
>     Parameters
>     ----------
>     ds: xr.Dataset
>         Dataset to process
>     sic_threshold: float
>         Sea ice concentration threshold (%)
>     **regrid_kwargs: Any
>         xesmf regrid kwargs
> 
>     Returns
>     -------
>     xr.Dataset
>         Dataset with siarea and siextend (km2)
>     """
>     ds = ds.cf[["latitude", "longitude", "sea_ice_area_fraction"]]
> 
>     # Monthly resample
>     ds = ds.sortby("time").resample(time="MS").mean()
>     ds["time"].attrs["long_name"] = "time"
> 
>     if regrid_kwargs:
>         interpolated_objs = []
>         for region in ("northern_hemisphere", "southern_hemisphere"):
>             obj_out = interpolate_to_satellite_grid(ds, region, **regrid_kwargs)
>             interpolated_objs.append(obj_out.expand_dims(region=[region]))
>         ds = xr.concat(interpolated_objs, "region")
> 
>     return compute_extent_and_area_from_sic(ds, sic_threshold, grid_cell_area=25**2)
> ```
> 
> When I am trying to make maps I want to be able to do one region at a time since combining the Arctic and Antarctic regions into one dataset means the spatial coverage goes back to the whole globe again (filled with missing data).
> 
> For #102 I'd need the same interpolation function before it was rerun with the new `interpolation_kwargs`

I think I'm going to refactor a bit the notebook, so the cached function will accept an argument to choose the region (right now the loop over northern/southern hemisphere is hardcoded).

What kind of maps do you need to make? Right now we are only caching timeseries, we could add different functions to cache 2D data.

**Comment by malmans2** [comment]
Looking at the 2 masks now. I think we can simplify the first one as follows:
```python
from c3s_eqc_automatic_quality_control import download
import xarray as xr
import numpy as np


collection_id = "satellite-sea-ice-concentration"
request = {
    "region": "northern_hemisphere",
    "version": "v2",
    "variable": "all",
    "format": "zip",
    "origin": "esa_cci",
    "cdr_type": "cdr",
    "year": "2002",
    "month": "06",
    "day": "01",
}
ds = download.download_and_transform(collection_id, request)

def get_tim_tsr(lon_in, lat):
    # make longitude > 0
    lon = lon_in.copy()
    lon[lon < 0] += 360.0

    # Define approximate GODAE limits
    limits = {
        "Chuckchi_Sea": {
            "lon_min": 180.0,
            "lon_max": 200.0,
            "lat_min": 66.0,
            "lat_max": 90.0,
        },
        "SLK": {
            "lon_min": 35.0,
            "lon_max": 180.0,
            "lat_min": 65.0,
            "lat_max": 83.0,
        },  # Siberian, Laptev, Kara Seas
        "Barents_Sea": {
            "lon_min": 5.0,
            "lon_max": 35.0,
            "lat_min": 68.0,
            "lat_max": 90.0,
        },
    }

    # set Siberian/Laptev/Kara seas lat_max to vary linearly with longitude
    y0 = 83
    y1 = 83
    x0 = limits["SLK"]["lon_min"]
    x1 = limits["SLK"]["lon_max"]
    limits["SLK"]["lat_max"] = y0 + 0.5 * (y1 - y0) * (
        1 + np.cos(2 * np.pi * (lon - x0) / (x1 - x0))
    )

    # set masks
    mask = np.zeros_like(lon, dtype=bool)
    for sea, sea_limits in limits.items():
        lon_inside = (lon >= sea_limits["lon_min"]) * (lon < sea_limits["lon_max"])
        if sea in ["Barents_Sea", "Chuckchi_Sea"]:
            # include Barents and Chuckchi Seas in the TSR
            mask += lon_inside * (lat >= sea_limits["lat_min"])
        else:
            mask += lon_inside * (lat >= sea_limits["lat_max"])
    return mask

def get_mattia_tsr(lon, lat):
    # Define approximate GODAE limits
    limits = {
        "Chuckchi_Sea": {
            "lon_min": 180.0,
            "lon_max": 200.0,
            "lat_min": 66.0,
            "lat_max": 90,
        },
        "Siberian_Laptev_Kara_Seas": {
            "lon_min": 35.0,
            "lon_max": 180.0,
            "lat_min": 83.0,
            "lat_max": 90,
        },
        "Barents_Sea": {
            "lon_min": 5.0,
            "lon_max": 35.0,
            "lat_min": 68.0,
            "lat_max": 90,
        },
    }

    # Convert longitude
    lon = lon.where(lon >= 0, lon + 360)

    mask = xr.zeros_like(lon)
    for sea_limits in limits.values():
        sea_mask = (
            (lon >= sea_limits["lon_min"])
            & (lon <= sea_limits["lon_max"])
            & (lat >= sea_limits["lat_min"])
            & (lat <= sea_limits["lat_max"])
        )
        mask = xr.where(sea_mask, 1, mask)
    return mask

    
tim_tsr = get_tim_tsr(ds["longitude"].values, ds["latitude"].values)
mattia_tsr = get_mattia_tsr(ds["longitude"], ds["latitude"])
np.testing.assert_equal(tim_tsr, mattia_tsr.values)
mattia_mask.plot()
```

**Comment by tdcwilliams** [comment]
Hi @malmans2,
- we can skip fio_esm_2_0, kiost_esm and noresm2_lm and just use nearest_s2d interpolation
- new tsr code looks good
- for the mapping, I was thinking about sequences of 10-year averages, looking like the test plots in the notebook I sent here. I have some code I can send. Maybe I should make a new issue about that.

**Comment by malmans2** [comment]
Yes, please open a new issue and let me know which variables you want to plot in the maps.

**Comment by malmans2** [comment]
Hi @tdcwilliams,

I revised one of the templates. You can now chose masks.
Could you please take a look and let me know if it looks OK?

- Here is the template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp4/cmip6_sea_ice_evaluation.ipynb
- Here is the notebook executed: https://gist.github.com/malmans2/6d4ce1d9cb31134f66a8e38d478c3044

**Comment by tdcwilliams** [comment]
Hi @malmans2,
thanks a lot for that. It is actually interesting to have the evaluations done for the specific masks as well to get an idea of how much to trust the projections in those particular areas. The projections are the most interesting part of the shipping routes notebook though - just getting the extent for all the models and experiments from the sea ice diagnostics notebooks when they are limited to the shipping routes.
So the main priority would be now to cache the extents from the projections, and then I can make some figures from the data.

The code for the masking looks great.
For the illustrations of the mask, we could zoom in more eg `isel(xc=slice(50,-100), yx=slice(50,-50))`

**Comment by malmans2** [comment]
Hi @tdcwilliams,

> So the main priority would be now to cache the extents from the projections, and then I can make some figures from the data.

Do you mean that the priority is to do the same for [this notebook](https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp4/cmip6_sea_ice_diagnostics.ipynb)? If yes, I'm running the scripts to populate the cache right now. I'll let you know when it's ready.

Meanwhile, I added the zoom dropping NaNs rather than hardcoding the x/y limits: https://gist.github.com/malmans2/6d4ce1d9cb31134f66a8e38d478c3044

**Comment by tdcwilliams** [comment]
Hi @malmans2 
Thanks a lot for caching that data.
- For the sea ice diagnostics I need all the data though (historical and projections).
  It is just for the shipping routes that the projections are the main priority.
- By the way, the evaluation notebook should have the whole Arctic evaluated.
  I can still use the tsr and nsr evaluation in the shipping route notebook though.

**Comment by tdcwilliams** [comment]
Hi @malmans2, how is the caching going for the notebooks?

**Comment by malmans2** [comment]
Hi @tdcwilliams,

For the diagnostics notebook, `historical` and `ssp1_2_6` are cached
Here are the notebooks executed if you want to take a look at the results: https://gist.github.com/malmans2/6d4ce1d9cb31134f66a8e38d478c3044
(In the notebooks all sea masks are used, but you can easily select a subset if you need)

ssp2_4_5 is about 50% done, ssp3_7_0 and ssp5_8_5 will start right after.

**Comment by tdcwilliams** [comment]
Thanks @malmans2, that looks really good.

**Comment by malmans2** [comment]
Hi @tdcwilliams,

Everything is cached.
Here are the templates:
- https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp4/cmip6_sea_ice_diagnostics.ipynb
- https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp4/cmip6_sea_ice_evaluation.ipynb

Here is the notebook executed: https://gist.github.com/malmans2/6d4ce1d9cb31134f66a8e38d478c3044

Hi lost a bit track of this issue. Do you have everything you need for the timeseries notebook?
I'll work on maps (#119) next week.

**Comment by tdcwilliams** [comment]
Hi @malmans2, thanks I have it and will send it later with the plotting
routines I ended up using. It worked out quite well in the end.
 I might not need you to work on the maps after all - I'll let you know if
I do.

**Comment by tdcwilliams** [comment]
Hi @malmans2, here is how the diagnostics notebook turned out (just one map needed in the end to explain an unexpected result for the transpolar shipping route)

[cmip6_sea_ice_diagnostics.ipynb.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/13512177/cmip6_sea_ice_diagnostics.ipynb.zip)
