### ISSUE TITLE
notebook permanent link

### ISSUE THREAD

**Issue by chiaravol** [bopen/c3s-eqc-toolbox-template#117]
### Notebook description

Hi Mattia,

We'd like to add/create the link to our jupyter notebook, but we cannot find the right repository in github/ecmwf-projects.

Could you help?

Thanks,
Chiara

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Here it is: https://github.com/ecmwf-projects/c3s2-eqc-quality-assessment

It's possible that you don't have access yet. I just reminded ECMWF to add some users.
When they add you, you will get an invitation to join the repo.

**Comment by malmans2** [comment]
The invites have been sent, check your email associated with GitHub.
Please close this issue if you have access to the repo.

**Comment by chiaravol** [comment]
Thanks Mattia.
I can see the right repository now. We can close the issue.
