### ISSUE TITLE
Error with diagnostic.py 

### ISSUE THREAD

**Issue by paololanteri** [bopen/c3s-eqc-toolbox-template#12]
While running the template for climate projections I encountered the following error:

--------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_1946/2118281780.py in <module>
      4
      5 import c3s_eqc_toolbox_template
----> 6 from c3s_eqc_automatic_quality_control.c3s_eqc_automatic_quality_control import diagnostics, download, plot
      7
      8 warnings.filterwarnings("ignore")

~/bin/c3s_eqc_automatic_quality_control/c3s_eqc_automatic_quality_control/diagnostics.py in <module>
     23
     24 def _spatial_weights(
---> 25     obj: xr.Dataset | xr.DataArray, lon: str = "longitude", lat: str = "latitude"
     26 ) -> xr.DataArray:
     27     cos = np.cos(np.deg2rad(obj[lat]))

TypeError: unsupported operand type(s) for |: 'ABCMeta' and 'type'

Let me recap the steps I made:
-I downloaded the latest version of c3s-eqc-toolbox-template and c3s-eqc-automatic-quality-control from b-open github webpage
-i put them in the VM under /data/wp4/bin/
-I run the notebook template you developed for climate projections and I get the error above.

Any error from my side?
Thank you

**Comment by malmans2** [comment]
I think you are just using the wrong version of python. We only test python 3.10 at the moment.
You should follow these instructions: https://github.com/bopen/c3s-eqc-toolbox-template#workflow-for-developerscontributors

Here is a recap (just substitute `DEVELOP` with the name of your environment):
```
git clone git@github.com:bopen/c3s-eqc-toolbox-template.git
cd c3s-eqc-toolbox-template
conda create -n DEVELOP -c conda-forge python=3.10
conda activate DEVELOP
make conda-env-update
```

**Comment by malmans2** [comment]
I think you are just missing the ssh key for GitHub. But you don't really need it, the template repo is public.
Try to clone from `https`:
```
git clone https://github.com/bopen/c3s-eqc-toolbox-template.git
```

**Comment by paololanteri** [comment]
Thank you Mattia, I can run the notebook templates for climate projection correctly now!

**Comment by malmans2** [comment]
Great!
