### ISSUE TITLE
how to download 30-years of albedo time-series and create its time-series? 

### ISSUE THREAD

**Issue by akankshabalha** [bopen/c3s-eqc-toolbox-template#129]
### Notebook description

Hi,
I need to download and create a annual timeseries of albedo dataset for following region during 1990-2020. With the experience from the previous notebooks, I know to do it for 1-2 years, but I don't understand how to download the dataset for 30 years, as satellite and sensor differs after every few years.  

Region:
46.91N, 50.85E, 46.81N, 50.75E

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Hi,
I don't know how to help you. The description is too vague.
Which dataset? Which sensors?

Are you referring to [this](https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/urban_heat_islands.ipynb) template?
If yes, I can cache that time period for you.
All you have to do is provide the following parameters:

- Coordinates of the overall area
- Coordinates of the zoom
- Name of the sensors and time period

**Comment by akankshabalha** [comment]
Hi Mattia,

I am not referring to the template that you mentioned above.
I have attached the notebook which I am working upon. The notebook mentions the sensor, time-period and the coordinates of the area. It is taking a lot of time to download the data (with no success yet), it would be nice if you could help in caching the data.

[Albedo_Caspian.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/14118446/Albedo_Caspian.zip)

**Comment by malmans2** [comment]
Hi there,

The CDS is experiencing issues at the moment.
I've already contacted ECMWF, they are working on it.

I'll let you know when I'm able to download and cache your data.

**Comment by akankshabalha** [comment]
Hi Mattia,

Have you been able to download and cache the data that I requested above
.

**Comment by malmans2** [comment]
No, the dataset is still under maintenance as mentioned [here](https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-albedo?tab=overview). There's nothing I can do about it.

Could you please check periodically and let me know when the dataset will be available?

**Comment by akankshabalha** [comment]
Hi Mattia,

The surface albedo dataset is available on CDS now. Could you please help me in downloading and caching the data I requested above in the .zip file.

Thanks

**Comment by malmans2** [comment]
I'm on it, my guess is that tomorrow morning they'll be ready.
I'll let you know when you can start using the cache data.

**Comment by malmans2** [comment]
Hello, everything is now cached. You need to use the following code:

```python
from c3s_eqc_automatic_quality_control import download, diagnostics

collection_id = "satellite-albedo"
chunks = {"year": 1}

common_request = {
    "format": "zip",
    "variable": "albb_bh",
    "product_version": "v2",
    "month": [f"{month:02d}" for month in range(1, 13)],
    "nominal_day": "10",
    "area": [46.91, 50.75, 46.81, 50.85],
}
requests = {
    "noaa_11": {
        "year": [str(year) for year in range(1990, 1995)],
        "horizontal_resolution": "4km",
        "sensor": "avhrr",
    },
    "noaa_14": {
        "year": [str(year) for year in range(1995, 2002)],
        "horizontal_resolution": "4km",
        "sensor": "avhrr",
    },
    "noaa_17": {
        "year": [str(year) for year in range(2002, 2006)],
        "horizontal_resolution": "4km",
        "sensor": "avhrr",
    },
    "spot": {
        "year": [str(year) for year in range(2006, 2014)],
        "horizontal_resolution": "1km",
        "sensor": "vgt",
    },
    "proba": {
        "year": [str(year) for year in range(2014, 2021)],
        "horizontal_resolution": "1km",
        "sensor": "vgt",
    },
}

maps = {}
timeseries = {}
for satellite, request in requests.items():
    print(f"{satellite=}")

    maps[satellite] = download.download_and_transform(
        collection_id,
        common_request | request | {"satellite": satellite},
        chunks=chunks,
        transform_chunks=False,
        transform_func=diagnostics.time_weighted_mean,
        drop_variables=["crs"],
    )

    timeseries[satellite] = download.download_and_transform(
        collection_id,
        common_request | request | {"satellite": satellite},
        chunks=chunks,
        transform_func=diagnostics.spatial_weighted_mean,
        drop_variables=["crs"],
    )
```
The two dictionaries contain the maps and timeseries for each satellite.
Please let me know if we can close this issue.

**Comment by akankshabalha** [comment]
Thanks Mattia, it worked. I need your help in one more thing.

Following your code, I tried to plot the time-series of albedo using the below-mentioned code, but it gives me seperate time-series plot, one for each satellite and, each time series plot contains various variables such as AL_BH_BB, AL_BH_BB_ERR etc. However, I want a one time-series plot from 1990-2020 of AL_BH_BB. Moreover, before creating time-series, the satellite data having resolution 4km needs to be regridded to 1km to obtain time-series of datasets with same resolution. Could you please help.


    # Plotting the time series data for each satellite
    for satellite, ts_data in timeseries.items():
        plt.figure(figsize=(10, 6))
    
        # Extracting time and albedo values as numpy arrays
        time_values = ts_data.time.values
    
        # Plotting each variable in the dataset
        for variable in ts_data.data_vars:
            plt.plot(time_values, ts_data[variable].values, label=f"{satellite} - {variable}")
    
        plt.title(f"Time Series of Albedo ({satellite})")
        plt.xlabel("Time")
        plt.ylabel("Albedo")
        plt.legend()
        plt.grid(True)
        plt.show()

**Comment by malmans2** [comment]
Hi,

If you want me to add an interpolation, I need to know what interpolation algorithm you want to use.
But as far as I can tell, you don't need an interpolation for timeseries. We perform spatial weighted averages, so interpolating before doing the average won't make much difference.

Maybe you meant maps? If you want to interpolate low res maps to high-res maps, just let me know what kind of interpolation you'd like to perform. I can add plots of maps as well, but I need to know what kind of plot you need to display (e.g., a single plot with a time average? one plot per satellite? ...)

In the meantime, you can find the timeseries plot you requested here:

- Template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/albedo_timeseries_and_maps.ipynb
- Notebook executed: https://gist.github.com/malmans2/bc6e49b24fdff65447b9b70fb3807077

**Comment by malmans2** [comment]
> I am unable to download lake water level data

What do you mean? I need full code and/or a traceback to help with issues.
Anyways, the data is cached on the VM:
```python
from c3s_eqc_automatic_quality_control import download

collection_id_lake = "satellite-lake-water-level"
request_lake = {
    "variable": "water_surface_height_above_reference_datum",
    "version": "version_4_0",
    "format": "zip",
    "lake": "caspian",
    "region": "southwestern_asia",
}
ds = download.download_and_transform(collection_id_lake, request_lake)
```

This dataset seems completely unrelated to this issue. If you need further assistance please open a new issue.
