### ISSUE TITLE
Can't properly run the following notebook: in_situ/02-Application_Template_Global_Timeseries_Gridded.ipynb

### ISSUE THREAD

**Issue by anolive** [bopen/c3s-eqc-toolbox-template#13]
While running the ds_mean = download.download_and_transform() command (cell #8), the following error occurs:

2023-01-18 15:29:12,898 INFO Gathering file 1 out of 2...
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
File ~/anaconda3/envs/bopen/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1900, in Connection._execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1899     if not evt_handled:
-> 1900         self.dialect.do_execute(
   1901             cursor, statement, parameters, context
   1902         )
   1904 if self._has_events or self.engine._has_events:

File ~/anaconda3/envs/bopen/lib/python3.11/site-packages/sqlalchemy/engine/default.py:736, in DefaultDialect.do_execute(self, cursor, statement, parameters, context)
    735 def do_execute(self, cursor, statement, parameters, context=None):
--> 736     cursor.execute(statement, parameters)

OperationalError: no such column: cache_entries.expiration

The above exception was the direct cause of the following exception:

OperationalError                          Traceback (most recent call last)
Cell In[15], line 1
----> 1 ds_mean = download.download_and_transform(
      2     collection_id,
      3     request,
      4     transform_func=diagnostics.spatial_weighted_mean,
      5     split_all=True,
      6 )

File ~/anaconda3/envs/bopen/lib/python3.11/site-packages/c3s_eqc_automatic_quality_control/download.py:352, in download_and_transform(collection_id, requests, chunks, split_all, transform_func, logger, **kwargs)
    350 for n, request_chunk in enumerate(request_list):
    351     logger.info(f"Gathering file {n+1} out of {len(request_list)}...")
--> 352     ds = download_and_transform_chunk(
    353         collection_id,
    354         request=request_chunk,
    355         transform_func=transform_func,
    356     )
    357     datasets.append(ds.encoding["source"])
    359 logger.info("Aggregating data...")

File ~/anaconda3/envs/bopen/lib/python3.11/site-packages/cacholote/cache.py:129, in cacheable.<locals>.wrapper(__context__, *args, **kwargs)
    127     filters.append(config.CacheEntry.expiration == expiration)
    128 with sqlalchemy.orm.Session(config.ENGINE.get(), autoflush=False) as session:
--> 129     for cache_entry in (
    130         session.query(config.CacheEntry)
    131         .filter(*filters)
    132         .order_by(config.CacheEntry.timestamp.desc())
    133         .with_for_update()
    134     ):
    135         # Attempt all valid cache entries
    136         try:
    137             return _decode_and_update(session, cache_entry, settings)

File ~/anaconda3/envs/bopen/lib/python3.11/site-packages/sqlalchemy/orm/query.py:2901, in Query.__iter__(self)
   2900 def __iter__(self):
-> 2901     result = self._iter()
   2902     try:
   2903         for row in result:

File ~/anaconda3/envs/bopen/lib/python3.11/site-packages/sqlalchemy/orm/query.py:2916, in Query._iter(self)
   2913 params = self._params
   2915 statement = self._statement_20()
-> 2916 result = self.session.execute(
   2917     statement,
   2918     params,
   2919     execution_options={"_sa_orm_load_options": self.load_options},
   2920 )
   2922 # legacy: automatically set scalars, unique
   2923 if result._attributes.get("is_single_entity", False):

File ~/anaconda3/envs/bopen/lib/python3.11/site-packages/sqlalchemy/orm/session.py:1714, in Session.execute(self, statement, params, execution_options, bind_arguments, _parent_execute_state, _add_event, **kw)
   1712 else:
   1713     conn = self._connection_for_bind(bind)
-> 1714 result = conn._execute_20(statement, params or {}, execution_options)
   1716 if compile_state_cls:
   1717     result = compile_state_cls.orm_setup_cursor_result(
   1718         self,
   1719         statement,
   (...)
   1723         result,
   1724     )

File ~/anaconda3/envs/bopen/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1705, in Connection._execute_20(self, statement, parameters, execution_options)
   1701     util.raise_(
   1702         exc.ObjectNotExecutableError(statement), replace_context=err
   1703     )
   1704 else:
-> 1705     return meth(self, args_10style, kwargs_10style, execution_options)

File ~/anaconda3/envs/bopen/lib/python3.11/site-packages/sqlalchemy/sql/elements.py:334, in ClauseElement._execute_on_connection(self, connection, multiparams, params, execution_options, _force)
    330 def _execute_on_connection(
    331     self, connection, multiparams, params, execution_options, _force=False
    332 ):
    333     if _force or self.supports_execution:
--> 334         return connection._execute_clauseelement(
    335             self, multiparams, params, execution_options
    336         )
    337     else:
    338         raise exc.ObjectNotExecutableError(self)

File ~/anaconda3/envs/bopen/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1572, in Connection._execute_clauseelement(self, elem, multiparams, params, execution_options)
   1560 compiled_cache = execution_options.get(
   1561     "compiled_cache", self.engine._compiled_cache
   1562 )
   1564 compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
   1565     dialect=dialect,
   1566     compiled_cache=compiled_cache,
   (...)
   1570     linting=self.dialect.compiler_linting | compiler.WARN_LINTING,
   1571 )
-> 1572 ret = self._execute_context(
   1573     dialect,
   1574     dialect.execution_ctx_cls._init_compiled,
   1575     compiled_sql,
   1576     distilled_params,
   1577     execution_options,
   1578     compiled_sql,
   1579     distilled_params,
   1580     elem,
   1581     extracted_params,
   1582     cache_hit=cache_hit,
   1583 )
   1584 if has_events:
   1585     self.dispatch.after_execute(
   1586         self,
   1587         elem,
   (...)
   1591         ret,
   1592     )

File ~/anaconda3/envs/bopen/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1943, in Connection._execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1940             branched.close()
   1942 except BaseException as e:
-> 1943     self._handle_dbapi_exception(
   1944         e, statement, parameters, cursor, context
   1945     )
   1947 return result

File ~/anaconda3/envs/bopen/lib/python3.11/site-packages/sqlalchemy/engine/base.py:2124, in Connection._handle_dbapi_exception(self, e, statement, parameters, cursor, context)
   2122     util.raise_(newraise, with_traceback=exc_info[2], from_=e)
   2123 elif should_wrap:
-> 2124     util.raise_(
   2125         sqlalchemy_exception, with_traceback=exc_info[2], from_=e
   2126     )
   2127 else:
   2128     util.raise_(exc_info[1], with_traceback=exc_info[2])

File ~/anaconda3/envs/bopen/lib/python3.11/site-packages/sqlalchemy/util/compat.py:211, in raise_(***failed resolving arguments***)
    208     exception.__cause__ = replace_context
    210 try:
--> 211     raise exception
    212 finally:
    213     # credit to
    214     # https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/
    215     # as the __traceback__ object creates a cycle
    216     del exception, replace_context, from_, with_traceback

File ~/anaconda3/envs/bopen/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1900, in Connection._execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1898                 break
   1899     if not evt_handled:
-> 1900         self.dialect.do_execute(
   1901             cursor, statement, parameters, context
   1902         )
   1904 if self._has_events or self.engine._has_events:
   1905     self.dispatch.after_cursor_execute(
   1906         self,
   1907         cursor,
   (...)
   1911         context.executemany,
   1912     )

File ~/anaconda3/envs/bopen/lib/python3.11/site-packages/sqlalchemy/engine/default.py:736, in DefaultDialect.do_execute(self, cursor, statement, parameters, context)
    735 def do_execute(self, cursor, statement, parameters, context=None):
--> 736     cursor.execute(statement, parameters)

OperationalError: (sqlite3.OperationalError) no such column: cache_entries.expiration
[SQL: SELECT cache_entries."key" AS cache_entries_key, cache_entries.expiration AS cache_entries_expiration, cache_entries.result AS cache_entries_result, cache_entries.timestamp AS cache_entries_timestamp, cache_entries.counter AS cache_entries_counter, cache_entries.tag AS cache_entries_tag 
FROM cache_entries 
WHERE cache_entries."key" = ? AND cache_entries.expiration > ? ORDER BY cache_entries.timestamp DESC]
[parameters: ('4f348bfb2f5df0195331b50d9d3331a2773925aa3f8ef5a4c0520bae', '2023-01-18 15:29:12.900322')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by anolive** [comment]
Hi @malmans2 ,

thank you very much for your prompt reply and detailed steps. Those worked like a charm! The notebook is working now.

**Comment by malmans2** [comment]
Nice! I'm going to close this, but feel free to re-open or open more issues in the future.

> Now I have some doubts going forward, e.g., how should we proceed regarding each of the datasets and the remaining diagnostics. But I guess updates and procedures will be discussed soon.

Yes, I think this will be addressed in our next meeting.
