### ISSUE TITLE
Unable to download and raster plot land cover data

### ISSUE THREAD

**Issue by akankshabalha** [bopen/c3s-eqc-toolbox-template#133]
### Notebook description

I need to download and create a raster plot of 'land cover' variable (out of all the variables) of this product (https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-land-cover?tab=form). I am encountering two issues: 

1) I am unable to download it. Could you please help in caching the data.

2) The dataset is available globally, however I need to create its raster plot only for a particular region i.e., -5.10, -66.80, -5.30, -66.50. I have already created jupyter notebook (attached). I only want to add the raster plots of land cover data in the notebook.

The details of the requested data is mentioned below.

    'satellite-land-cover',
        {
            'variable': 'land_cover',
            'format': 'zip',
            'year': '1992',
            'version': 'v2.0.7cds',
        },
        'download.zip')

    'satellite-land-cover',
        {
            'variable': 'all',
            'format': 'zip',
            'year': '2018',
            'version': 'v2.1.1',
        },
        'download.zip')

[Albedo_Forests_FinalHTML (1).zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/14594719/Albedo_Forests_FinalHTML.1.zip)

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Hi,

> I am unable to download it.

This is not very helpful. Why are you unable to download? What's the error/traceback? Which code did you run?
The code you copy/pasted it's not even our software but a direct request for `cdsapi`.

I was able to download and regionalise your requests with no issues.
It's cached on the VM.
```python
# Import libraries
from c3s_eqc_automatic_quality_control import download, utils

# Define parameters
area = [-5.10, -66.80, -5.30, -66.50]

# Define request
collection_id = "satellite-land-cover"
request_land_cover = {
    "variable": "land_cover",
    "format": "zip",
    "year": "1992",
    "version": "v2.0.7cds",
}
request_all = {
    "variable": "all",
    "format": "zip",
    "year": "2018",
    "version": "v2.1.1",
}

# Download and transform
kwargs = {
    "transform_func": utils.regionalise,
    "transform_func_kwargs": {
        "lat_slice": slice(area[0], area[2]),
        "lon_slice": slice(area[1], area[3]),
    },
}
ds_land_cover = download.download_and_transform(collection_id, request_land_cover, **kwargs)
ds_all = download.download_and_transform(collection_id, request_all, **kwargs)
```
