### ISSUE TITLE
Is it possible to add google earth/google map images to jupyter notebook?

### ISSUE THREAD

**Issue by akankshabalha** [bopen/c3s-eqc-toolbox-template#137]
### Notebook description

Hi Mattia,

I need to add google earth (preferably)/ google map images in my jupyter notebook (attached below) for the following region for year 1991 and 2019.

"area": [-5.10, -66.80, -5.30, -66.50]

Sorry that I am asking help from the scratch but I have no experience in how to import google earth images to jupyter, is it even possible to do so? I am clueless. Could you please help.

[Albedo_Forests_FinalHTML (1).zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/14697255/Albedo_Forests_FinalHTML.1.zip)

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Hi @akankshabalha,

I have no experience with that. My guess is that it's doable, but it's not straightforward.
We would need to install various external libraries. Also, it's very likely that you need to authenticate using your credentials, so the notebook is harder to share.

Maybe it's easier to add a static image. If you get the satellite image that you want, you can simply add it in a markdown cell (drag and drop should work). Various evaluator are already adding external figures like that.

**Comment by akankshabalha** [comment]
Hi Mattia,

Thanks for the prompt response. Okay, I will try to add static image.
