### ISSUE TITLE
Help for figure optimization in JN

### ISSUE THREAD

**Issue by paolocristofanelli** [bopen/c3s-eqc-toolbox-template#138]
### Notebook description

The JN analyse Level 3  "satellite-carbon-dioxide" "merged_obs4mips" "xco2" dataset to create global annual variability of seasonal XCO2 (Figure 1) and Global trend quantification (Figure 2).
I need help to optimise the graphic aspect of Fig. 1. WP5 leader asked to have larger maps and a smaller legend bar, but still ensuring the readability of the characters.

[Fig1_satellite-observations_carbon-dioxide-data-from-2002-to-present-derived-from-satellite -observations_TBC_q1.pdf](https://github.com/bopen/c3s-eqc-toolbox-template/files/14721765/Fig1_satellite-observations_carbon-dioxide-data-from-2002-to-present-derived-from-satellite.-observations_TBC_q1.pdf)

### Notebook link or upload

[satellite-observations_carbon-dioxide-data-from-2002-to-present-derived-from-satellite -observations_TBC_q1.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/14721768/satellite-observations_carbon-dioxide-data-from-2002-to-present-derived-from-satellite.-observations_TBC_q1.zip)

### Anything else we need to know?

WP5. JN to be used as tool for quality assessment.

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Sure, this is easy to fix. I'll send you a snipped so you can easily customize it.
Is this cached on the VM?

**Comment by paolocristofanelli** [comment]
@malmans2 thank you!
Do you mean the Figure is cached?

**Comment by malmans2** [comment]
Yes, I meant the data. I just tried and it's cached.

In `plot.projected_map` you can pass any of the keyword arguments supported by xarray plot.
How about this? Alternatively, you could use an horizontal colorbar...
```python
# Analysis of global variability of seasonal XCO2
ds_seasonal = download.download_and_transform(
    *request,
    transform_func=compute_seasonal_timeseries_nomask,
    transform_func_kwargs=transform_func_kwargs_nommask,
)
_ = plot.projected_map(
    ds_seasonal[variable],
    projection=ccrs.Robinson(),
    col="season",
    row="year",
    robust=True,
    aspect=1.5,
    cbar_kwargs={"shrink": 0.5},
)
```


![image](https://github.com/bopen/c3s-eqc-toolbox-template/assets/22245117/9b491c99-c4fa-4413-969a-60f85241ce4f)

**Comment by paolocristofanelli** [comment]
Looks fine. Maybe an horizontal color bar can further help

**Comment by malmans2** [comment]
Better?
```python
# Analysis of global variability of seasonal XCO2
ds_seasonal = download.download_and_transform(
    *request,
    transform_func=compute_seasonal_timeseries_nomask,
    transform_func_kwargs=transform_func_kwargs_nommask,
)
_ = plot.projected_map(
    ds_seasonal[variable],
    projection=ccrs.Robinson(),
    col="season",
    row="year",
    robust=True,
    cbar_kwargs={"orientation": "horizontal", "pad": 0.05},
)
```
![image](https://github.com/bopen/c3s-eqc-toolbox-template/assets/22245117/f18365b4-ff13-467d-a3e4-c6874e29899f)

**Comment by paolocristofanelli** [comment]
@malmans2 much better! Thank you!
