### ISSUE TITLE
Wp5: water level extremes

### ISSUE THREAD

**Issue by Cri-dei** [bopen/c3s-eqc-toolbox-template#139]
### Notebook description

Identification of extreme events of water level time series for the Victoria lake. 

### Notebook link or upload

[Lake water level_ Extremes_rev.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/14743435/Lake.water.level_.Extremes_rev.zip)

### Anything else we need to know?

I am running again the notebook to do the reviews I was asked to do. Now I have an error running the notebook. I am not able to download the variable anymore.
Moreover, I am asked to add some plots and picture from another document that I used as literature review. There is a way to add a picture in the notebook?

Thank you so much!

![image](https://github.com/bopen/c3s-eqc-toolbox-template/assets/56677048/c0c826f6-2e66-46b5-a71b-3513f71afcb9)

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Hi @Cri-dei,

> I am running again the notebook to do the reviews I was asked to do. Now I have an error running the notebook. I am not able to download the variable anymore.

Your cached data has expired on the VM as you haven't use it for a long time.
If you look at the [dataset webpage](https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-lake-water-level?tab=form) on the CDS, there's this warning:

> WARNING [2023-10-06]: The addition of the latest version require changes to the download form. Please note CDS API requests need to be modified due to these changes.

If you send me the new request I can cache it for you. Also please send me the name of the template corresponding to this dataset so I can update it.

> Moreover, I am asked to add some plots and picture from another document that I used as literature review. There is a way to add a picture in the notebook?

Yes, you can add external figures in markdown cells. I believe you can just drag and drop the figure you want to add. See https://github.com/bopen/c3s-eqc-toolbox-template/issues/137

**Comment by Cri-dei** [comment]
Hi Mattia,
Thanks for your prompt answer!
How I can send you the CDS API request?

The notebook I am referring to is: in wp5 : lake_water_level_extremes
[lake_water_level_extremes.ipynb](https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/lake_water_level_extremes.ipynb) 

I am modifying it a bit so I will send you the final version when I am done.

**Comment by Cri-dei** [comment]
`import cdsapi

c = cdsapi.Client()

c.retrieve(
    'satellite-lake-water-level',
    {
        'variable': 'all',
        'region': 'southern_africa',
        'lake': 'victoria',
        'version': 'version_4_0',
        'format': 'zip',
    },
    'download.zip')`

I have to do it also for the other notebook and variables?

**Comment by malmans2** [comment]
Looks [like](https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/lake_water_level_extremes.ipynb) is the only notebook using that dataset, so no need to do it for other notebooks (unless ECMWF changed the form of other datasets).

I'll cache the new request in a minute and will let you know when it's ready

**Comment by malmans2** [comment]
ohh that was quick. It's cached!
Here is the latest template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/lake_water_level_extremes.ipynb

**Comment by Cri-dei** [comment]
It is a small request indeed, just a data series! 
Thank you, it is working now!!
