### ISSUE TITLE
Replicate a JN for other variables in the datafile Level3 XCO2 "merged_obs4mips" (WP5)

### ISSUE THREAD

**Issue by paolocristofanelli** [bopen/c3s-eqc-toolbox-template#141]
### Notebook description

Does any easy way exist to replicate for other variables in the datafile ("xco2_nobs", "xco2_stderr"), the JN at https://github.com/bopen/c3s-eqc-toolbox-template/issues/138#issue-2202270678 ?

When tried I got: "Exception: the request you have submitted is not valid. Value 'xco2_nobs' not valid for parameter 'variable', valid values are: co2, xco2."

### Environment

<details>

</details>

**Comment by malmans2** [comment]
What's the name of the template?

**Comment by paolocristofanelli** [comment]
[satellite-observations_carbon-dioxide-data-from-2002-to-present-derived-from-satellite -observations_TBC_q1.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/14721768/satellite-observations_carbon-dioxide-data-from-2002-to-present-derived-from-satellite.-observations_TBC_q1.zip)

**Comment by malmans2** [comment]
I meant the template in this repo, which is what we maintain.
Is it this one? https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/xch4_xco2_satellite_lev3.ipynb

**Comment by paolocristofanelli** [comment]
Hi @malmans2! I updated the JN but I do not have permission to update to  https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/

You can find it, here in attachment.

[satellite-observations_carbon-dioxide-data-from-2002-to-present-derived-from-satellite-observations_TBC_q1.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/14757151/satellite-observations_carbon-dioxide-data-from-2002-to-present-derived-from-satellite-observations_TBC_q1.zip)

**Comment by malmans2** [comment]
Hi @paolocristofanelli,

You can not update templates. B-Open maintains the template, and you use it to build your own notebook.
The templates are minimal, no comments nor advanced settings to tune plots.

Did you built your notebook starting from this template? https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/xch4_xco2_satellite_lev3.ipynb

If yes, I'm editing it so you can select any variable downloaded. I'm also adding the region/time selection.

**Comment by malmans2** [comment]
@paolocristofanelli , the new template is ready: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/xch4_xco2_satellite_lev3.ipynb

You can now choose variables such as `xco2_nobs`.
Please let me know if it works OK.

**Comment by malmans2** [comment]
Hi @paolocristofanelli,

Can we close this issue?
