### ISSUE TITLE
Glacier mass balance - maps (WP5)

### ISSUE THREAD

**Issue by yoniv1** [bopen/c3s-eqc-toolbox-template#149]
### Notebook description

Gridded glacier mass change data on the global scale since 1976.

### Notebook link or upload

https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/glacier_mass_balance_maps.ipynb

### Anything else we need to know?

I would like to change the calculation of the glacier mass change uncertainty in the notebook. Right now, the sum of the uncertainty values over the time dimension is just taken for every pixel in the grid, i.e. err_pixel(i,j) = err_1976(i,j) + err_1977(i,j) + ... + err_2021(i,j). I would like to apply the error propagation formula to each pixel through the time dimension: err_pixel(i,j) = sqrt((err_1976(i,j))^2 + (err_1977(i,j))^2 + ... + (err_2021(i,j))^2).

### Environment

<details>

</details>

**Comment by yoniv1** [comment]
> Is the variable `Glacier`?

yes!

**Comment by malmans2** [comment]
Actually 1 sec, I need to fix a bug

**Comment by malmans2** [comment]
I think it was fine. Anyways, please use the latest version.

- Here is the template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/glacier_mass_balance_maps.ipynb
- Here is the notebook executed: https://gist.github.com/malmans2/bdf421d7f26ae98881842afad07828e1

Let me know!

**Comment by yoniv1** [comment]
Thanks Mattia, looks good! The topic can be closed for now. Might be reopened later, however, depending on if I have struggles later on.

**Comment by yoniv1** [comment]
```
Hello Mattia,

In the function you have added in this notebook (see below), is it possible to: 
- add 2D matrices of the p-values of the slopes of the linear and quadratic trends for the glacier mass change data to this dataset (statistical significance)?
- to also retrieve a time series of global mass change data (the sum of all 2D pixels for each year)? i.e. over the time dimension and not over the space dimension.
Thanks!

def compute_sum_uncertainty_slope_and_acceleration(ds):

```    with xr.set_options(keep_attrs=True):
        cumsum = ds["Glacier"].cumsum("time").drop_vars("time")
        ds["Uncertainty"] = (ds["Uncertainty"] ** 2).sum("time") ** (1 / 2)

    # Sum
    ds = ds.sum("time", keep_attrs=True)
    for da in ds.data_vars.values():
        da.attrs["long_name"] = f"Sum of {da.attrs['long_name']}"

    # Linear
    ds["Slope"] = cumsum.polyfit("time", 1)["polyfit_coefficients"].sel(degree=1)
    ds["Slope"].attrs = {
        "long_name": f"Trend of {da.attrs['long_name']}",
        "units": f"{da.attrs['units']} yr$^{-1}$",
    }

    # Quadratic
    ds["Acceleration"] = 2 * cumsum.polyfit("time", 2)["polyfit_coefficients"].sel(
        degree=2
    )
    ds["Acceleration"].attrs = {
        "long_name": f"Quadratic Trend of {da.attrs['long_name']}",
        "units": f"{da.attrs['units']} yr$^{-2}$",
    }

    return ds

**Comment by malmans2** [comment]
Hi @yoniv1,

> add 2D matrices of the p-values of the slopes of the linear and quadratic trends for the glacier mass change data to this dataset (statistical significance)?

Done. `ds` now has 2 additional variables. Pvalue1 and Pvalue2. Ideally, you'd have to share an algorithm or snippets. As you didn't do it, please make sure that p-values are computed correctly.

> to also retrieve a time series of global mass change data (the sum of all 2D pixels for each year)? i.e. over the time dimension and not over the space dimension.

Done. See the Dataset named `ds_timeseries`

I added quick and dirty plots. You might want to customize the `column_kwargs` settings, and revise the timeseries plots. If you want me to include changes in the plot in the template, please let me know the settings you want to use.

Here is the template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/glacier_mass_balance_maps.ipynb
Here is the notebook executed: https://gist.github.com/malmans2/93a4294c4e3d2e6c8db91ef5f3552712

As always, please let me know if everything works OK.

**Comment by yoniv1** [comment]
Thanks Mattia, looks good!
