### ISSUE TITLE
Climatology and bias near surface air temperature WP4 

### ISSUE THREAD

**Issue by paololanteri** [bopen/c3s-eqc-toolbox-template#15]
Attached here the first version of climatology and bias plots of near surface air temperature for climate projections (clima_t2m.ipynb) with additional functions needed (functions.py). I could run itentirely from the VM.

There is still a problem with the use of xesmf (cell [12]) that seems to be not compatible with the latest version of xarray. So, for the moment I'm using the most basic xarray interpolation function (cell [13]).

[scripts.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/10608344/scripts.zip)

**Comment by malmans2** [comment]
Hi @paololanteri,

I'm adding a couple of diagnostics to compute (and cache) regridders, and compute seasonal averages.
I think `xesmf` is working ok for me.

Could you please check whether the code below is working as expected?
At the moment the code is just regridding, computing seasonal averages, then making a very basic plot.

I'm working on this [branch](https://github.com/bopen/c3s-eqc-automatic-quality-control/pull/15). Before testing, you need to download the branch and install the proper environment.
```
git clone https://github.com/bopen/c3s-eqc-automatic-quality-control.git -b regridder
cd c3s-eqc-automatic-quality-control
conda create -n DEVELOP -c conda-forge python=3.10
conda activate DEVELOP
make conda-env-update
pip install -e .
```

Here is the code:
```python
# %%
import warnings

from c3s_eqc_automatic_quality_control import diagnostics, download

warnings.filterwarnings("ignore")

# %%
year_start = 1985
year_stop = 2014

common_request = {
    "year": [str(year) for year in range(year_start, year_stop + 1)],
    "month": [f"{month:02d}" for month in range(1, 12 + 1)],
}

# %%
request_era = {
    "product_type": "monthly_averaged_reanalysis",
    "format": "netcdf",
    "time": "00:00",
    "variable": "2m_temperature",
}

request_sim = {
    "format": "zip",
    "temporal_resolution": "monthly",
    "experiment": "historical",
    "variable": "near_surface_air_temperature",
    "model": "cmcc_cm2_sr5",
}

# %%
ds_era = download.download_and_transform(
    "reanalysis-era5-single-levels-monthly-means",
    {**common_request, **request_era},
    chunks={"year": 1},
)

ds_sim = download.download_and_transform(
    "projections-cmip6",
    {**common_request, **request_sim},
    transform_func=diagnostics.regrid,
    transform_func_kwargs={
        "grid_out": ds_era.drop_dims("time"),
        "method": "bilinear",
        "periodic": True,
    },
    chunks={"year": 1},
)

# %%
ds_era_seasonal = diagnostics.time_weighted_seasonal_mean(ds_era)
ds_sim_seasonal = diagnostics.time_weighted_seasonal_mean(ds_sim)
seasonal_bias = ds_sim_seasonal["tas"] - ds_era_seasonal["t2m"]
seasonal_bias.plot(x="longitude", y="latitude", col="season", col_wrap=2, robust=True)
```

**Comment by malmans2** [comment]
@paololanteri I made some progress and I've added a notebook to the templates.

I've added the following functionalities:
1. `diagnostics.regrid`: cached regridding using xesmf
2. `diagnostics.seasonal_weighted_mean`: compute seasonal weighted mean
3. `plot.global_map`: make global maps using xarray + matplotlib + cartopy

The notebook is here: https://github.com/bopen/c3s-eqc-toolbox-template/blob/clima-t2m/notebooks/wp4/clima_t2m.ipynb

Both the notebook and the python code are not in the main branch yet, so you have to install the environment as mentioned in my previous comment:
```
git clone https://github.com/bopen/c3s-eqc-automatic-quality-control.git -b regridder
cd c3s-eqc-automatic-quality-control
conda create -n DEVELOP -c conda-forge python=3.10
conda activate DEVELOP
make conda-env-update
pip install -e .
```

Let me know if everything works OK and the notebook is consistent with your code.

**Comment by paololanteri** [comment]
Hi @malmans2,
running the first cell of the notebook I get the following error:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/miniconda3/envs/DEVELOP/lib/python3.10/site-packages/esmpy/interface/loadESMF.py:26
     25 try:
---> 26     esmfmk = os.environ["ESMFMKFILE"]
     27 except:

File ~/miniconda3/envs/DEVELOP/lib/python3.10/os.py:680, in _Environ.__getitem__(self, key)
    678 except KeyError:
    679     # raise KeyError with the original key value
--> 680     raise KeyError(key) from None
    681 return self.decodevalue(value)

KeyError: 'ESMFMKFILE'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
File ~/miniconda3/envs/DEVELOP/lib/python3.10/site-packages/xesmf/backend.py:22
     21 try:
---> 22     import esmpy as ESMF
     23 except ImportError:

File ~/miniconda3/envs/DEVELOP/lib/python3.10/site-packages/esmpy/__init__.py:112
    110 #### IMPORT LIBRARIES #########################################################
--> 112 from esmpy.api.esmpymanager import *
    113 from esmpy.api.grid import *

File ~/miniconda3/envs/DEVELOP/lib/python3.10/site-packages/esmpy/api/esmpymanager.py:9
      7 #### IMPORT LIBRARIES #########################################################
----> 9 from esmpy.interface.cbindings import *
     11 from esmpy.api.constants import *

File ~/miniconda3/envs/DEVELOP/lib/python3.10/site-packages/esmpy/interface/cbindings.py:13
     12 from esmpy.util.decorators import *
---> 13 from esmpy.interface.loadESMF import _ESMF
     16 def copy_struct(src):

File ~/miniconda3/envs/DEVELOP/lib/python3.10/site-packages/esmpy/interface/loadESMF.py:28
     27 except:
---> 28     raise ImportError('The ESMFMKFILE environment variable is not available.')
     30 #### INVESTIGATE esmf.mk ######################################################
     31 
     32 # TODO: look for various dependecies in the ESMF build log
   (...)
     37 #       use this information to set variables that can be checked at beginning
     38 #       of the routines that require an ESMF build with these dependencies

ImportError: The ESMFMKFILE environment variable is not available.

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 5
      3 import matplotlib.pyplot as plt
      4 import xarray as xr
----> 5 from c3s_eqc_automatic_quality_control import diagnostics, download, plot
      7 plt.style.use("seaborn-v0_8-talk")
      9 warnings.filterwarnings("ignore")

File ~/c3s-eqc-automatic-quality-control/c3s_eqc_automatic_quality_control/diagnostics.py:25
     23 import numpy as np
     24 import xarray as xr
---> 25 import xesmf as xe
     28 def _spatial_weights(
     29     obj: xr.Dataset | xr.DataArray, lon: str = "longitude", lat: str = "latitude"
     30 ) -> xr.DataArray:
     31     cos = np.cos(np.deg2rad(obj[lat]))

File ~/miniconda3/envs/DEVELOP/lib/python3.10/site-packages/xesmf/__init__.py:4
      1 # flake8: noqa
      3 from . import data, util
----> 4 from .frontend import Regridder, SpatialAverager
      6 try:
      7     from ._version import __version__

File ~/miniconda3/envs/DEVELOP/lib/python3.10/site-packages/xesmf/frontend.py:12
      9 import xarray as xr
     10 from xarray import DataArray, Dataset
---> 12 from .backend import Grid, LocStream, Mesh, add_corner, esmf_regrid_build, esmf_regrid_finalize
     13 from .smm import (
     14     _combine_weight_multipoly,
     15     _parse_coords_and_values,
   (...)
     19     read_weights,
     20 )
     21 from .util import LAT_CF_ATTRS, LON_CF_ATTRS, split_polygons_and_holes

File ~/miniconda3/envs/DEVELOP/lib/python3.10/site-packages/xesmf/backend.py:24
     22     import esmpy as ESMF
     23 except ImportError:
---> 24     import ESMF
     25 import numpy as np
     26 import numpy.lib.recfunctions as nprec

ModuleNotFoundError: No module named 'ESMF'
```

**Comment by malmans2** [comment]
Looks like the env variable `$ESMFMKFILE` was not set correctly.
Try this:
1. Stop the jupyter kernel and close jupyter
2. Open a new terminal
3. Activate the environment (`conda activate DEVELOP`)
4. Open jupyter, restart the kernel, and try to run again

**Comment by paololanteri** [comment]
Perfect, thank you, it works also for me now!

I would only argue that we would like to plot the model climatology (first plot) on its **native** grid, to make evident the native horizontal resolution of the model.
Instead, for what concern the bias map we are still discussing between us what should be the right interpolation grid (this depend also on the use-case, that is not finalized yet)...
We would like also to mantain the **annual** average, not only the seasonal ones, is it possible?

Can I also ask you why I'm not able to download CMIP6 without transforming, with the following code lines?
```
ds_sim = download.download_and_transform(
    *request_sim,
    chunks={"year": 1},
)
```

Thank you!

**Comment by malmans2** [comment]
OK, makes sense. I'll change a bit the notebook so it will plot the native grid as well.

The issue when no transformation is applied is something I have to investigate (I should have some time this week). It comes from the bounds, but I'm not exactly sure what's causing it (looks like they have conflicting type or something like that). This is why I used a function that drops the bounds in the templates.
 
For the annual weighted average, I think I'm going to add a separate diagnostic.

I'll let you know when the notebook is ready for another round of review.

**Comment by paololanteri** [comment]
Ok, perfect.
you can find a code for the annual average in the function time_mean() inside the file functions.py I sent you above.

**Comment by malmans2** [comment]
Hi @paololanteri ,
The issue with bounds should be fixed now, and the notebook is now plotting the original data rather than interpolated data.

If you don't want to re-download and install from scratch, this should work:

Update environment:
```
conda activate DEVELOP
cd c3s-eqc-automatic-quality-control
git pull
make conda-env-update
pip install -e .
```

Update notebook:
```
cd c3s-eqc-toolbox-template
git pull
```

If something does not work properly, you might have to clear the cache (or you might want to do it anyways, just to make sure you are using data computed with the latest code).
To clear the cache, just delete the directory printed by the code below:
```
conda activate DEVELOP
python -c "import cacholote, os; print(os.path.dirname(cacholote.utils.get_cache_files_fs_dirname()[-1]))"
```

**Comment by malmans2** [comment]
Hi @paololanteri,
I've implemented `diagnostics.annual_weighted_mean` as well.

Could you please try the [latest version of the notebook](https://github.com/bopen/c3s-eqc-toolbox-template/blob/clima-t2m/notebooks/wp4/clima_t2m.ipynb)?
As this is a template, I've simplified it a bit to showcase everything using fewer code/cells.

Let me know if everything is working as expected, and if all diagnostics you need are now available.

**Comment by paololanteri** [comment]
Hi Mattia,
I was trying the last one, but the cache was somehow cleaned, and my downloads fail. 
So, right now I am not able to do it.
I hope that ECMWF technical team will solve the problem of download as soon as possible (I have raised up the issue on ECMWF jira today), link: https://jira.ecmwf.int/servicedesk/customer/portal/8/CDSAPP-259

**Comment by malmans2** [comment]
Got it. If you are running locally, probably the cache has been cleared by your tmp policy. If you are on the VM, it's possible that the cache has not been cleared, but invalidated because you updated the cache package. In that case, you can clear the cache (see commands in my previous comments) to free some space. 

I don't have access to the ticket you opened. I've developed and tested the notebook this morning and it cdsapi was working ok on my local machine.

**Comment by malmans2** [comment]
Actually, I just found out that the CDS is currently having technical difficulties. See: https://cds.climate.copernicus.eu/#!/home

> The CDS is currently facing technical difficulties which we are working to resolve as quickly as possible. Apologies for any inconvenience caused.

**Comment by paololanteri** [comment]
Ok I dind't consider the possibility to work on the toolbox on my local machine, I was working only on the VM. It is for sure a good idea, I will try.

**Comment by malmans2** [comment]
Hi @paololanteri ,
I've merged the development branches. You can now access the notebook as usual (i.e., follow the instructions in the README of this repo, without having to download and install explicitly `c3s-eqc-automatic-quality-control`).

Feel free to re-open this issue if you'd like to make some changes or if you find any issue with the template.
