### ISSUE TITLE
User Case Upper Tropospheric Humidity

### ISSUE THREAD

**Issue by gmandorl** [bopen/c3s-eqc-toolbox-template#150]
### Notebook description

The notebook contains a Use Case of the Upper Tropospheric Humidity dataset. The code works and it produces the right result.

Could you check if the code is properly written? I did not use any build in for visualizing the results. Should I use different tools?

### Notebook link or upload

[UTH_JN_UseCase1.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/15065529/UTH_JN_UseCase1.zip)

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Hi @gmandorl,

I started reviewing this. What kind of parameters do you want to allow?
For example, you parametrize `months`, but you hardcoded `days`. 31 days work OK in January, but might break other months.

Does it make sense to parametrize a period? For example, start=`2007-01` and stop=`2007-01`. Or do you expect users to request a subset of months for different years?

**Comment by gmandorl** [comment]
Hi @malmans2,

You are right, I hardcoded `days` because I don't expect users to request a subset of months for different years. 31 days work also for different months but it's not great to see.

I think that `start`=2007-01 and `stop`=2007-01 are fine, or even one entire year is ok.

I would like to parametrize just the period and the region.

**Comment by malmans2** [comment]
Hi @gmandorl,

The template for this notebook is ready.

- Here is the template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/uth_atmospheric_circulation.ipynb
- Here is the notebook executed: https://gist.github.com/malmans2/069120c85a4bdb30f45cb70e90aec832

Please let me know if everything looks ok.

**Comment by gmandorl** [comment]
Hi @malmans2 

Thank you very much.

I have two questions:

1) Why the new download.download_and_transform() does not print anything? In the original notebook the download.download_and_transform() used to print a pink block like this

2024-04-22 11:31:43,519 INFO Welcome to the CDS
2024-04-22 11:31:43,520 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-pressure-levels
2024-04-22 11:31:43,583 INFO Request is queued
2024-04-22 11:31:44,589 INFO Request is running
2024-04-22 11:31:56,801 INFO Request is completed


2) You changed the plotting from pyplot to pandas. Is using pandas is better? Why?

**Comment by malmans2** [comment]
1. The whole point of `download.download_and_transform()` is caching data. Therefore, it only downloads the very first time you run it (the prints are from `cdsapi` used under the hood)
2. It's not better or worst. IMO it's clearer what's happening because we replaced the few lines of code that you wrote with 2 simple and self-describing functions, which are `groupby` and `boxplot`

This is just a template though, feel free to use your favourite approach in the notebook you'll submit. You are dealing with small data, so performance is not really an issue for this notebook.

Can I close this issue?

**Comment by gmandorl** [comment]
Thank you. Yes, you can close this issue.
