### ISSUE TITLE
Monitor climate change over Europe with land reanalysis data

### ISSUE THREAD

**Issue by Cri-dei** [bopen/c3s-eqc-toolbox-template#155]
### Notebook description

Review of Era5-Land notebook, trend assessment and in-situ data comparison

### Notebook link or upload

[ERA-5Land_Temperature_rev3_July.zip](https://github.com/user-attachments/files/16051412/ERA-5Land_Temperature_rev3_July.zip)

### Anything else we need to know?

Hi, I updated the code including the data comparison. Can you please look at it if can be fine? I will then ask the link from the ecmwf github. Thanks!

### Environment

<details>

</details>

**Comment by Cri-dei** [comment]
[ERA-5Land_Temperature_rev3_July(2).zip](https://github.com/user-attachments/files/16051486/ERA-5Land_Temperature_rev3_July.2.zip)

Please check this version, it is the updated one!

**Comment by malmans2** [comment]
Hi @Cri-dei,

I glanced through the code and it looks OK and in line with the template I made for you a while ago.
Do you have something specific you'd like me to check?

Otherwise, feel free to request a permalink.

**Comment by malmans2** [comment]
Actually, how did you get 'Spain_shape.shp'?
It would be better to include the download step in your NB, so it is reproducible.

I can implement that if you share the url of the shapefile.

**Comment by Cri-dei** [comment]
Here the link: https://www.eea.europa.eu/data-and-maps/data/eea-reference-grids-2/gis-files/spain-shapefile.
Respect to the previous notebook there is in addition the part of cutting the map with the shapefile and last paragraph with the comparison with in situ and bias.
If you can just check that new part would be great.
(I just submit the request for the permalink, but i can quickly update it if you suggest something to be modified).

**Comment by malmans2** [comment]
Should all the plots/analysis be restricted to Spain only?
It looks like you are using the original da for some analysis

**Comment by malmans2** [comment]
Also, what's the URL to download this file? `observed-annual-average-mean-surface-air-temperature-of-spain-for-1997-2022.csv`

**Comment by Cri-dei** [comment]
Should be just with Spain. If I am using the original da is not correct, I should used the clipped one since the original data are just for Spain. I download the in situ data from here: https://climateknowledgeportal.worldbank.org/country/spain/climate-data-historical. You can select and download from the plot section .

**Comment by malmans2** [comment]
Did you process it? I see 1991-2020, you have 1997-2022

**Comment by Cri-dei** [comment]
I just selected manually the data from 1997-2022 in the csv before importing. I could have done it also with the code, was just faster :D

**Comment by malmans2** [comment]
OK, can you please tell me exactly which CSV I should download. Each plot has a download CSV button, so I'm not sure which one I'm supposed to use.

**Comment by Cri-dei** [comment]
The data can be downloaded from this plot:
![image](https://github.com/bopen/c3s-eqc-toolbox-template/assets/56677048/330d7987-5c8a-4f88-8503-6d1875818d0e)
The selection is done in this way (average for the entire period): 
![image](https://github.com/bopen/c3s-eqc-toolbox-template/assets/56677048/eb5b328c-9e41-4c00-84f5-da899c8553ae)

**Comment by malmans2** [comment]
Hi @Cri-dei,

I made a new template for this notebook: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/era5_land_temperature_spain.ipynb

Please try it out and let me know how it goes.

You don't need to download the shapefile anymore, but you do need to download the entire observed climatology (I could not find an easy way to download it programmatically). When you'll request a permalink, please add a note uploading the csv file as done here: https://github.com/ecmwf-projects/c3s2-eqc-quality-assessment/issues/21#issue-2199830430

**Comment by Cri-dei** [comment]
I did it following the instructions. Should be all okay! I think we can close it! Thanks for the support.
