### ISSUE TITLE
Land-sea mask

### ISSUE THREAD

**Issue by gmandorl** [bopen/c3s-eqc-toolbox-template#159]
### Describe the solution you'd like

In this notebook, I plot the cloud top pressure distribution in the tropics. However, I would like to do this separately for land and ocean, meaning I need a land-sea mask that matches the latitude-longitude grid of my dataset.

How can I obtain a land-sea mask? One option might be to separate land and ocean using a dataset that covers only the ocean, such as "Sea surface temperature daily data from 1979 to present derived from satellite observations", but I don't think that's the most ideal approach.

[cloud_top_pressure.zip](https://github.com/user-attachments/files/17129138/cloud_top_pressure.zip)

**Comment by malmans2** [comment]
Hi @gmandorl,

B-Open only provides technical support for the software component. I am not familiar with this data product, so I do not know if a land/sea mask is available for it.

If a land/sea mask is not available, you could use this snippet to obtain one:
```python
import regionmask

land_110 = regionmask.defined_regions.natural_earth_v5_0_0.land_110
land_mask = land_110.mask_3D(ds_clara).squeeze("region", drop=True)
land_mask.plot()
```

**Comment by gmandorl** [comment]
Hi @malmans2,

Thank you very much. I think that will be sufficient.

I am currently having an issue with the VM. As soon as it’s resolved, I will test the code, and if everything works properly, I’ll close the issue.

**Comment by malmans2** [comment]
> I am currently having an issue with the VM

What kind of issue?

**Comment by gmandorl** [comment]
When I execute any download request, I have a "Exception: Not Found" error.

This is the error that I get when I run the notebook I shared in this issue:

`0%|          | 0[/1](http://localhost:5678/1) [00:00<?, ?it[/s](http://localhost:5678/s)]2024-09-27 08:55:52,142 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/satellite-cloud-properties
  0%|          | 0/1 [00:00<?, ?it[/s](http://localhost:5678/s)]

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
File [/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/cdsapi/api.py:459](http://localhost:5678/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/cdsapi/api.py#line=458), in Client._api(self, url, request, method)
    458 try:
--> 459     result.raise_for_status()
    460     reply = result.json()

File [/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/requests/models.py:1024](http://localhost:5678/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/requests/models.py#line=1023), in Response.raise_for_status(self)
   1023 if http_error_msg:
-> 1024     raise HTTPError(http_error_msg, response=self)

HTTPError: 404 Client Error: Not Found for url: https://cds.climate.copernicus.eu/api/v2/resources/satellite-cloud-properties

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
Cell In[6], line 20
      1 collection_id = 'satellite-cloud-properties'
      5 request_clara =  {
      6     'product_family': 'clara_a3',
      7     'origin': 'eumetsat',
   (...)
     14     'area': [30, -180, -30, 180],
     15     }
---> 20 ds_clara = download.download_and_transform(
     21     collection_id,
     22     request_clara,
     23 )

File /data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/c3s_eqc_automatic_quality_control/download.py:623, in download_and_transform(collection_id, requests, chunks, split_all, transform_func, transform_func_kwargs, transform_chunks, n_jobs, invalidate_cache, cached_open_mfdataset_kwargs, quiet, **open_mfdataset_kwargs)
    619         cacholote.delete(
    620             func.func, *func.args, request_list=request_list, **func.keywords
    621         )
    622     with _set_env(tqdm_disable=quiet):
--> 623         ds = func(request_list=request_list)
    625 ds.attrs.pop("coordinates", None)  # Previously added to guarantee roundtrip
    626 return ds

File [/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/c3s_eqc_automatic_quality_control/download.py:436](http://localhost:5678/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/c3s_eqc_automatic_quality_control/download.py#line=435), in _download_and_transform_requests(collection_id, request_list, transform_func, transform_func_kwargs, **open_mfdataset_kwargs)
    429 def _download_and_transform_requests(
    430     collection_id: str,
    431     request_list: list[dict[str, Any]],
   (...)
    434     **open_mfdataset_kwargs: Any,
    435 ) -> xr.Dataset:
--> 436     sources = get_sources(collection_id, request_list)
    437     preprocess = functools.partial(
    438         _preprocess,
    439         collection_id=collection_id,
    440         preprocess=open_mfdataset_kwargs.pop("preprocess", None),
    441     )
    443     grib_ext = (".grib", ".grb", ".grb1", ".grb2")

File [/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/c3s_eqc_automatic_quality_control/download.py:349](http://localhost:5678/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/c3s_eqc_automatic_quality_control/download.py#line=348), in get_sources(collection_id, request_list)
    347 disable = os.getenv("TQDM_DISABLE", "False") == "True"
    348 for request in tqdm.tqdm(request_list, disable=disable):
--> 349     sources.update(retrieve(collection_id, request))
    350 return list(sources)

File [/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/c3s_eqc_automatic_quality_control/download.py:339](http://localhost:5678/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/c3s_eqc_automatic_quality_control/download.py#line=338), in retrieve(collection_id, request)
    334 def retrieve(collection_id: str, request: dict[str, Any]) -> list[str]:
    335     with cacholote.config.set(
    336         return_cache_entry=False,
    337         io_delete_original=True,
    338     ):
--> 339         return [file.path for file in _cached_retrieve(collection_id, request)]

File [/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/cacholote/cache.py:102](http://localhost:5678/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/cacholote/cache.py#line=101), in cacheable.<locals>.wrapper(*args, **kwargs)
     99                 warnings.warn(str(ex), UserWarning)
    100                 clean._delete_cache_entries(session, cache_entry)
--> 102 result = func(*args, **kwargs)
    103 cache_entry = database.CacheEntry(
    104     key=hexdigest,
    105     expiration=settings.expiration,
    106     tag=settings.tag,
    107 )
    108 try:

File [/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/c3s_eqc_automatic_quality_control/download.py:324](http://localhost:5678/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/c3s_eqc_automatic_quality_control/download.py#line=323), in _cached_retrieve(collection_id, request)
    322 if NOCACHE:
    323     request = request | {"nocache": datetime.datetime.now().isoformat()}
--> 324 ds = earthkit.data.from_source("cds", collection_id, request, prompt=False)
    325 if isinstance(ds, ShapeFileReader) and hasattr(ds._parent, "_path_and_parts"):
    326     # Do not unzip vector data
    327     sources = [ds._parent._path_and_parts]

File [/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/earthkit/data/sources/__init__.py:150](http://localhost:5678/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/earthkit/data/sources/__init__.py#line=149), in from_source(name, lazily, *args, **kwargs)
    147     return from_source_lazily(name, *args, **kwargs)
    149 prev = None
--> 150 src = get_source(name, *args, **kwargs)
    151 while src is not prev:
    152     prev = src

File [/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/earthkit/data/sources/__init__.py:131](http://localhost:5678/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/earthkit/data/sources/__init__.py#line=130), in SourceMaker.__call__(self, name, *args, **kwargs)
    128     klass = find_plugin(os.path.dirname(__file__), name, loader)
    129     self.SOURCES[name] = klass
--> 131 source = klass(*args, **kwargs)
    133 if getattr(source, "name", None) is None:
    134     source.name = name

File [/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/earthkit/data/core/__init__.py:22](http://localhost:5678/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/earthkit/data/core/__init__.py#line=21), in MetaBase.__call__(cls, *args, **kwargs)
     20 obj = cls.__new__(cls, *args, **kwargs)
     21 args, kwargs = cls.patch(obj, *args, **kwargs)
---> 22 obj.__init__(*args, **kwargs)
     23 return obj

File [/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/earthkit/data/sources/cds.py:126](http://localhost:5678/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/earthkit/data/sources/cds.py#line=125), in CdsRetriever.__init__(self, dataset, prompt, *args, **kwargs)
    123 nthreads = min(self.settings("number-of-download-threads"), len(self.requests))
    125 if nthreads < 2:
--> 126     self.path = [self._retrieve(dataset, r) for r in self.requests]
    127 else:
    128     with SoftThreadPool(nthreads=nthreads) as pool:

File [/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/earthkit/data/sources/cds.py:126](http://localhost:5678/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/earthkit/data/sources/cds.py#line=125), in <listcomp>(.0)
    123 nthreads = min(self.settings("number-of-download-threads"), len(self.requests))
    125 if nthreads < 2:
--> 126     self.path = [self._retrieve(dataset, r) for r in self.requests]
    127 else:
    128     with SoftThreadPool(nthreads=nthreads) as pool:

File [/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/earthkit/data/sources/cds.py:140](http://localhost:5678/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/earthkit/data/sources/cds.py#line=139), in CdsRetriever._retrieve(self, dataset, request)
    137     self.source_filename = cds_result.location.split("[/](http://localhost:5678/)")[-1]
    138     cds_result.download(target=target)
--> 140 return_object = self.cache_file(
    141     retrieve,
    142     (dataset, request),
    143     extension=EXTENSIONS.get(request.get("format"), ".cache"),
    144 )
    145 return return_object

File [/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/earthkit/data/sources/__init__.py:68](http://localhost:5678/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/earthkit/data/sources/__init__.py#line=67), in Source.cache_file(self, create, args, **kwargs)
     65 if owner is None:
     66     owner = re.sub(r"(?!^)([A-Z]+)", r"-\1", self.__class__.__name__).lower()
---> 68 return cache_file(owner, create, args, **kwargs)

File [/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/earthkit/data/core/caching.py:1053](http://localhost:5678/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/earthkit/data/core/caching.py#line=1052), in cache_file(owner, create, args, hash_extra, extension, force, replace)
   1051 with FileLock(lock):
   1052     if not os.path.exists(path):  # Check again, another thread[/process](http://localhost:5678/process) may have created the file
-> 1053         owner_data = create(path + ".tmp", args)
   1054         os.rename(path + ".tmp", path)
   1055 try:

File [/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/earthkit/data/sources/cds.py:136](http://localhost:5678/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/earthkit/data/sources/cds.py#line=135), in CdsRetriever._retrieve.<locals>.retrieve(target, args)
    135 def retrieve(target, args):
--> 136     cds_result = self.client().retrieve(args[0], args[1])
    137     self.source_filename = cds_result.location.split("[/](http://localhost:5678/)")[-1]
    138     cds_result.download(target=target)

File [/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/cdsapi/api.py:381](http://localhost:5678/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/cdsapi/api.py#line=380), in Client.retrieve(self, name, request, target)
    380 def retrieve(self, name, request, target=None):
--> 381     result = self._api("%s[/resources/](http://localhost:5678/resources/)%s" % (self.url, name), request, "POST")
    382     if target is not None:
    383         result.download(target)

File [/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/cdsapi/api.py:481](http://localhost:5678/data/common/miniforge3/envs/wp5/lib/python3.11/site-packages/cdsapi/api.py#line=480), in Client._api(self, url, request, method)
    476             e.append(
    477                 "To access this resource, you first need to accept the terms"
    478                 "of '%s' at %s" % (t["title"], t["url"])
    479             )
    480         error = ". ".join(e)
--> 481     raise Exception(error)
    482 else:
    483     raise

Exception: Not Found`

**Comment by malmans2** [comment]
Yesterday the legacy CDS was decommissioned. See: https://forum.ecmwf.int/t/goodbye-legacy-climate-data-store-hello-new-climate-data-store-cds/6380

You need to update your `.cdsapirc` with the new credentials.

**Comment by gmandorl** [comment]
Hi @malmans2,

I am trying to use the land-sea mask you suggested. It works, however, it frequently causes my Jupyter notebook to crash. I've created a simple notebook to replicate the problem. Could the crashes be due to high memory usage? Do you have any recommendations on how I can resolve this?


[test_land_mask.zip](https://github.com/user-attachments/files/17364852/test_land_mask.zip)

**Comment by malmans2** [comment]
Hi @gmandorl,

Someone was using a lot of memory, probably due to a stale job. It should work fine now.

A couple of suggestions:

- Once you're done developing, we can wrap the masking part in the transform function, which will allow us to cache the masking step. I can help you optimize it when your notebook is more stable (just ping me when you're ready).
- Please remember to stop the Jupyter Lab server when you're finished (e.g., every day when you are done working). If everyone does this, we'll make better use of the VM resources. You can follow the instructions printed on the terminal by `jupyter_server`: `jupyter lab stop ...`

**Comment by malmans2** [comment]
Hi @gmandorl,

Do you need further help on this ticket or can I close it?

**Comment by gmandorl** [comment]
Hi @malmans2,

The land/sea mask you suggested worked well, thank you for the help.
We can close this issue.
