### ISSUE TITLE
Clear the cache

### ISSUE THREAD

**Issue by paololanteri** [bopen/c3s-eqc-toolbox-template#17]
Hi Mattia,

After some downloads on my local machine I got the following error:

OperationalError: (sqlite3.OperationalError) database or disk is full
[SQL: DELETE FROM cache_entries WHERE cache_entries."key" = ? AND cache_entries.expiration = ?]
[parameters: ('c655af6fd80fc01a6fb2fa741e8dbf9d', '9999-12-31 23:59:59.999999')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

how do you suggest to clear the cache whenever we saturate its capacity?

**Comment by malmans2** [comment]
Hi @paololanteri,
At the moment the cache is never cleared automatically, but there's a function that allows you to do it.
You need to explicitly use that function in you code whenever you want to make sure that the cache size does not exceed a threshold.
The function is `cacholote.clean_cache_files`. The first arguments is the maximum size of the cache in bytes (e.g., `cacholote.clean_cache_files(0)` would delete all files.
There are other arguments to customize the cleaner. See `help(cacholote.clean_cache_files)`.

(In the future, we will add a cronjob in the VM to clean the cache)
