### ISSUE TITLE
Jupyter Notebook Nº2 - LC

### ISSUE THREAD

**Issue by inesgirao** [bopen/c3s-eqc-toolbox-template#174]
### Notebook description

Jupyter Notebook Nº2 - LC
Changes in the code were necessary so I send again the JN for use case 2 for techincal revision.

### Notebook link or upload

[C3S2_D520.5.3.14b_Quality_Assessment_User_Questions_LULC_UQ2_v1.7.zip](https://github.com/user-attachments/files/18218234/C3S2_D520.5.3.14b_Quality_Assessment_User_Questions_LULC_UQ2_v1.7.zip)

### Environment

<details>
Brotli==1.1.0
Cartopy==0.24.1
Mako==1.3.8
Markdown==3.7
MarkupSafe==3.0.2
PySocks==1.7.1
PyYAML==6.0.2
SQLAlchemy==2.0.36
SQLAlchemy-Utils==0.41.2
Send2Trash==1.8.3
affine==2.4.0
alembic==1.14.0
annotated-types==0.7.0
anyio==4.7.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
array-api-compat==1.9.1
arrow==1.3.0
asttokens==3.0.0
async-lru==2.0.4
attrs==24.2.0
autocommand==2.2.2
babel==2.16.0
backports.tarfile==1.2.0
beautifulsoup4==4.12.3
bleach==6.2.0
c3s-eqc-automatic-quality-control==0.1.2.dev113+g12de045
cached-property==1.5.2
cacholote==1.4.0
cdsapi==0.7.5
certifi==2024.12.14
cf-units==3.3.0
cf-xarray==0.10.0
cffi==1.17.1
cfgrib==0.9.14.1
cftime==1.6.4.post1
cgul==0.0.4
charset-normalizer==3.4.0
click==8.1.7
click-plugins==1.1.1
cligj==0.7.2
cloudpickle==3.1.0
comm==0.2.2
contourpy==1.3.1
cycler==0.12.1
dask==2024.12.0
datapi==0.1.1
debugpy==1.8.9
decorator==5.1.1
defusedxml==0.7.1
earthkit-data==0.11.4
earthkit-geo==0.3.0
earthkit-meteo==0.3.0
eccodes==2.39.0
ecmwflibs==0.6.3
entrypoints==0.4
exceptiongroup==1.2.2
executing==2.1.0
fastjsonschema==2.21.1
filelock==3.16.1
findlibs==0.0.5
fonttools==4.55.2
fqdn==1.5.1
fsspec==2024.10.0
geopandas==1.0.1
greenlet==3.1.1
h11==0.14.0
h2==4.1.0
hpack==4.0.0
httpcore==1.0.7
httpx==0.28.1
hyperframe==6.0.1
idna==3.10
importlib-metadata==8.5.0
importlib-resources==6.4.5
inflect==7.3.1
ipykernel==6.29.5
ipython==8.30.0
isoduration==20.11.0
jaraco.collections==5.1.0
jaraco.context==5.3.0
jaraco.functools==4.0.1
jaraco.text==3.12.1
jedi==0.19.2
jinja2==3.1.4
joblib==1.4.2
json5==0.10.0
jsonpointer==3.0.0
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
jupyter-client==7.4.9
jupyter-core==5.7.2
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter-server==2.14.2
jupyter-server-terminals==0.5.3
jupyterlab==4.3.3
jupyterlab-pygments==0.3.0
jupyterlab-server==2.27.3
kiwisolver==1.4.7
locket==1.0.0
lru-dict==1.3.0
matplotlib==3.9.3
matplotlib-inline==0.1.7
mistune==3.0.2
more-itertools==10.3.0
multiurl==0.3.3
nbclient==0.10.1
nbconvert==7.16.4
nbformat==5.10.4
nest-asyncio==1.6.0
netCDF4==1.7.2
notebook==7.3.1
notebook-shim==0.2.4
numpy==2.2.0
overrides==7.7.0
packaging==24.2
pandas==2.2.3
pandocfilters==1.5.0
parso==0.8.4
partd==1.4.2
patsy==1.0.1
pdbufr==0.11.0
pexpect==4.9.0
pickleshare==0.7.5
pillow==11.0.0
pip==24.3.1
pkgutil-resolve-name==1.3.10
platformdirs==4.3.6
plotly==5.24.1
pooch==1.8.2
prometheus-client==0.21.1
prompt-toolkit==3.0.48
properscoring==0.1
psutil==6.1.0
ptyprocess==0.7.0
pure-eval==0.2.3
pycparser==2.22
pydantic==2.10.3
pydantic-core==2.27.1
pydantic-settings==2.6.1
pygments==2.18.0
pyogrio==0.10.0
pyparsing==3.2.0
pyproj==3.7.0
pyshp==2.3.1
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-json-logger==2.0.7
pytz==2024.2
pyzmq==24.0.1
rasterio==1.4.3
referencing==0.35.1
regionmask==0.13.0
requests==2.32.3
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rioxarray==0.18.1
rpds-py==0.22.3
scipy==1.14.1
seaborn==0.13.2
setuptools==75.3.0
shapely==2.0.6
six==1.17.0
sniffio==1.3.1
soupsieve==2.5
stack-data==0.6.3
statsmodels==0.14.4
structlog==24.4.0
tabulate==0.9.0
tenacity==9.0.0
terminado==0.18.1
tinycss2==1.4.0
tomli==2.2.1
toolz==1.0.0
tornado==6.4.2
tqdm==4.67.1
traitlets==5.14.3
typeguard==4.3.0
types-python-dateutil==2.9.0.20241206
typing-extensions==4.12.2
typing-utils==0.1.0
tzdata==2024.2
uri-template==1.3.0
urllib3==2.2.3
wcwidth==0.2.13
webcolors==24.11.1
webencodings==0.5.1
websocket-client==1.8.0
wheel==0.44.0
xarray==2024.11.0
xhistogram==0.3.2
xskillscore==0.0.26
zipp==3.21.0
zstandard==0.23.0
/tmp/ipykernel_523282/4036504839.py:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources

</details>

**Comment by malmans2** [comment]
Hi @inesgirao,

Didn't we already optimise this code? I noticed a very similar template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/LULC_land_cover_urbanization_trends.ipynb

Do you need me to review something specific? At first glance, it seems like you adapted the template by reorganising the code to suit your needs, so the notebook looks in good shape to me.

**Comment by malmans2** [comment]
I just ran the notebook on the VM, and it works as expected.
You can request a permalink if you need to submit this notebook in the CIM.
I’ll be on leave next week, so if you need this completed before the end of the month, please make sure to handle it this week.
