### ISSUE TITLE
Euro-CORDEX simulations download 

### ISSUE THREAD

**Issue by lsangelantoni** [bopen/c3s-eqc-toolbox-template#20]
Hi Mattia, 

we are failing to download Euro-CORDEX simulations. 
We regularly download them with the "old" cdsapi but some issue comes up with the download_and_transform function of the new toolbox that does not recognize some input parameters. 

In the attachment, you can find the related section of the code. 
[issue_download_cdx.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/10861975/issue_download_cdx.zip)

Many thanks, 
Lorenzo

**Comment by malmans2** [comment]
Hi @lsangelantoni,

I'll take a look.
At the moment `download_and_transform` is also using cdsapi under the hood. A couple of questions:
1. Did you try locally, on the VM, or both?
2. Have you tried the same exact request on the same machine using `cdsapi`?

**Comment by lsangelantoni** [comment]
Hi Mattia,

thanks,
- I am currently working on a local server.
- Yes I have already downloaded the same combination of a global and
regional climate model. All the other download parameters are the same.

Lorenzo

**Comment by malmans2** [comment]
@lsangelantoni Looking at the [download form](https://cds.climate.copernicus.eu/cdsapp#!/dataset/projections-cordex-domains-single-levels?tab=form), `year` and `month` are not valid parameters for this dataset.
You should use `start_year` and/or `end_year`.
