### ISSUE TITLE
New to Python and Jupyter#2 - Using cdstoolbox

### ISSUE THREAD

**Issue by sandrocalmanti** [bopen/c3s-eqc-toolbox-template#22]
To speed-up my learning curve in python/jupyter I'd like to  use some of the examples in the toolbox gallery. I've picked a random one 

[https://cds.climate.copernicus.eu/toolbox-editor/gallery/10_anomaly_plot](https://cds.climate.copernicus.eu/toolbox-editor/gallery/10_anomaly_plot)

but I'm not able to import the cdstoolbox

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 2
      1 import calendar
----> 2 import cdstoolbox as ct
      4 # Define the list of years to retrieve
      5 ERA5_YEARS = [str(year) for year in range(1979, 2020 + 1)]

ModuleNotFoundError: No module named 'cdstoolbox'
```

The gallery has a lot of nice exemples that will be useful to implement use cases. Is it possible to have it available on the VM?

**Comment by malmans2** [comment]
Hi @sandrocalmanti,

It is not possible to install `cdstoolbox` on the VM. It can only be used here (see Toolbox Editor): https://cds.climate.copernicus.eu/cdsapp#!/toolbox

Some clarifications:
1. ECMWF is leading the development of a new version of it, which is called `cads-toolbox`. The new version is open-source and `c3s-eqc-automatic-quality-control` is using it under the hood. At the moment, only download and caching have been implemented in `cads-toolbox`.
2. The training material shared by ECMWF does not use `cdstoolbox`. This is the link: https://ecmwf-projects.github.io/copernicus-training-c3s/intro.html
3. If you need some of the old functionalities of `cdstoolbox` to develop your notebook, you would have to make a feature request to ECMWF. I think confluence is the best place to discuss it. Please add a comment [here](https://confluence.ecmwf.int/display/CDSM/WG+-+Toolbox) tagging both Eddy and James as they are the maintainers of the new `cads-toolbox`.

**Comment by sandrocalmanti** [comment]
Ok thanks.
