### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by sandrocalmanti** [bopen/c3s-eqc-toolbox-template#27]
Hi, 

just to highlight that this is producing an _Attirbute error_.  Is there any missing transformation function?

[my_notebook.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/11003198/my_notebook.zip)

Best!

Sandro

**Comment by malmans2** [comment]
Hi @sandrocalmanti ,

There are a few issues I need to report upstream to the ECMWF dev team.
For this dataset, if you need to download and open the dataset without doing any transformation, just define a dummy function.

Looks like that way we are able to avoid the bug because each chunk is harmonised separately.

E.g.,
```python
from c3s_eqc_automatic_quality_control import download

collection_id = "reanalysis-era5-single-levels-monthly-means"
request = {
    "product_type": "monthly_averaged_reanalysis",
    "format": "grib",
    "time": "00:00",
    "variable": "2m_temperature",
}

start = "2022-01"
stop = None
requests = download.update_request_date(request, start=start, stop=stop)

def dummy_transform_func(ds):
    return ds

ds_mean = download.download_and_transform(
    collection_id,
    requests,
    transform_func=dummy_transform_func,
    chunks={"year": 1, "month": 1},
)
```

**Comment by malmans2** [comment]
Hi,
There's now a workaround in our code, so you should be able to open the dataset without having to define a dummy function:
```python
from c3s_eqc_automatic_quality_control import download

collection_id = "reanalysis-era5-single-levels-monthly-means"
request = {
    "product_type": "monthly_averaged_reanalysis",
    "format": "grib",
    "time": "00:00",
    "variable": "2m_temperature",
}

start = "2022-01"
stop = None
requests = download.update_request_date(request, start=start, stop=stop)

ds = download.download_and_transform(
    collection_id,
    requests,
    chunks={"year": 1, "month": 1},
)
```

**Comment by malmans2** [comment]
Closing this as I think it's fixed. But feel free to repoen
