### ISSUE TITLE
Jupyter Notebook for the EOBS dataset - to be reviewed and optimised w/ eqc toolbox

### ISSUE THREAD

**Issue by anolive** [bopen/c3s-eqc-toolbox-template#32]
Dear Mattia and B-OPEN team,

As agreed previously, please find here attached the First Use Case/User Question for the E-OBS catalogue entry (this one: https://cds.climate.copernicus.eu/cdsapp#!/dataset/insitu-gridded-observations-europe?tab=overview).

As with the LULC, this first version uses the cdsapi and our go-to libraries in handling this type of dataset. In this case, CDO is also used (together with Xarray).

We will meanwhile work on the LULC update (issue #26).

Let us know what you think. Thank you in advance.
Ana

[C3S2_D520.5.3.2_Quality_Assessment_User_Questions_EOBS_UQ1_v1.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/11055863/C3S2_D520.5.3.2_Quality_Assessment_User_Questions_EOBS_UQ1_v1.zip)

**Comment by ritavcunha** [comment]
@malmans2 the notebook it is now working! Thank you very much, your suggestion helped a lot!

**Comment by malmans2** [comment]
Hi there, I'm closing this as looks like you are able to run the template.
Feel free to re-open or open more issues though!
