### ISSUE TITLE
WG5 deliverable: Water Lakes temperature

### ISSUE THREAD

**Issue by Cri-dei** [bopen/c3s-eqc-toolbox-template#33]
### Notebook description

Use Case: Check completeness of lake water temperature time series for Great African Lakes and outliers detection.

User Question: The satellite lakes water temperature dataset for Great African Lakes is complete in time? Are there some outliers? 

Methods: 

        - Select Great African Lakes area and extract the mean water lakes temperature
        - Plot the time series
        - Calculate percentage of missing values
        - Boxplot of the values and outliers detection
        

### Notebook link or upload

[Lake_water_temperature_ Outlier detection.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/11123512/Lake_water_temperature_.Outlier.detection.zip)

### Anything else we need to know?

I changed the code that you initially sent me since I notice the high percentage of missing values and outliers, this I think is more significative.

### Environment

<details>

</details>

**Comment by malmans2** [comment]
I've updated the template, let me know if anything doesn't look right.
https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/lake_water_temperature_outlier_detection.ipynb
