### ISSUE TITLE
WG5 Deliverable: Soil moisture

### ISSUE THREAD

**Issue by Cri-dei** [bopen/c3s-eqc-toolbox-template#34]
### Notebook description

World spatial coverage of satellite soil moisture data considering the interval 1997-2002.

Use questions: 
Satellite soil moisture data can be used for whatever case study in the world or there is a spatial variability of data availability?

Methods:

         - Calculate the percentage of missing values for each grid cell
         - Mask the dataframe considering only inland data
         - Plot the map of percentage of missing values for the selected period
         - Plot for each continent the map and histogram of missing values

### Notebook link or upload

[Soil moisture_ Completeness.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/11123588/Soil.moisture_.Completeness.zip)

### Anything else we need to know?

Can we fix the x limit for the plot for North America, Asia and Oceania?

The continents are cut and not entire. I will put the zoom on the main area, I know that do like to include some islands that maybe are farthest.

![image](https://user-images.githubusercontent.com/56677048/229167844-c109c545-86f1-4ab7-87c9-3a209bc5a28e.png)
![image](https://user-images.githubusercontent.com/56677048/229168234-ce7131cb-1a06-4c4b-afa6-fd37557f9ce5.png)
![image](https://user-images.githubusercontent.com/56677048/229168481-e90e0e00-0e38-4db6-9e3b-dc8c9f276109.png)

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Hi!
Sure, here is an example to do that:
```python
fig, (ax_imshow, ax_hist) = imshow_and_hist(ds["mvc"], world_shape)
ax_imshow.set_xlim([-50, 50])
ax_imshow.set_ylim([-20, 20])
```
![image](https://user-images.githubusercontent.com/22245117/230600886-cc047fce-7fe2-4aee-a858-5e7e6b2d9197.png)

So you just have to define the limits you want to change.

**Comment by malmans2** [comment]
Hi @Cri-dei,
Do you need anything from me about this issue, or can we close it?

**Comment by Cri-dei** [comment]
Hi @malmans2 ,
actually yes I would still need help for it. The changes of axis limit is something that has to be changed inside the function you create to visualize the plot. I can not change it directly in the code, because they are already fixed in the function when all the continents are defined.

**Comment by malmans2** [comment]
Hi @Cri-dei,
Sorry, I don't think I'm following.

The snippet in my previous comment shows how to modify the limits after running the plotting function.
```python
fig, (ax_imshow, ax_hist) = imshow_and_hist(ds["mvc"], world_shape)
ax_imshow.set_xlim([-50, 50])
ax_imshow.set_ylim([-20, 20])
```
Also, the plotting function is defined in the notebook itself, so you can modify it to accept the limits.

Anyways, I can easily update the notebook for you. Just send me the x/y limits you'd like to use for all continents.

**Comment by Cri-dei** [comment]
Okay I tried again to recompile it and I have now an error for the shapefile.

For the axis limit, these are the continent that has to be specified. The other continets are fine in the plot.

```
#Asia
fig, (ax_imshow, ax_hist) = imshow_and_hist(ds["mvc"], world_shape.CONTINENT==Asia)
ax_imshow.set_xlim([0, 160])
ax_imshow.set_ylim([-15, 80])

#North America
ax_imshow.set_xlim([-160, 10])
ax_imshow.set_ylim([90, 5])

#Oceania
ax_imshow.set_xlim([100, 160])
ax_imshow.set_ylim([-50, 10])

```
Thank  you!

![image](https://github.com/bopen/c3s-eqc-toolbox-template/assets/56677048/c81bc49b-f265-49a2-ab8e-59983deaa6a5)

**Comment by malmans2** [comment]
Good catch, the libraries we are using introduced a breaking change. 
It's fixed now.

I've added the code to customize the limits of imshow (some of them don't look correct, but now you can easily change them). See: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/soil_moisture_dataquality.ipynb
Please send me the final version of `continent_limits` when you are done.

(BTW, are you OK with the histogram always showing the whole continent? Or should the histogram only show the statistics within x_lim/y_lim that you specify?)

**Comment by malmans2** [comment]
Hi @Cri-dei,

What's the status of this notebook? I'm trying to close old issues so we don't have too many open.
Do you want me to update the template, or are you OK with the latest version?
