### ISSUE TITLE
Need the module iris on VM

### ISSUE THREAD

**Issue by sandrocalmanti** [bopen/c3s-eqc-toolbox-template#38]
### Describe the solution you'd like

[my_ipynb.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/11160557/my_ipynb.zip)

Dear Mattia,

to boost my learning curve in python and at the same time do some useful work for our deliverables I'm trying to recycle some codes used by Yassmina during past contracts (attached).

It seems I need to use a module named `iris`

Is it possible to have this in the VM?

Cheers

Sandro

**Comment by malmans2** [comment]
No problem,

Which WP are you using? Until we start using that package more widely, I will only install it on you WP environment.

**Comment by malmans2** [comment]
I realised you should be WP3 if I'm not mistaken.
Iris is now available on WP3 environment on the VM.

**Comment by sandrocalmanti** [comment]
Ciao Mattia,

that's actually work for wp5 and I'm trying to keep things in order and separated between WP3 and WP5. Sorry I didn't highlight the working WP before. Nice to have `iris` on both, anyway

**Comment by malmans2** [comment]
Done!
