### ISSUE TITLE
Can't compute spatially-weighted global mean timeseries for "satellite-carbon-dioxide"

### ISSUE THREAD

**Issue by paolocristofanelli** [bopen/c3s-eqc-toolbox-template#41]
```python
import os
os.environ["CDSAPI_RC"] = os.path.expanduser("~/cristofanelli_paolo/.cdsapirc")

collection_id = "satellite-carbon-dioxide"

#year_start = 2018
#year_stop = 2019

request = {
    'format': 'zip',
    'processing_level': 'level_3',
    'variable': 'xco2',
    'sensor_and_algorithm': 'merged_obs4mips',
    'format': 'zip',
    #"year": [str(year) for year in range(year_start, year_stop + 1)],
    #"month": [f"{month:02d}" for month in range(1, 12 + 1)],
    'version': '4.4'
}

ds_mean = download.download_and_transform(
    collection_id,
    request,
    transform_func=diagnostics.spatial_weighted_mean
    #split_all=True,
)

0%|          | 0/1 [00:00<?, ?it/s]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[17], line 1
----> 1 ds_mean = download.download_and_transform(
      2     collection_id,
      3     request,
      4     transform_func=diagnostics.spatial_weighted_mean
      5     #split_all=True,
      6 )

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/c3s_eqc_automatic_quality_control/download.py:474, in download_and_transform(collection_id, requests, chunks, split_all, transform_func, transform_func_kwargs, transform_chunks, logger, **open_mfdataset_kwargs)
    472 sources = []
    473 for request in tqdm.tqdm(request_list):
--> 474     ds = download_and_transform_requests(
    475         collection_id,
    476         [request],
    477         transform_func,
    478         transform_func_kwargs,
    479         **open_mfdataset_kwargs,
    480     )
    481     sources.append(ds.encoding["source"])
    482 open_mfdataset_kwargs.pop("preprocess", None)  # Already preprocessed

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/cacholote/cache.py:104, in cacheable.<locals>.wrapper(*args, **kwargs)
    101             warnings.warn(str(ex), UserWarning)
    102             _delete_cache_entry(session, cache_entry)
--> 104 result = func(*args, **kwargs)
    105 cache_entry = database.CacheEntry(
    106     key=hexdigest,
    107     expiration=settings.expiration,
    108     tag=settings.tag,
    109 )
    110 try:

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/c3s_eqc_automatic_quality_control/download.py:395, in _download_and_transform_requests(collection_id, request_list, transform_func, transform_func_kwargs, **open_mfdataset_kwargs)
    392     ds = xr.open_mfdataset(sources, **open_mfdataset_kwargs)
    394 if transform_func is not None:
--> 395     ds = transform_func(ds, **transform_func_kwargs)
    396     if not isinstance(ds, xr.Dataset):
    397         raise TypeError(
    398             f"`transform_func` must return a xr.Dataset, while it returned {type(ds)}"
    399         )

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/c3s_eqc_automatic_quality_control/diagnostics.py:182, in spatial_weighted_mean(obj, lon, lat)
    165 def spatial_weighted_mean(
    166     obj: xr.Dataset | xr.DataArray, lon: str | None = None, lat: str | None = None
    167 ) -> xr.Dataset | xr.DataArray:
    168     """
    169     Calculate spatial mean of ds with latitude weighting.
    170 
   (...)
    180     reduced object
    181     """
--> 182     return _spatial_weighted_reduction(obj, "mean", lon, lat)

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/c3s_eqc_automatic_quality_control/diagnostics.py:161, in _spatial_weighted_reduction(obj, func, lon, lat, **kwargs)
    159 with xr.set_options(keep_attrs=True):  # type: ignore[no-untyped-call]
    160     weights = _spatial_weights(obj, lon, lat)
--> 161     obj = getattr(obj.weighted(weights), func)(dim=(lon, lat), **kwargs)
    162 return obj

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/weighted.py:483, in Weighted.mean(self, dim, skipna, keep_attrs)
    477 def mean(
    478     self,
    479     dim: Dims = None,
    480     skipna: bool | None = None,
    481     keep_attrs: bool | None = None,
    482 ) -> T_Xarray:
--> 483     return self._implementation(
    484         self._weighted_mean, dim=dim, skipna=skipna, keep_attrs=keep_attrs
    485     )

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/weighted.py:540, in DatasetWeighted._implementation(self, func, dim, **kwargs)
    537 def _implementation(self, func, dim, **kwargs) -> Dataset:
    538     self._check_dim(dim)
--> 540     return self.obj.map(func, dim=dim, **kwargs)

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/dataset.py:5957, in Dataset.map(self, func, keep_attrs, args, **kwargs)
   5955 if keep_attrs is None:
   5956     keep_attrs = _get_keep_attrs(default=False)
-> 5957 variables = {
   5958     k: maybe_wrap_array(v, func(v, *args, **kwargs))
   5959     for k, v in self.data_vars.items()
   5960 }
   5961 if keep_attrs:
   5962     for k, v in variables.items():

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/dataset.py:5958, in <dictcomp>(.0)
   5955 if keep_attrs is None:
   5956     keep_attrs = _get_keep_attrs(default=False)
   5957 variables = {
-> 5958     k: maybe_wrap_array(v, func(v, *args, **kwargs))
   5959     for k, v in self.data_vars.items()
   5960 }
   5961 if keep_attrs:
   5962     for k, v in variables.items():

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/weighted.py:281, in Weighted._weighted_mean(self, da, dim, skipna)
    273 def _weighted_mean(
    274     self,
    275     da: DataArray,
    276     dim: Dims = None,
    277     skipna: bool | None = None,
    278 ) -> DataArray:
    279     """Reduce a DataArray by a weighted ``mean`` along some dimension(s)."""
--> 281     weighted_sum = self._weighted_sum(da, dim=dim, skipna=skipna)
    283     sum_of_weights = self._sum_of_weights(da, dim=dim)
    285     return weighted_sum / sum_of_weights

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/weighted.py:271, in Weighted._weighted_sum(self, da, dim, skipna)
    263 def _weighted_sum(
    264     self,
    265     da: DataArray,
    266     dim: Dims = None,
    267     skipna: bool | None = None,
    268 ) -> DataArray:
    269     """Reduce a DataArray by a weighted ``sum`` along some dimension(s)."""
--> 271     return self._reduce(da, self.weights, dim=dim, skipna=skipna)

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/weighted.py:229, in Weighted._reduce(da, weights, dim, skipna)
    225     da = da.fillna(0.0)
    227 # `dot` does not broadcast arrays, so this avoids creating a large
    228 # DataArray (if `weights` has additional dimensions)
--> 229 return dot(da, weights, dims=dim)

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/computation.py:1770, in dot(dims, *arrays, **kwargs)
   1767 # subscripts should be passed to np.einsum as arg, not as kwargs. We need
   1768 # to construct a partial function for apply_ufunc to work.
   1769 func = functools.partial(duck_array_ops.einsum, subscripts, **kwargs)
-> 1770 result = apply_ufunc(
   1771     func,
   1772     *arrays,
   1773     input_core_dims=input_core_dims,
   1774     output_core_dims=output_core_dims,
   1775     join=join,
   1776     dask="allowed",
   1777 )
   1778 return result.transpose(*all_dims, missing_dims="ignore")

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/computation.py:1205, in apply_ufunc(func, input_core_dims, output_core_dims, exclude_dims, vectorize, join, dataset_join, dataset_fill_value, keep_attrs, kwargs, dask, output_dtypes, output_sizes, meta, dask_gufunc_kwargs, *args)
   1203 # feed DataArray apply_variable_ufunc through apply_dataarray_vfunc
   1204 elif any(isinstance(a, DataArray) for a in args):
-> 1205     return apply_dataarray_vfunc(
   1206         variables_vfunc,
   1207         *args,
   1208         signature=signature,
   1209         join=join,
   1210         exclude_dims=exclude_dims,
   1211         keep_attrs=keep_attrs,
   1212     )
   1213 # feed Variables directly through apply_variable_ufunc
   1214 elif any(isinstance(a, Variable) for a in args):

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/computation.py:312, in apply_dataarray_vfunc(func, signature, join, exclude_dims, keep_attrs, *args)
    307 result_coords, result_indexes = build_output_coords_and_indexes(
    308     args, signature, exclude_dims, combine_attrs=keep_attrs
    309 )
    311 data_vars = [getattr(a, "variable", a) for a in args]
--> 312 result_var = func(*data_vars)
    314 out: tuple[DataArray, ...] | DataArray
    315 if signature.num_outputs > 1:

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/computation.py:769, in apply_variable_ufunc(func, signature, exclude_dims, dask, output_dtypes, vectorize, keep_attrs, dask_gufunc_kwargs, *args)
    764     if vectorize:
    765         func = _vectorize(
    766             func, signature, output_dtypes=output_dtypes, exclude_dims=exclude_dims
    767         )
--> 769 result_data = func(*input_data)
    771 if signature.num_outputs == 1:
    772     result_data = (result_data,)

File <__array_function__ internals>:180, in einsum(*args, **kwargs)

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/dask/array/core.py:1760, in Array.__array_function__(self, func, types, args, kwargs)
   1757 if has_keyword(da_func, "like"):
   1758     kwargs["like"] = self
-> 1760 return da_func(*args, **kwargs)

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/dask/array/einsumfuncs.py:213, in einsum(dtype, optimize, split_every, *operands, **kwargs)
    211 # Infer the output dtype from operands
    212 if dtype is None:
--> 213     dtype = np.result_type(*[o.dtype for o in ops])
    215 if optimize is not False:
    216     # Avoid computation of dask arrays within np.einsum_path
    217     # by passing in small numpy arrays broadcasted
    218     # up to the right shape
    219     fake_ops = [np.broadcast_to(o.dtype.type(0), shape=o.shape) for o in ops]

File <__array_function__ internals>:180, in result_type(*args, **kwargs)

TypeError: The DType <class 'numpy.dtype[datetime64]'> could not be promoted by <class 'numpy.dtype[float64]'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtype[datetime64]'>, <class 'numpy.dtype[float64]'>)
```

**Comment by malmans2** [comment]
Hi @paolocristofanelli,
There something wrong about the `"time_bnds"` variable.

A quick fix is:
```python
ds_mean = download.download_and_transform(
    collection_id,
    request,
    transform_func=diagnostics.spatial_weighted_mean,
    drop_variables=("time_bnds",)
    )
```

(In the long term, I think the best solution would be to automatically find bounds and upgrade those variables to coordinates. I will have a look and let you know if I can implement it in our software)

**Comment by paolocristofanelli** [comment]
It worked. Now, tried the same for std:

ds_std = download.download_and_transform(
    collection_id,
    request,
    transform_func=diagnostics.spatial_weighted_std,
    drop_variables=("time_bnds",)
)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[20], line 1
----> 1 ds_std = download.download_and_transform(
      2     collection_id,
      3     request,
      4     transform_func=diagnostics.spatial_weighted_std,
      5     drop_variables=("time_bnds",)
      6 )

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/c3s_eqc_automatic_quality_control/download.py:474, in download_and_transform(collection_id, requests, chunks, split_all, transform_func, transform_func_kwargs, transform_chunks, logger, **open_mfdataset_kwargs)
    472 sources = []
    473 for request in tqdm.tqdm(request_list):
--> 474     ds = download_and_transform_requests(
    475         collection_id,
    476         [request],
    477         transform_func,
    478         transform_func_kwargs,
    479         **open_mfdataset_kwargs,
    480     )
    481     sources.append(ds.encoding["source"])
    482 open_mfdataset_kwargs.pop("preprocess", None)  # Already preprocessed

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/cacholote/cache.py:104, in cacheable.<locals>.wrapper(*args, **kwargs)
    101             warnings.warn(str(ex), UserWarning)
    102             _delete_cache_entry(session, cache_entry)
--> 104 result = func(*args, **kwargs)
    105 cache_entry = database.CacheEntry(
    106     key=hexdigest,
    107     expiration=settings.expiration,
    108     tag=settings.tag,
    109 )
    110 try:

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/c3s_eqc_automatic_quality_control/download.py:395, in _download_and_transform_requests(collection_id, request_list, transform_func, transform_func_kwargs, **open_mfdataset_kwargs)
    392     ds = xr.open_mfdataset(sources, **open_mfdataset_kwargs)
    394 if transform_func is not None:
--> 395     ds = transform_func(ds, **transform_func_kwargs)
    396     if not isinstance(ds, xr.Dataset):
    397         raise TypeError(
    398             f"`transform_func` must return a xr.Dataset, while it returned {type(ds)}"
    399         )

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/c3s_eqc_automatic_quality_control/diagnostics.py:202, in spatial_weighted_std(obj, lon, lat)
    185 def spatial_weighted_std(
    186     obj: xr.Dataset | xr.DataArray, lon: str | None = None, lat: str | None = None
    187 ) -> xr.Dataset | xr.DataArray:
    188     """
    189     Calculate spatial std with latitude weighting.
    190 
   (...)
    200     reduced object
    201     """
--> 202     return _spatial_weighted_reduction(obj, "std", lon, lat)

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/c3s_eqc_automatic_quality_control/diagnostics.py:161, in _spatial_weighted_reduction(obj, func, lon, lat, **kwargs)
    159 with xr.set_options(keep_attrs=True):  # type: ignore[no-untyped-call]
    160     weights = _spatial_weights(obj, lon, lat)
--> 161     obj = getattr(obj.weighted(weights), func)(dim=(lon, lat), **kwargs)
    162 return obj

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/weighted.py:503, in Weighted.std(self, dim, skipna, keep_attrs)
    497 def std(
    498     self,
    499     dim: Dims = None,
    500     skipna: bool | None = None,
    501     keep_attrs: bool | None = None,
    502 ) -> T_Xarray:
--> 503     return self._implementation(
    504         self._weighted_std, dim=dim, skipna=skipna, keep_attrs=keep_attrs
    505     )

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/weighted.py:540, in DatasetWeighted._implementation(self, func, dim, **kwargs)
    537 def _implementation(self, func, dim, **kwargs) -> Dataset:
    538     self._check_dim(dim)
--> 540     return self.obj.map(func, dim=dim, **kwargs)

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/dataset.py:5957, in Dataset.map(self, func, keep_attrs, args, **kwargs)
   5955 if keep_attrs is None:
   5956     keep_attrs = _get_keep_attrs(default=False)
-> 5957 variables = {
   5958     k: maybe_wrap_array(v, func(v, *args, **kwargs))
   5959     for k, v in self.data_vars.items()
   5960 }
   5961 if keep_attrs:
   5962     for k, v in variables.items():

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/dataset.py:5958, in <dictcomp>(.0)
   5955 if keep_attrs is None:
   5956     keep_attrs = _get_keep_attrs(default=False)
   5957 variables = {
-> 5958     k: maybe_wrap_array(v, func(v, *args, **kwargs))
   5959     for k, v in self.data_vars.items()
   5960 }
   5961 if keep_attrs:
   5962     for k, v in variables.items():

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/weighted.py:309, in Weighted._weighted_std(self, da, dim, skipna)
    301 def _weighted_std(
    302     self,
    303     da: DataArray,
    304     dim: Dims = None,
    305     skipna: bool | None = None,
    306 ) -> DataArray:
    307     """Reduce a DataArray by a weighted ``std`` along some dimension(s)."""
--> 309     return cast("DataArray", np.sqrt(self._weighted_var(da, dim, skipna)))

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/weighted.py:295, in Weighted._weighted_var(self, da, dim, skipna)
    287 def _weighted_var(
    288     self,
    289     da: DataArray,
    290     dim: Dims = None,
    291     skipna: bool | None = None,
    292 ) -> DataArray:
    293     """Reduce a DataArray by a weighted ``var`` along some dimension(s)."""
--> 295     sum_of_squares = self._sum_of_squares(da, dim=dim, skipna=skipna)
    297     sum_of_weights = self._sum_of_weights(da, dim=dim)
    299     return sum_of_squares / sum_of_weights

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/weighted.py:259, in Weighted._sum_of_squares(self, da, dim, skipna)
    251 def _sum_of_squares(
    252     self,
    253     da: DataArray,
    254     dim: Dims = None,
    255     skipna: bool | None = None,
    256 ) -> DataArray:
    257     """Reduce a DataArray by a weighted ``sum_of_squares`` along some dimension(s)."""
--> 259     demeaned = da - da.weighted(self.weights).mean(dim=dim)
    261     return self._reduce((demeaned**2), self.weights, dim=dim, skipna=skipna)

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/weighted.py:483, in Weighted.mean(self, dim, skipna, keep_attrs)
    477 def mean(
    478     self,
    479     dim: Dims = None,
    480     skipna: bool | None = None,
    481     keep_attrs: bool | None = None,
    482 ) -> T_Xarray:
--> 483     return self._implementation(
    484         self._weighted_mean, dim=dim, skipna=skipna, keep_attrs=keep_attrs
    485     )

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/weighted.py:529, in DataArrayWeighted._implementation(self, func, dim, **kwargs)
    528 def _implementation(self, func, dim, **kwargs) -> DataArray:
--> 529     self._check_dim(dim)
    531     dataset = self.obj._to_temp_dataset()
    532     dataset = dataset.map(func, dim=dim, **kwargs)

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/weighted.py:203, in Weighted._check_dim(self, dim)
    201 missing_dims = set(dims) - set(self.obj.dims) - set(self.weights.dims)
    202 if missing_dims:
--> 203     raise ValueError(
    204         f"{self.__class__.__name__} does not contain the dimensions: {missing_dims}"
    205     )

ValueError: DataArrayWeighted does not contain the dimensions: {'longitude'}

**Comment by malmans2** [comment]
This dataset looks a little tricky and needs some special care.
The problem now is that there's a dimension named `"pressure"` and a 1D variable named `"pre"` that is not a coordinate.

If you don't care about bounds, I would do this as a temporary workaround:
```python
def preprocess(ds):
    ds = ds.assign_coords(pressure = ds["pre"])
    ds = ds.drop("pre")
    return ds.drop_dims("bnds")
    
ds_mean = download.download_and_transform(
    collection_id,
    request,
    transform_func=diagnostics.spatial_weighted_mean,
    preprocess=preprocess
    )
    
ds_std = download.download_and_transform(
    collection_id,
    request,
    transform_func=diagnostics.spatial_weighted_std,
    preprocess=preprocess
    )
```

(BTW, you can also use `diagnostics.spatial_weighted_statistics` and compute mean, std, and median using a single function)

**Comment by paolocristofanelli** [comment]
@malmans2 thanks. Do we have a documentation repository for the available functions?

**Comment by malmans2** [comment]
Not yet, but you can do this:
```python
from c3s_eqc_automatic_quality_control import runner
runner.list_diagnostics()
```

Then you can use help, most of the functions have docstrings already:
```python
help(diagnostics.spatial_weighted_statistics)
```

**Comment by malmans2** [comment]
Re-opened this so I'll remember to implement this upstream, so in there future we don't need the workaround to correctly open this dataset.
