### ISSUE TITLE
Extract single year or region from satellite-carbon-dioxide dataset L3

### ISSUE THREAD

**Issue by paolocristofanelli** [bopen/c3s-eqc-toolbox-template#44]
Hello @malmans2 

I'm trying to extract a single year and a specific region from 

collection_id = "satellite-carbon-dioxide"
request = {
    'format': 'zip',
    'processing_level': 'level_3',
    'variable': 'xco2',
    'sensor_and_algorithm': 'merged_obs4mips',
    'format': 'zip',
    'version': '4.4'
}

I tried to implement the following piece of code to extract specific years and regions but isn't effective. Any hints?

# Define region
lon_slice = slice(0, 180)
lat_slice = slice(-90, 90)

def preprocess(ds):
    ds = ds.assign_coords(pressure = ds["pre"])
    ds = ds.drop("pre")
    ds = ds.sel(time='2018') #to extract 2018
   ds = utils.regionalise(ds, lon_slice=lon_slice, lat_slice=lat_slice)
 return ds.drop_dims("bnds")

**Comment by malmans2** [comment]
Closing this as it should be fixed.
