### ISSUE TITLE
Sorted data in time

### ISSUE THREAD

**Issue by annemo1976** [bopen/c3s-eqc-toolbox-template#48]
### What happened?

Hi

When I use the toolbox to download seasonal data by using chunks, I get data in a random order and sorted in time. Is there some options in download_and_transform that I can use so I don't have to sort the data afterwards? 

Best regards Anne-Mette 

### Minimal Complete Verifiable Example

```Python
from c3s_eqc_automatic_quality_control import diagnostics, download, plot

collection_id = "seasonal-monthly-single-levels"
request = {
    "format":             "grib",
    "originating_centre": "cmcc",
    "system":             "35",
    "variable":           "2m_temperature",
    "product_type":       "monthly_mean",
    "year":               [str(year) for year in range(1993, 2000)] ,
    "leadtime_month":     "5",
    "month":              "01",
    "area":               [89.5,-179.5,-89.5,179.5],
    "grid":               "1/1",
}

xr_open_mfdataset_kwargs = {
    "concat_dim": "forecast_reference_time",
    "combine": "nested",
    "parallel": True,
}

dsh = download.download_and_transform(
    collection_id,
    request,
    chunks={"year": 1, "leadtime_month": 1},
    **xr_open_mfdataset_kwargs,
)
dsh
```

### Relevant log output

```Python
forecast_reference_time
(forecast_reference_time)
datetime64[ns]
1999-01-01 ... 1996-01-01
array(['1999-01-01T00:00:00.000000000', '1997-01-01T00:00:00.000000000',
       '1993-01-01T00:00:00.000000000', '1998-01-01T00:00:00.000000000',
       '1994-01-01T00:00:00.000000000', '1995-01-01T00:00:00.000000000',
       '1996-01-01T00:00:00.000000000'], dtype='datetime64[ns]')
```

### Anything else we need to know?

I was running on VM.

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Hi,

What happens if you use [this](https://github.com/bopen/c3s-eqc-toolbox-template/issues/30#issuecomment-1482619306) to open the dataset? I. e., replace the `xr_open_mfdataset_kwargs` with `backend_kwargs`.

If that doesn't work, I would sort the dataset after opening it: `dsh.sortby("forecast_reference_time")`

**Comment by annemo1976** [comment]
That seems to work, now I get the data sorted. Thank you!!
