### ISSUE TITLE
Seasonal anomalies and trend - XCH4 dataset satellite

### ISSUE THREAD

**Issue by malmans2** [bopen/c3s-eqc-toolbox-template#52]
Hi @malmans2,
now I need to calculate seasonal anomalies (DJF, MAM, JJA, SON or only one selected season as test - let's say JJA) for each single year from this dataset with daily time resolution and then plotting global maps of the obtained seasonal anomalies for each single year (i.e. JJA 2006, JJA 2007,...). 

The workflow should be as following:
1)	To calculate the global trend for the whole dataset timeframe  (e.g. 2006 – 2021)
2)	To detrend the daily values from the global trend
3)	To calculate over a regular grid the seasonal averages from the daily files
4)	To calculate over the same grid the anomalies of the seasonal averages 

Is there any technical solution available of useful codes which I can adapt?
Thank you

_Originally posted by @paolocristofanelli in https://github.com/bopen/c3s-eqc-toolbox-template/issues/47#issuecomment-1540209377_

**Comment by malmans2** [comment]
Hi @paolocristofanelli,
Let's use a dedicated issue for this discussion.


> now I need to calculate seasonal anomalies (DJF, MAM, JJA, SON or only one selected season as test - let's say JJA) for each single year from this dataset with daily time resolution

Do you need to weight the results? If you don't, you can just do this:
```python
def seasonal_mean(ds):
    return ds.groupby("time.season").mean()

anomaly_ds = ds.groupby("time.year").map(seasonal_mean) - seasonal_mean(ds)
```
`anomaly_ds` will have the following dimensions:
```
Dimensions: season year layer_dim level_dim
```
where season is ["DJF", "MAM", "JJA", "SON"].

(BTW, we do have a function for seasonal weighted means, used for example in [this notebook](https://github.com/bopen/c3s-eqc-toolbox-template/blob/16cba7819d9f9bf7cbd232fd54d0a1835d05e1f1/notebooks/wp4/clima_t2m.ipynb#L116) to compute seasonal means from monthly data. But because you have daily data, I don't think you need to apply weights).

**Comment by malmans2** [comment]
>  and then plotting global maps of the obtained seasonal anomalies for each single year (i.e. JJA 2006, JJA 2007,...).

What kind of plots do you need to do? We have a plotting function to plot projected maps (`c3s_eqc_automatic_quality_control.plot.projected_map`, also used in [this notebook](https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp4/clima_t2m.ipynb)), but that only works with lat/lon gridded data.

It looks like `satellite-methane` is not gridded. Do you already have code to regrid/plot? If yes, could you please send me a snippet?

**Comment by malmans2** [comment]
> The workflow should be as following:
> 1)	To calculate the global trend for the whole dataset timeframe  (e.g. 2006 – 2021)
> 2)	To detrend the daily values from the global trend
> 3)	To calculate over a regular grid the seasonal averages from the daily files
> 4)	To calculate over the same grid the anomalies of the seasonal averages 
> 
> Is there any technical solution available of useful codes which I can adapt?

The workflow looks very similar to the analysis done in [trend_pr_cmip6.ipynb](https://github.com/bopen/c3s-eqc-toolbox-template/blob/16cba7819d9f9bf7cbd232fd54d0a1835d05e1f1/notebooks/wp4/trend_pr_cmip6.ipynb). In that notebook the trends are computed using a package named `xarrayMannKendall`. However, it's not available on the wp5 environmen. Let me know if you need it on the VM.

**Comment by paolocristofanelli** [comment]
Hi @malmans2,

Great! I don't think that I need to weight starting  from daily data 
Yes, I need to re-grid, indeed. Can yo share with me the list of the available re-gridding methods so that I can tell you which is the most suitable? 
It would be useful to have the xarrayMannKendall package on WP5, thank you.  For this type of data the method https://gml.noaa.gov/aftp/user/thoning/ccgcrv/ is typically used for trend calculation. However, in my knowledge it is not implemented yet in satellite or gridded datasets.

**Comment by malmans2** [comment]
I will install `xarrayMannKendall` late tonight (looks like a few users are using the VM at the moment).

We do have a function to regrid (`diagnostics.regrid` used in the notebooks mentioned in my previous comment). It uses `xesmf` under the hood. This are the available algorithms: https://xesmf.readthedocs.io/en/latest/notebooks/Compare_algorithms.html
However, I'm not sure whether `xesmf` is OK for ungridded data. We have been using it to regrid from gridded to gridded. I'll have a look at it tomorrow.

**Comment by paolocristofanelli** [comment]
In any case 1 X 1 degree should be fine. In this dataset only the center of the observation is provided (no boundaries)

**Comment by malmans2** [comment]
Hi @paolocristofanelli,

`xarrayMannKendall` is now available on the VM.
I think we can use `xesmf` for the regridding, but I need more info about how you exactly intend to perform the regridding (some subjective choice needs to be made I think, like the grouping to do before regridding and the interpolation algorithm).

It looks like something similar is already available on the CDS. Can you use level 3 data? They are monthly data regridded on a 5x5 grid.
Here is an example:
```python
from c3s_eqc_automatic_quality_control import download, diagnostics, plot
import cartopy.crs as ccrs
import xarray as xr

collection_id = 'satellite-methane'
request = {
        'processing_level': 'level_3',
        'variable': 'xch4',
        'sensor_and_algorithm': 'merged_obs4mips',
        'version': '4.4',
        'format': 'zip',
    }
ds = download.download_and_transform(collection_id, request)

climatology = diagnostics.seasonal_weighted_mean(ds)
with xr.set_options(keep_attrs=True):
    anomaly = ds.groupby("time.year").map(diagnostics.seasonal_weighted_mean) - climatology
    
plot.projected_map(anomaly["xch4"], projection=ccrs.Robinson(), col="season", row="year")
```
which produces this plot:
![image](https://github.com/bopen/c3s-eqc-toolbox-template/assets/22245117/b3896abb-837a-4be5-bc3e-1756da9e5cdd)

**Comment by malmans2** [comment]
OK!
If you need feedback from us on the detranding step, please share a snippet or detailed instructions on how you intend to perform it.

**Comment by malmans2** [comment]
Got it. I believe we need to group the time dimension before regridding.
Is monthly OK (similarly to what is done for level-3 data)?

**Comment by paolocristofanelli** [comment]
Yes, monthly it's ok

**Comment by malmans2** [comment]
> Hi @malmans2,
> 
> for regridding level-2, we can use arithmetic unweighted averaging of all data falling in the grid box. Maybe excluding grid box with less than 1 level-2 data.

Actually, I realised that nearest_d2s is not exactly this. I'll think about it, it looks like xesmf does not support this. As you don't want to use weights, we probably don't even have to use a library for lat\lon data.

**Comment by paolocristofanelli** [comment]
Hi @malmans2,

I will test the notebook on Friday and I will let you know. Many thanks, up to now!

**Comment by malmans2** [comment]
Ok, no rush from my side.

I've updated the template notebook, implementing the code to regrid using  arithmetic unweighted averaging.
If the function works as expected, we can probably add it to diagnostic functions in `c3s_eqc_automatic_quality_control`.

**Comment by paolocristofanelli** [comment]
Hi @malmans2,

I tested the code https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/xch4_satellite_lev2.ipynb

When increasing the number of considered years (eg. start = 2005, end=2007)  I got: "Exception: Client has not agreed to the required terms and conditions.. To access this resource, you first need to accept the termsof 'GHG-CCI Licence' at https://cds.climate.copernicus.eu/cdsapp/#!/terms/ghg-cci"

I need to add:
"import os
os.environ["CDSAPI_RC"] = os.path.expanduser("~/cristofanelli_paolo/.cdsapirc")"

How to mask only for data over land?

**Comment by malmans2** [comment]
Hi @paolocristofanelli,

Working on another notebook I realised that you probably want timeseries where DJF are actually D(year-1)J(year)F(year).
Before we had `D(year)J(year)F(year)`, so J and D are 11 months apart. I've fixed it in the notebook template, but let me know if you actually prefer the former version.

Here it is: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/xch4_satellite_lev2.ipynb

**Comment by paolocristofanelli** [comment]
Hello @malmans2 

here you can find a draft notebook for .
1) calculating spatial trends of XCO2 and XCH4 anomalies
2) calculating seasonal anomalies of XCO2 and XCH4 after detrending.

When going to the point 2 , I got this error. Can you give me a guidance about how to fix?

[Notebook_xch4-xco2_20230617.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/11779074/Notebook_xch4-xco2_20230617.zip)


[----------------------------------------------------------------------------------------------------------------------------]
/data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/duck_array_ops.py:188: RuntimeWarning: invalid value encountered in cast
  return data.astype(dtype, **kwargs)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[11], line 11
      2 request_model = request
      4 transform_func_kwargs = {
      5     "year_start": year_start,
      6     "year_stop": year_stop,
      7     "clima_year_start": clima_year_start,
      8     "clima_year_stop": clima_year_stop,
      9 }
---> 11 ds = download.download_and_transform(
     12     *request_model,
     13     #chunks=chunks,
     14     transform_func=compute_anomaly,
     15     transform_func_kwargs={**transform_func_kwargs,},
     16     transform_chunks=False,
     17     preprocess=preprocess
     18 )
     20 # Detrending anomalies
     21 ds = detrend_dim(ds, "time", 1)

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/c3s_eqc_automatic_quality_control/download.py:554, in download_and_transform(collection_id, requests, chunks, split_all, transform_func, transform_func_kwargs, transform_chunks, n_jobs, invalidate_cache, cached_open_mfdataset_kwargs, **open_mfdataset_kwargs)
    550         if invalidate_cache:
    551             cacholote.delete(
    552                 func.func, *func.args, request_list=request_list, **func.keywords
    553             )
--> 554         ds = func(request_list=request_list)
    556 ds.attrs.pop("coordinates", None)  # Previously added to guarantee roundtrip
    557 return ds

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/cacholote/cache.py:86, in cacheable.<locals>.wrapper(*args, **kwargs)
     83             warnings.warn(str(ex), UserWarning)
     84             clean._delete_cache_entry(session, cache_entry)
---> 86 result = func(*args, **kwargs)
     87 cache_entry = database.CacheEntry(
     88     key=hexdigest,
     89     expiration=settings.expiration,
     90     tag=settings.tag,
     91 )
     92 try:

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/c3s_eqc_automatic_quality_control/download.py:434, in _download_and_transform_requests(collection_id, request_list, transform_func, transform_func_kwargs, **open_mfdataset_kwargs)
    431     ds = xr.open_mfdataset(sources, **open_mfdataset_kwargs)
    433 if transform_func is not None:
--> 434     ds = transform_func(ds, **transform_func_kwargs)
    435     if not isinstance(ds, xr.Dataset):
    436         raise TypeError(
    437             f"`transform_func` must return a xr.Dataset, while it returned {type(ds)}"
    438         )

Cell In[7], line 71, in compute_anomaly(da, clima_year_start, clima_year_stop, year_start, year_stop)
     68 da = da.where(mask.compute(), drop=True)
     70 # Compute anomaly
---> 71 clima = compute_climatology(da, clima_year_start, clima_year_stop)
     72 anoma = da - clima
     73 with xr.set_options(keep_attrs=True):

Cell In[7], line 60, in compute_climatology(da, clima_year_start, clima_year_stop)
     56 def compute_climatology(da, clima_year_start, clima_year_stop):
     57      # Select years (shift -1 to get D(year-1)J(year)F(year))
     58      #da = da.assign_coords(year=da["time"].dt.year.shift(time=-1).astype(int))
---> 60      return da.sel(year=slice(clima_year_start, clima_year_stop)).mean(
     61         "year", keep_attrs=True
     62     )

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/dataset.py:2642, in Dataset.sel(self, indexers, method, tolerance, drop, **indexers_kwargs)
   2581 """Returns a new dataset with each array indexed by tick labels
   2582 along the specified dimension(s).
   2583 
   (...)
   2639 DataArray.sel
   2640 """
   2641 indexers = either_dict_or_kwargs(indexers, indexers_kwargs, "sel")
-> 2642 query_results = map_index_queries(
   2643     self, indexers=indexers, method=method, tolerance=tolerance
   2644 )
   2646 if drop:
   2647     no_scalar_variables = {}

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/indexing.py:182, in map_index_queries(obj, indexers, method, tolerance, **indexers_kwargs)
    179     options = {"method": method, "tolerance": tolerance}
    181 indexers = either_dict_or_kwargs(indexers, indexers_kwargs, "map_index_queries")
--> 182 grouped_indexers = group_indexers_by_index(obj, indexers, options)
    184 results = []
    185 for index, labels in grouped_indexers:

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/indexing.py:144, in group_indexers_by_index(obj, indexers, options)
    142     grouped_indexers[index_id][key] = label
    143 elif key in obj.coords:
--> 144     raise KeyError(f"no index found for coordinate {key!r}")
    145 elif key not in obj.dims:
    146     raise KeyError(f"{key!r} is not a valid dimension or coordinate")

KeyError: "no index found for coordinate 'year'"

**Comment by malmans2** [comment]
Hi @paolocristofanelli,

The notebook for WP4 always reduces monthly data to either seasonal or annual timeseries.
Looks like you are looking for something slightly different in the last section of your notebook.
Could you please check whether this notebook is doing what you are looking for? 
[trend_cristofanelli.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/11787241/trend_cristofanelli.zip)

I think we can also simplify a bit your notebook, but let's think about it later when you are ready for a last round of review.

**Comment by paolocristofanelli** [comment]
@malmans2 thank you, I'implemented it into the notebook 
[Notebook_xch4-xco2_20230621.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/11816371/Notebook_xch4-xco2_20230621.zip)

I have some issues with working with xco2 data:
1) Figure 1: values are not expressed in ppm (must be still multiplied by 10^6)
![Figure1_xco2](https://github.com/bopen/c3s-eqc-toolbox-template/assets/62693475/22c63751-f310-4e18-bc10-109939c2a3ed)

2) Figure 2: only the year 2018 is plotted instead of 2003-2021
![Figure2_xco2](https://github.com/bopen/c3s-eqc-toolbox-template/assets/62693475/a1b781c0-6f76-4d66-988c-cf47a7e1e65b)

3) Figure 3: it seems that equally zero values are present over oceans. This looks strange since I did not enable land mask.
![Figure3_xco2](https://github.com/bopen/c3s-eqc-toolbox-template/assets/62693475/fd36de18-7333-48e1-acfc-3ae93a18bb72)

Thanks a lot for your hints!

**Comment by paolocristofanelli** [comment]
@malmans2 for Figure 1 this is correct (seasonal means) but, you are right, I forgot to implement the time shift handling D an J.

**Comment by paolocristofanelli** [comment]
Yes, spatial weights on. Where possible I would keep the spatial weights on also for the other functions.

**Comment by malmans2** [comment]
Got it.
What should be the input off the Mann Kendall test? Monthly anomalies?
So `da.groupby("time.month") - da.groupby("time.month").mean()`?
So we have monthly data, and from each month we remove the climatology of the corresponding month?

**Comment by malmans2** [comment]
@paolocristofanelli, I prepared a new notebook for you. Here it is: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/wip_xch4_xco2.ipynb

I've simplified it quite a bit, it looks like you don't need many of the features used in WP4.
It should be easier to follow now. Please make sure that everything works correctly, because I believe most of the results changed.


> This looks strange since I did not enable land mask.

If you edit a cached function without changing its name or its arguments, you are not going to see changes because we use previously computed values. When you are developing/debugging, it's useful to deactivate the cache. You can achieve that by using the argument `invalidate_cache=True` of `download_and_transform`. Alternatively, you can set the global variable `download.INVALIDATE_CACHE = True`. Invalidating the cache does not clear raw data, so you won't have to re-download data.

**Comment by paolocristofanelli** [comment]
Thank you @malmans2 : looks much more clean and effective, now! 
A further general question: in the case, we like to activate subsetting of data (masking) based on ancillary variables as "land_fraction" or "xch4_nobs"/"xco2_nobs", what is best strategy? To implement the masking in the preprocessing or in the cached function? Do you have an example of code to be used?

**Comment by malmans2** [comment]
Good question, I'll add that option in the template (I should have time to do in in the next hour or so).

Your data is not that big, I don't think ti would affect performance too much.
Probably better to cache the masked data, I think some of the results might change (e.g., spatially weighted means).

**Comment by malmans2** [comment]
@paolocristofanelli I added a paremeter: `min_land_fraction`
`min_land_fraction = None`: do not mask.
`min_land_fraction = 0.5`: only use data where `land_fraction >= 0.5`

Please test it out and let me know if everything is working as expected.

The caching approach we are using works well if you are not planning to change very often the `min_land_fraction` parameter (e.g., `min_land_fraction = 0.5` and `min_land_fraction = 0.51` would create 2 different cache files).

I renamed the notebook. Here it is: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/xch4_xco2_satellite_lev3.ipynb

**Comment by paolocristofanelli** [comment]
@malmans2 thanks it works! looking to Figure 3 (Global trends) it seems that trend values (0.0 ppm/yr) are given also for masked data (see oceans) and that they are used to calculate the global statistics on the right. Any way to mask them out for the global statistic calculations?

**Comment by malmans2** [comment]
Good catch. Looks like the Mann Kendall library we are using is not handling very well all nans (they do have an issue opened already on GH).

I added the masking. Please try the [last notebook](https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/xch4_xco2_satellite_lev3.ipynb) and let me know.
I've changed the name of the affected function, so you don't have to manually invalidate the cache.

You should get this with `min_land_fraction = 0.5`:
![image](https://github.com/bopen/c3s-eqc-toolbox-template/assets/22245117/4ad82ba3-71ca-4bfc-8dea-1c6618a02bf7)

**Comment by paolocristofanelli** [comment]
@malmans2 I think we can close this issue. I will open a new one for the final test of the notebook

**Comment by malmans2** [comment]
Sounds good!
