### ISSUE TITLE
Seasonal standard deviation

### ISSUE THREAD

**Issue by vincenzodetoma** [bopen/c3s-eqc-toolbox-template#55]
### Describe the solution you'd like

Hi Mattia, will it be possible to implement a function analogous to the already present seasonal_weighted_mean already present in the c3s_eqc_automatic_quality_control diagnostics module but with the standard deviation?
I send you my function which runs over the dataset without any preprocessing step.

```python
def season_std(ds, period=[None,None]):
    if period!= [None, None]:
        return ds.sel(time=slice(period[0], period[1])).groupby('time.season').std('time')
    else:
        return ds.groupby('time.season').std('time')
```
Feel free to modify also without the specification of the period keyword, since I will give it as an argument in the request to the CADS.

Thanks,
Vincenzo

**Comment by vincenzodetoma** [comment]
PS: I attach to you a notebook I wrote to work on local data we already have (on a 1-degree spatial resolution to make computations lighter), which I'll have to modify according to existing or future functionalities within the toolbox. 

[html_satellite_userquestion_1.pdf](https://github.com/bopen/c3s-eqc-toolbox-template/files/11496776/html_satellite_userquestion_1.pdf)

**Comment by malmans2** [comment]
Ohh I forgot, did you want me to review the notebook?
If yes, could you please open a new issue choosing the notebook submission form?

Also, please attach the notebook in `.ipynb` format and make sure I can run it (i.e., make sure you don't use local data previously downloaded, but include any code you used to download data).
