### ISSUE TITLE
Filter for subdaily data

### ISSUE THREAD

**Issue by sandrocalmanti** [bopen/c3s-eqc-toolbox-template#58]
### Describe the solution you'd like

Dear @malmans2 

I would like to apply a filter to my dataset with the following scheme 

```
def dfilt(zt,weights):

#Number of weight (should be an odd number)
k=weights.size
k2=int((k-1)/2)

#Length of the time series
N=zt.size

zt_filt=np.empty(0)
for i in range(1+k2,N-k2):    
   #Extract k time step around the central time
    chunk=zt[i-k2-1:i+k2]
   #Apply the filter as the scalar product between the chunk and the corresponding weights
    zt_filt=np.append(zt_filt, np.dot(chunk,dfilt))

return(zt_filt)
```

I have scketched it as it would by applied to a time series but I would apply the filter to the same 12-hourly data retrieved in the stormtrack notebook that you have already revised,

[ERA5_stormtrack_v1.0.ipynb.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/11602084/ERA5_stormtrack_v1.0.ipynb.zip)

 and obtain a 3D array (longitude,latitude,time) with of 12-hourly filtered data to which I would then apply some other statistics ("mean" or "std").

This type of function might be quite useful since, depending on the weights defined by the user, the filter might become anything among a running, mean, a generic low-pass , band-pass or high-pass filter to analyse different aspects of a time series or 2D fileds.

For example, a running mean (which might be the default option) would have N+1 weights (N even) all equal to 1/(N+1). Different sequences of weights can be defined by the user.

Does it sound feasible for you to implement this filter in a way that is can run efficiently on a 3D (longitude,latitude,time) array and work as a filter in the time dimension?

I have tried to write it myself, but it becomes incredibly slow and therefore useless.  It is important for our case study because we need to demonstrate the use of high-requency (sub-daily) data.

Please let me know if the description of the function we need is clear.

Best!

Sandro

**Comment by malmans2** [comment]
Hi @sandrocalmanti,

Let me check whether I'm understanding correctly. Say you define the weights like this:
```
[1, 2, 1]
```
you'd like to apply a rolling average with window of size 3, where the central value weights twice the right/left values. (I think we need to normalize weights to compute means with dot, otherwise it's a weighted sum)

Is the code below doing what you are looking for?
```python
import xarray as xr
from c3s_eqc_automatic_quality_control import download

# Select time period and chunks
start = "1980"
stop = "1989"  # None: present
chunks = {"year": 1, "time": 1}

# Define request
collection_id = "reanalysis-era5-pressure-levels"
request = {
    "product_type": "reanalysis",
    "format": "grib",
    "variable": "geopotential",
    "pressure_level": "500",
    "area": [90, -180, 30, 180],
    "time": ["00:00", "12:00"],
}
requests = download.update_request_date(request, start=start, stop=stop)

ds = download.download_and_transform(
    collection_id,
    requests,
    concat_dim="forecast_reference_time",
    combine="nested",
    chunks=chunks
)

def rolling_weighted_mean(da, weights, dim, use_dot=True):
    weights = xr.DataArray(weights, dims="window")
    rolling_da = da.rolling(
        forecast_reference_time=weights.size, center=True
    ).construct("window")
    if use_dot:
        weights = weights / weights.sum()  # Normalize weights
        return rolling_da.dot(weights)

    # The method below would be better as we don't have to code the reduction
    # (i.e., just use mean, std, ...)
    # However, I keep getting memory errors on the VM. I need to explore it, looks like
    # an xarray/dask problem
    return rolling_da.weighted(weights).mean("window")

weights = [1, 2, 3, 4, 3, 2, 1]
da = rolling_weighted_mean(ds["z"], weights, "forecast_reference_time")

da.isel(forecast_reference_time=100).plot()
```

If the code above is correct, I'll cleanup and generalize the function, and I'll add it to our software. Unfortunately, looks like we can't use xarray's native weighting (see comment in the code), so I'll have to code a similar one for std.

Let me know.

**Comment by sandrocalmanti** [comment]
@malmans2   one question.

The `dim` parameter passed to rolling_weighted_mean is not used, is it?

I would call this function *rolling_weighted_filter* which becomes a "mean" only in special cases.  The 1-2-1 filter would be kind of a noise reduction.

**Comment by malmans2** [comment]
Ooops, good catch. To have it working with any dataset, it's supposed to be like that:
```python
def rolling_weighted_mean(da, weights, dim, use_dot=True):
    weights = xr.DataArray(weights, dims="window")
    rolling_da = da.rolling({dim: weights.size}, center=True).construct("window")
    if use_dot:
        weights = weights / weights.sum()  # Normalize weights
        return rolling_da.dot(weights)

    # The method below would be better as we don't have to code the reduction
    # (i.e., just use mean, std, ...)
    # However, I keep getting memory errors on the VM. I need to explore it, looks like
    # an xarray/dask problem
    return rolling_da.weighted(weights).mean("window")
```

All inline comments you added are correct. And the name you are suggesting works for me.

Just one question: Is the normalisation of the weights needed?
I.e., should we remove the normalisation step and assume that the user will pass normalised weights if they need a rolling mean?
For example, in your notebook you had negative weights I think. I'm not sure whether normalisation is good there.

**Comment by malmans2** [comment]
Hi, the function is now ready:
```python
import xarray as xr
from c3s_eqc_automatic_quality_control import download, diagnostics

# Select time period and chunks
start = "1980"
stop = "1989"  # None: present
chunks = {"year": 1, "time": 1}

# Define request
collection_id = "reanalysis-era5-pressure-levels"
request = {
    "product_type": "reanalysis",
    "format": "grib",
    "variable": "geopotential",
    "pressure_level": "500",
    "area": [90, -180, 30, 180],
    "time": ["00:00", "12:00"],
}
requests = download.update_request_date(request, start=start, stop=stop)

weights = [
    0.82119,
    -0.16871,
    -0.14062,
    -0.10059,
    -0.05682,
    -0.01752,
    0.01118,
    0.02646,
    0.02906,
    0.02250,
    0.01163,
    0.00101,
    -0.00624,
    -0.00903,
    -0.00801,
    -0.00491,
]

ds = download.download_and_transform(
    collection_id,
    requests,
    chunks=chunks,
    transform_chunks=False,
    transform_func=diagnostics.rolling_weighted_filter,
    transform_func_kwargs={"weights_mapper": {"forecast_reference_time": weights}},
    concat_dim="forecast_reference_time",
    combine="nested",
)
```

See: `help(diagnostics.rolling_weighted_filter)`.
I changed a bit the API. You need to provide a dictionary mapping `{dim: weights}`. This way it should work fine with multidimensional filters as well.

Next time you use the VM, could you please restart the server? I've changed a couple of env variables, and you'll need to restart in order to get them. For example, do this:
1. From local terminal, kill all opened ssh: `pskill ssh`
2. Form your directory on the VM, run `jupyter_server` and follow the instructions to kill the server (last line)
3. Run `jupyter_server` and follow the usual instructions to open the SSH tunnel and use jupyter

**Comment by malmans2** [comment]
Hi Sandro,

I forgot to mention a couple of minor comments about your notebook:
1. `print(da_mean.reduce(np.min,dim=["longitude","latitude","season"]).values)` -> `print(da_mean.min().values)`
2. To get all diagnostics available: `print(diagnostics.__all__)`

**Comment by sandrocalmanti** [comment]
Thank you @malmans2  looks great! And thanks for the shortcut.

I will test it will keep you posted.

**Comment by sandrocalmanti** [comment]
That's wierd.

I'm testing the filter function and I apply a seasonal std to the filtered data to get an DataArray  `da_std_bp` of size (4,241,1440). If I try to plot `da_std_bp` or compute some simple statistics (min,max), I get a memory error because it is trying to allocate space for a DataArray of size (6638,241,1440), which is the size of the original filterd data.

What am I doing wrong?

```
import xarray as xr
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy

from c3s_eqc_automatic_quality_control import diagnostics, download, plot
plt.style.use("seaborn-v0_8-notebook")

# Select time period and chunks
start = "1980"
stop = "1989"  # None: present
chunks = {"year": 1, "time": 1}


# Define request
collection_id = "reanalysis-era5-pressure-levels"
request = {
    "product_type": "reanalysis",
    "format": "grib",
    "variable": "geopotential",
    "pressure_level": "500",
    "area": [90, -180, 30, 180],
    "time": ["00:00", "12:00"],
}
requests = download.update_request_date(request, start=start, stop=stop)


#Band-pass
weights = np.array([0.27769,
                    0.14335, 
                   -0.10201,
                   -0.19477,
                   -0.09233,
                    0.02830,
                    0.04193,
                    0.00335,
                    0.00411,
                    0.03281,
                    0.03043,
                   -0.00200,
                   -0.01917,
                   -0.00967,
                   -0.00013,
                   -0.00304])
weights = np.concatenate((np.flip(weights[1:]),weights))

ds_bandpass = download.download_and_transform(
    collection_id,
    requests,
    chunks=chunks,
    transform_chunks=False,
    transform_func=diagnostics.rolling_weighted_filter,
    transform_func_kwargs={"weights_mapper": {"forecast_reference_time": weights}},
    concat_dim="forecast_reference_time",
    combine="nested",
)


ds_bandpass_seasonal=ds_bandpass.groupby("forecast_reference_time.season").std("forecast_reference_time")
with xr.set_options(keep_attrs=True):
    da_std_bp  = ds_bandpass_seasonal["z"]/(9.8)

print(da_std_bp.min().values)

fig, axs = plt.subplots(2,2,
                        subplot_kw={'projection': ccrs.NorthPolarStereo(central_longitude=0)},
                        figsize=(15,15))
    
for i,ax in enumerate(axs.flat):   
  cs1 = ax.contour(da_std_bp["longitude"],da_std_bp["latitude"],da_std_bp.sel(season=da_std_bp["season"].values[i]),
                 colors='k',
                 linewidths=0.5,
                 linestyles="dashed",
                 levels=range(0,200,10),
                 transform=ccrs.PlateCarree())
  cs2 = ax.contour(da_std_bp["longitude"],da_std_bp["latitude"],da_std_bp.sel(season=da_std["season"].values[i]),
                 colors='k',
                 linewidths=2.0,
                 levels=range(0,200,40),
                 transform=ccrs.PlateCarree())
  ax.clabel(cs1)
  ax.set_title(da_mean["season"].values[i], fontsize=16)
  ax.coastlines(color="lightgray")
  ax.add_feature(cartopy.feature.LAND)

fig.suptitle('RMS ERA5 500hPa geopotential height [m]', fontsize=20)

```

**Comment by sandrocalmanti** [comment]
@malmans2 

it works nicely and thanks for the clarification on the caching scenarios. Understood.

![image](https://github.com/bopen/c3s-eqc-toolbox-template/assets/53210493/6759fa24-a1ac-4111-a58f-8eac6af1d72a)

**Comment by malmans2** [comment]
Closing this in favour of #66
