### ISSUE TITLE
500mb geopotential and storm tracks in ERA5 

### ISSUE THREAD

**Issue by sandrocalmanti** [bopen/c3s-eqc-toolbox-template#66]
### Notebook description

This is the quasi-final form of the notebook on storm-tracks as seen from ERA5.

The code is complete, it does everything it has to do, but needs to be optimized. For example a mapping function would be more efficient and readable than repeating the same lines of code.

In the notebook, the user can select the season of interest `soi` to visualize the corresponding season

Meanwhile, I'm working on the description of the results and take-home messages to complete the notebook

Best!

S.

### Notebook link or upload

[C3S_520_D5_3_4b_NB1_ERA5_Storm-Track.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/11803681/C3S_520_D5_3_4b_NB1_ERA5_Storm-Track.zip)

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Hi @sandrocalmanti,

Looks good, and the way you are caching data is correct.

I think we can make use of `plot.projected_map` to make the plots, but I need to try.
I'll take a look this afternoon and I'll probably add a template for this use case.

**Comment by sandrocalmanti** [comment]
Thank you @malmans2 

After some discussion with my collegues I have implemented a small extention to this notebook, in order to compare the present climate with the backward extention of ERA5 to 1940.

I have added a new dimension `period` as done in other notebooks on the reanalysis.

It seems to work nicely quite to the end until I get a `Memory error`.

[ERA5_Stormtrack_periods.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/11962217/ERA5_Stormtrack_periods.zip)

I have tried to clear the kernel and restart, in case anything went wrong.
Is there anything we can do about that? Am I using the caching correctly?

Cheers

Sandro

**Comment by malmans2** [comment]
Hi @sandrocalmanti,

Especially when there are many users logged in, the VM is struggling to compute all seasons at once.
Let's cache all seasons separately.

I've updated the template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/era5_storm_track.ipynb
Here is the template rendered: https://gist.github.com/malmans2/c662d0899b9a7bb8d38542611e32124c

Let me know if it works OK.

**Comment by sandrocalmanti** [comment]
I have checked the rendering and it's just fine.

Theank you.
