### ISSUE TITLE
Uncertainty in seasonal forecasts for a single model system

### ISSUE THREAD

**Issue by annemo1976** [bopen/c3s-eqc-toolbox-template#67]
### Notebook description

This notebook explains how the range of outcomes covered by the ensemble members can be interpreted as the uncertainty for a seasonal forecast from the Copernicus Climate Change Service (C3S). The notebook provides an example of how this uncertainty can be visualized, compared with the climatology, and used in a practical way to make outlooks for the coming months.  

### Notebook link or upload

VM: /data/wp3/olsen_annem/annemo/uncertainty_densityplot.ipynb

Let me know if you also need a zipped ipynb-fil 

### Anything else we need to know?

From WP3 (Seasonal forecasts). The notebook is in the folder /data/wp3/olsen_annem/annemo/ on the VM's with the name: uncertainty_densityplot.ipynb . We are using the WP3-conda environment set up there. 

There is an error message that says: 
Error while converting 1 to months for forecastMonth.
 Units will not be converted.

Traceback:
Unable to convert from 'Unit('1')' to 'Unit('months')'.
Error while converting 1 to months for forecastMonth.
 Units will not be converted.

Traceback:
Unable to convert from 'Unit('1')' to 'Unit('months')'.

It will be nice if this could be hidden, but I could not find out how. 

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Hi @annemo1976,

The template for your use case is ready: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp3/uncertainty_densityplot.ipynb

I didn't make major changes, this is what I've done:
1. Added chunking (you can switch it off setting `chunks={}`). I think it's better to use chunking, so if you only change years you don't have to re-download and re-compute everything. Looks like the queue for this dataset sometimes is very slow! You can use the parameter `n_jobs` to speed it up, so chunking will not result in very slow download. For example, `n_jobs=5` will make 5 concurrent requests to the CDS.
2. Reduced data (global means) are now cached, so they're not recomputed every time

Please test it out and let me know if everything is working as expected. If you run the template as it is, everything should be already cached.

**Comment by malmans2** [comment]
Another quick comment: We are not 100% sure if interactive plots will be supported in the CIM.
Predictia is looking into this.

No worries though, if we can't use interactive plots we just need to do this: `fig.show(renderer="png")`

**Comment by annemo1976** [comment]
Hi Mattia

I have tested the new notebook and it looks great and works very well,
except for one minor issue in the title. I didn't figure out how to make
the chunking work together with indexing time, so very nice that you have
included the chunking :-)

The issue in the title is that it says for the first plot:

"Density plot of 2m temperature over Southern Norway for Jan 2023,
from ecmwf with start time 2023-06-01. Hindcast period from 1993 to 2016."

since month=6, it should say "for Jun 2023".

I see from the code that you use "leadtime_month" (which have values 1 to
6) and "year_forecast", but you need to calculate "valid_time" which is
"forecast_reference_time" + "leadtime_month" and use both "month" and
"year" from valid_time (forecast year = 2022 and month =12, gives
valid_time = 2022-12-01 for leadtime_month=1 and 2023-05-01 for
leadtime_month=6).

In my notebook I calculate valid_time with the code below that uses
dateutil.relativedelta:

   start_time = pd.to_datetime(dsf.forecast_reference_time.values)
   valid_time = start_time + relativedelta(months=month-1)
   title='Density plot of 2m temperature over '+name+' for
'+calendar.month_abbr[valid_time.month] \
         +' '+str(valid_time.year)+', <br>from '+centre+' with start time
'+str(start_time.date()) \
         + '. Hindcast period from '+ min(hcstyears)+' to '+
max(hcstyears)+'.'

Best regard Anne-Mette

lør. 24. juni 2023 kl. 13:44 skrev Mattia Almansi ***@***.***

**Comment by malmans2** [comment]
Ooops, my bad!
Can you check the latest version please?
https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp3/uncertainty_densityplot.ipynb

**Comment by annemo1976** [comment]
This works perfectly. I have checked both for ecmwf, dwd and ukmo, (ukmo
has a lagged ensemble and uses indexing time). They all seem to work fine.
Thank you very much Mattia!!

Anne-Mette

man. 26. juni 2023 kl. 11:34 skrev Mattia Almansi ***@***.***

**Comment by malmans2** [comment]
Awesome!
