### ISSUE TITLE
Notebook with Use Case 1 for XCO2 and XCH4 Dataset - Deliverable 30th June 2023

### ISSUE THREAD

**Issue by paolocristofanelli** [bopen/c3s-eqc-toolbox-template#68]
Hello,

here you can find the notebook for:

Category: Atmospheric trends and variability
Short Title: Seasonal Atmospheric XCH4 and XCO2 Anomalies
Use Case Title: A study on XCH4 and XCO2 seasonal anomalies

[C3S_520_Quality_assessment_XCH4_XCO2_v1.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/11847829/C3S_520_Quality_assessment_XCH4_XCO2_v1.zip)

In the future, for trend calculation of greenhouse gas, we should implement this method
https://gml.noaa.gov/ccgg/mbl/crvfit/crvfit.html

A  Python class for computing the curves is available at https://gml.noaa.gov/aftp/user/thoning/ccgcrv/

**Comment by paolocristofanelli** [comment]
I forgot to mention that for Fig1 I preferred to switch off the land masking to show the actual variable coverage of the dataset for the different years and seasons.

**Comment by malmans2** [comment]
Hi @paolocristofanelli,

Is this the same as the last template, right?

This repo is only used by B-Open to provide technical support. You need to coordinate with Chunxue for the submission of the actual deliverable (I imagine you also need to add comments about methods and results)

**Comment by malmans2** [comment]
> In the future, for trend calculation of greenhouse gas, we should implement this method
> https://gml.noaa.gov/ccgg/mbl/crvfit/crvfit.html
> 
> A Python class for computing the curves is available at https://gml.noaa.gov/aftp/user/thoning/ccgcrv/

Could you please open a new issue (Feature request). You don't need this by the end of the month, right?

**Comment by paolocristofanelli** [comment]
Just updated the notebook link since I linked a wrong file (now it's ok)

**Comment by malmans2** [comment]
Hi @paolocristofanelli, looks good as it's consistent with the template (we keep the templates as small as possible, so we don't add comments there). I think you'll have to share it somehow with Chunxue, I don't think they are following this repo nor getting deliverables from here.

A minor comment, please set `download.INVALIDATE_CACHE=False` or remove it from the notebook, so you take advantage of the caching as much as possible.
