### ISSUE TITLE
Era5Land use case 1 revision

### ISSUE THREAD

**Issue by Cri-dei** [bopen/c3s-eqc-toolbox-template#70]
### Notebook description

    - Download 2m temperature variable (K) selecting the boundary box area of Spain.
    - Choose years of analysis: here we selectef from 1997 to 2022
    - Calculate the average annual temperature for the entire Country
    - Changing units of measure from Kelvin to Celsius
    - Barplot grouped for year with annual temperature values
    - Trend and significance with Mann Kendall Test

### Notebook link or upload

[ERA-5Land_Temperature_rev.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/11866967/ERA-5Land_Temperature_rev.zip)

### Anything else we need to know?

Hi mattia,

I have to modify a bit the notebook. here some points:

- I have problem with the warning package
- I would like to add the values in the barplot, to replicate this plot: https://www.statista.com/statistics/1199822/average-monthly-temperature-spain/
- There is an error to calculate the trend and significance with Mann Kendall test, maybe it is linked to some packages? It was working before

Thank you

### Environment

<details>

</details>

**Comment by malmans2** [comment]
I've updated the template with the new features you need: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/era5_land_temperature.ipynb

Please test it out and let me know.

I you want to silence warnings (I do not recommend doing it unless warnings are very noisy), you need to import the `warnings` package.

```python
import warnings
warnings.simplefilter("ignore") 
```

**Comment by Cri-dei** [comment]
Thank you. 
I have still this error when running the Mann Kendall test:
![image](https://github.com/bopen/c3s-eqc-toolbox-template/assets/56677048/7f438263-9b21-4349-b823-258d92acaf8a)

**Comment by malmans2** [comment]
You probably need to restart the kernel

**Comment by Cri-dei** [comment]
Sorry Mattia, how I can not display the numbers?

**Comment by Cri-dei** [comment]
Sorry Mattia, how i can not display the numbers?
That part with: text and numbers

![image](https://github.com/bopen/c3s-eqc-toolbox-template/assets/56677048/b334fbaf-f046-4448-9e95-33cc86af7026)

**Comment by malmans2** [comment]
`jupyter` prints the last variable the last values that are not assigned.
In your case, the text objects. So you just have to assign the variable.

For exmaple, if you don't need it:
```python
_ = ax.bar_label(ax.containers[0], rotation=90)
```
or if you need it:
```python
bar_text_objects = ax.bar_label(ax.containers[0], rotation=90)
```

**Comment by malmans2** [comment]
BTW, there's a `padding` argument as well, and many others.
I've only added a minimal example, you can get more info in matplotlib documentation, or (`help(ax.bar_label)`)
