### ISSUE TITLE
LAI fapar and Soil moisture notebook 

### ISSUE THREAD

**Issue by Cri-dei** [bopen/c3s-eqc-toolbox-template#73]
### Notebook description

Percentage of missing values for each pixel map and histogram

### Notebook link or upload

[Soil moisture_ Completeness_rev.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/11884325/Soil.moisture_.Completeness_rev.zip)
[fAPAR_ LAI_Completeness(1).zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/11884327/fAPAR_.LAI_Completeness.1.zip)

### Anything else we need to know?

Hi Mattia,

I have to reopen this issue. I noticed your question in the closed issue about the fact if the barplot should have the percentage of NA on the world or respect to a specific Continent num of pixel. When I show the map of Europe, the histogram should tell me the total number of pixel with 100 percent missiing value respect to the total num of pixel for that specific continent, not respect the globe. Now it is respect the globe area?

ps. They set a limitation on the number of plots we can create so I am showing at the end just Europe.
Thanks!

### Environment

<details>

</details>

**Comment by malmans2** [comment]
I believe what you are doing is correct. The barplot and the map use the exact same dataarray as input.

I guess the comment you are referring to is this: https://github.com/bopen/c3s-eqc-toolbox-template/issues/34#issuecomment-1547500187

You asked how to change the x/y axis of the map, so I added this feature in the template (looks like you are not using it though). For example, if you plot Europe, then you change the limits of the map using `set_xlim`/`set_ylim`, the bars won't change. Therefore you are showing a subregion, but the bars are showing the statistics for the whole continent.
