### ISSUE TITLE
Value Error: non monotonic global indexes along dimension forecast_reference_time

### ISSUE THREAD

**Issue by sandrocalmanti** [bopen/c3s-eqc-toolbox-template#75]
### What happened?

I'm working with the dataset CERRA for an analysis of extremes.

I need to extract all time steps of the reanalysis from a selected region. 
With the code reported below I get the following situations:

1. Downloading a single time step, e.g.  `'time': ['00:00']`, using chunks of one year is OK.
2. Downloading all time steps using chunks of one year, requires too much space and quits with ERROR
3. Downloading all time steps using chunks of 1 day is OK until the end of the download and the quits with the ERROR message  `ValueError: Resulting object does not have monotonic global indexes along dimension forecast_reference_time`
4. Downloading all time steps with chunks of 1 time step is as in case 3.

For the moment can leave with 1. (sub-optimal) when working on temperature but for example to do an analysis on precipitation I would need all subdaily time step to compute the cumulated rainfall.

Looks like a bug in the way the chunks are combined and might be useful to fix. 

### Minimal Complete Verifiable Example

```Python
import xarray as xr
from c3s_eqc_automatic_quality_control import download, utils

lon_slice = slice(5, 15)
lat_slice = slice(43, 48)

def regionalise_and_dayofyear_reindex(ds, lon_slice, lat_slice):
    ds = utils.regionalise(ds, lon_slice=lon_slice, lat_slice=lat_slice)
    return ds

# Select time period
start = "1985"
stop = "1986"  # None: present

# Define request
request_cerra =    {
        'variable': '2m_temperature',
        'level_type': 'surface_or_atmosphere',
        'data_type': 'reanalysis',
        'product_type': 'analysis',
        'time': ['00:00', '03:00', '06:00', '09:00', '12:00', '15:00', '18:00', '21:00'],
#        'time': ['00:00'],
        'format': 'grib',
}
request_cerra = download.update_request_date(request_cerra, start=start, stop=stop)

ds_cerra = download.download_and_transform(
    "reanalysis-cerra-single-levels",
    request_cerra,
    chunks={"day": 1},
    transform_chunks=True,
    transform_func=regionalise_and_dayofyear_reindex,
    transform_func_kwargs={
        "lon_slice": lon_slice,
        "lat_slice": lat_slice,
    },
)
```

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Hi Sandro,

If you are trying to download daily data, you need to use this:
```python
chunks = {"year": 1, "month": 1, "day": 1}
```

If you just do `{"day": 1}` the chunks are a little weird: all years, all months, just one day. My guess it that it creates issues because months don't have the same number of days.

So recap:
```python
chunks = {"year": 1, "month": 1, "day": 1}  # daily
chunks = {"year": 1, "month": 1}  # monthly
chunks = {"year": 1}  # yearly
```

Maybe start small (e.g., `start = "1985-01", stop = "1985-01"`), and check if it works OK. It's January '85, so you expect 31 chunks.

BTW, if you want to try to speed up the requests, you can try to use the argument `n_jobs` of `download_and_transform`. For example, `n_jobs=2` will submit 2 concurrent requests rather than just 1. But be careful, especially if you use it on the VM when it's busy. Also, make sure you only use it when raw data have not been downloaded yet, it might slow you down otherwise. I.e., it's better to only use it the very first time you are analysing a dataset/period, when the data is downloaded from the CDS.

**Comment by malmans2** [comment]
I haven't tried `{"year": 1, "month": 1, "day": 1}` though. Let me know if it doesn't fix the problem.
In that case, you might have to explicitly specify the dimension for concatenation.

**Comment by sandrocalmanti** [comment]
Undesrtood.

I was assuming that `{"day": 1}` already implied the constraints on month and year. Or, better, that working with `{"day": 1}` would make the other keys worthless.

Anyway, it works with `{"year": 1, "month": 1}`

For some reasons the retrival of CERRA is significantly slower than ERA5 and it becomes even slower with chunks = {"year": 1, "month": 1, "day": 1}  

For now, working with small datasets seem sufficient for the analysis that I'm preparing.

**Comment by malmans2** [comment]
OK, unfortunately we don't have a priority user for EQC yet, so we download at the same speed/qos of regular users.
I'm closing this for now. I suggest to use the small subset of data do develop your analysis. I'll see if we can use some trick to speed up the download when I review the actual notebook.

Sometimes the best we can do is to populate the cache when the CDS is not very busy (e.g., weekends).
