### ISSUE TITLE
ERA5 on pressure levels, time concistency - Final check

### ISSUE THREAD

**Issue by sandrocalmanti** [bopen/c3s-eqc-toolbox-template#76]
### Notebook description

This is for a final check at the technical level.

Already checked in an initial state by @malmans2. I have then extended the notebook to multiple variables as requested by Hans Hershbach and added the reference to volcanic eruptions.

Seems to work fine.

### Notebook link or upload

[C3S_520_D5_3_4a_NB1_ERA5-time-consistency.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/11896969/C3S_520_D5_3_4a_NB1_ERA5-time-consistency.zip)

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Hi Sandro,

I glanced through it and it looks good and in line with the initial notebook you developed.

I'll be out of the office starting tomorrow until July 11th.
I'll give it a final review when I get back if that's OK.

**Comment by malmans2** [comment]
Hi @sandrocalmanti,

Sorry, I almost forgot about this. It was already in good shape though.
Here is the template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/era5_time_consistency.ipynb

It's very similar to #79

**Comment by malmans2** [comment]
Hi @sandrocalmanti,

Is this notebook OK? Can we close this issue?

**Comment by sandrocalmanti** [comment]
We can close this one
