### ISSUE TITLE
ERA5 on pressure levels, ENSO - final check

### ISSUE THREAD

**Issue by sandrocalmanti** [bopen/c3s-eqc-toolbox-template#79]
### Notebook description

This is for a final check of the notebook of ENSO.

The structure of the notebook and tools used in the analysis are the same as in the [notebook on time consistency](https://github.com/bopen/c3s-eqc-toolbox-template/issues/76) so  it should be mainly ok.

However, I'm submitting for review to make sure we follow all steps of the agreed workflow.

### Notebook link or upload

[C3S_520_D5_3_4b_NB2_ERA5_ENSO.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/12004040/C3S_520_D5_3_4b_NB2_ERA5_ENSO.zip)

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Hi @sandrocalmanti,

Looks good. Here is the template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/era5_nino.ipynb

The only suggestion is to chunk the `variable` parameter rather then writing a loop.
You can chunk any parameter in the request.

Other than that, I implemented minor changes to take advantage of pandas/xarray features.

As usual, please let me know if it's OK and we can close the issue.

**Comment by malmans2** [comment]
Hi @sandrocalmanti,

Is this notebook OK? Can we close this issue?

**Comment by sandrocalmanti** [comment]
We can close this one
