### ISSUE TITLE
CMIP6 and CORDEX notebooks revision

### ISSUE THREAD

**Issue by lsangelantoni** [bopen/c3s-eqc-toolbox-template#83]
### Describe the solution you'd like

Hi @malmans2, 

we received the revisions from the ECMWF experts panel regarding the climatology/bias and trend notebooks for CMIP6 and CORDEX. 

We would need to implement the following modifications to the current notebooks:

1. **Climatology and bias**

- [x] Instead of ‘model=ensemble’ in the plot titles we should specify CMIP6 or CORDEX depending on which dataset is choose under the ‘define parameters’ 
- [x] Mask out sea grid nodes. Best it would be having a switch allowing to lead analyses considering or not sea grid nodes. Masking out ocean grid points could also allow to save lot of computation time, if made at the beginning. A plausible approach could be to create model specific land-sea masks interpolating the ERA5 one on the model grid, mask the data over land and then compute the diagnostics. 
- [x] From the ‘compute and show statistics’ direct measures of the variable (mean, median, std) should be removed. We would only let verification statistics (i.e., corr, crmse, rmse).  

2. **Trend notebook**

- [x] The boxplot representing the distribution of model trend and ERA5 trend should be modified: the value for ERA5 should be separated from the model boxplot. Then, on the x-axis we should have two labels: ‘CMIP6 trend’ and ‘ERA5 trend’: the first with a boxplot, the second just the correspondent dot.
- [x] We need to keep fixed the hatching style without reverting between temperature and precipitation. We could keep hatching grid nodes with significant trends. Nevertheless, we can preserve the distinct way of deriving statistical significance between individual models and ensemble.
- [x] Use two different colormap for trends and trends bias.  

Please let us know if you need any further details and how you would like to proceed. 
The VM path to the submitted notebooks is the following: 

- `/data/wp4/sangelantoni_lorenzo/c3s-eqc-toolbox-template/notebooks/wp4/clima_and_bias_cordex_cmip6_regionalised.ipynb`
- `/data/wp4/sangelantoni_lorenzo/c3s-eqc-toolbox-template/notebooks/wp4/trend_cordex_cmip6.ipynb`

Best, 
Lorenzo

**Comment by malmans2** [comment]
OK. I should be able to apply all of them today, then I will probably re-run the notebook overnight invalidating the cache (just to make sure that everything is OK with the latest libraries).

**Comment by lsangelantoni** [comment]
To avoid download each the model-specific land-sea mask (LSM) we can:
1-To interpolate ERA5 LSM to the _i_ model grid (whichever model). This gives a sort of model-specific LSM. 
2-Mask out sea nodes values.
3-Compute the diagnostics.

**Comment by malmans2** [comment]
One more clarification: Do you want to apply masks before interpolating?
If not, we can just mask everything after interpolating to ERA5 grid, assuming that ERA5 land/sea mask does not change over time. In fact we can just mask the cached results as the time reductions are not performed by the cached functions.

I'm not so sure that interpolate lsm to model -> mask model -> interpolate model to ERA5 is much better than downloading and applying model-specific maps before interpolating.

**Comment by lsangelantoni** [comment]
'If not, we can just mask everything after interpolating to ERA5 grid' in this case we would let outside (not masked) diagnostics that do not required an interpolation to ERA5 such as climatology and trend that are computed only considering the original model grid. 
What we would like to avoid is to download each model LSM since not all the models have LSM available, and because it would be a never-ending  process considering the large number of CMIP6 and CORDEX models.

**Comment by lsangelantoni** [comment]
Also, I am seeing that in the VM an 'Unexpected exception formatting exception' warning occurs in 
'Set up and retrieval'  section of the 'clima_and_bias_cordex_cmip6_regionalised.ipynb'. This is followed by an error in 'Download data' section. The same notebook is rightly executed in local machine. Perhaps we need to run a conda-env-update.

**Comment by lsangelantoni** [comment]
'So do you need to allow masking also in the trend notebook?' Yes. 
'in the climatology/bias notebook (1 in your comment) everything is interpolated to ERA5 grid.' Yes, the preliminary interpolation of ERA5 LSM to the models grid does prevent to compute our diagnostics and then interpolating the model (masked) results to ERA5 (masked as well) to derive for instance climatology or trends bias. Maybe I missed something?

**Comment by malmans2** [comment]
Here is the new clima_and_bias template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp4/clima_and_bias_cordex_cmip6_regionalised.ipynb
Here is the notebook executed: https://gist.github.com/malmans2/1301b759e9b14eeadc080aac8296287c

It should address all points in the first section of your comment (Climatology and bias).
You'll see that I only masked once the cached data (so after interpolation). As I mentioned before, this only works well if we can assume that lsm does not change with time (I'm using the very first one available in 1940). I masked out `lsm <=0.5`, I'm not sure if that's the best choice, let me know if you want to change that.

**Comment by lsangelantoni** [comment]
Thanks, everything seems to be fine. Usually in climate models the ism is a fixed field, not time-varying, so with a good approximation I believe we could rely in ism stationarity also for the future simulations. I would stick with lsm<=0.5, it seems a good compromise.

For the masking in the trends notebook, I just suggested what I would have done if I wrote a script from scratch. Since we are dealing with already pretty structured notebook, just follow the approach that suits you best.

**Comment by malmans2** [comment]
>  The boxplot representing the distribution of model trend and ERA5 trend should be modified: the value for ERA5 should be separated from the model boxplot. Then, on the x-axis we should have two labels: ‘CMIP6 trend’ and ‘ERA5 trend’: the first with a boxplot, the second just the correspondent dot.

Is this OK?
![Screenshot 2023-07-19 at 11 47 18](https://github.com/bopen/c3s-eqc-toolbox-template/assets/22245117/47e82fb0-fd90-46d6-abb5-be0ee05e2a65)

> We need to keep fixed the hatching style without reverting between temperature and precipitation. We could keep hatching grid nodes with significant trends. Nevertheless, we can preserve the distinct way of deriving statistical significance between individual models and ensemble.

This is the relevant code. How do you want to change it? I guess you want to keep `is_signif_ratio_hatches_kwargs` as it is, but what about `p_hatches_kwargs`? Do you want all variables to have the same hatching as precipitation or temperature?
```python
p_hatches_kwargs = hatches_kwargs | {
    "levels": [0, 0.05, 1],
    "hatches": ["/", "" * 5][:: 1 if variable == "precipitation" else -1],
}
is_signif_ratio_hatches_kwargs = hatches_kwargs | {
    "levels": [1, 0.8, 0],
    "hatches": ["", "/" * 5][:: 1 if variable == "precipitation" else -1],
}
```

>  Use two different colormap for trends and trends bias.

Which colormaps do you want to use?

**Comment by lsangelantoni** [comment]
- Yes, the boxplot looks okay. For the CMIP6 boxplot, do the grey circles with a black frame represent outliers?
- 'I guess you want to keep is_signif_ratio_hatches_kwargs' Yes, we can preserve this approach for the intermodel agreement on statistically significant changes. Concerning the p_atches_kwargs, it also remains as is since the threshold of 0.05, the t-test alpha level serves only to discriminate if or not our p-value is low enough (to reject the null hypothesis). 
- 'Do you want all variables to have the same hatching as precipitation or temperature'. As for the temperature. 
- 'Which colourmaps do you want to use? For the trend PuOr and for the bias we can let the current color. As for bwr, PuOr should be in agreement with the principle of brownish (purplish) colours for drying/warming (wettening/cooling) trends.

**Comment by malmans2** [comment]
> 'I guess you want to keep is_signif_ratio_hatches_kwargs' Yes, we can preserve this approach for the intermodel agreement on statistically significant changes. Concerning the p_atches_kwargs, it also remains as is since the threshold of 0.05, the t-test alpha level serves only to discriminate if or not our p-value is low enough (to reject the null hypothesis).

> 'Do you want all variables to have the same hatching as precipitation or temperature'. As for the temperature.

I don't follow these two points. If `p_atches_kwargs` remains as is, nothing changes. If all variables should have the same hatching as temperature, `p_atches_kwargs` should become:
```python
p_hatches_kwargs = hatches_kwargs | {
    "levels": [0, 0.05, 1],
    "hatches": ["" * 5, "/"],
}
```

**Comment by lsangelantoni** [comment]
Yes, you are right, for the p_value it is correct as you wrote above.

**Comment by malmans2** [comment]
The code we had before was a little missleading, not sure why we had `"" * 5`, is the same as `""`.
Anyways, for now I'm using this for p-value:
```python
p_hatches_kwargs = hatches_kwargs | {"levels": [0, 0.05, 1], "hatches": ["", "/" * 5]}
```
Which means that hatches only appear on top of values > 0.005.

Anyways, as usual I'll send you the template with the code and figures, which is easier to review.

**Comment by malmans2** [comment]
@lsangelantoni here is the trend notebook executed on as small subset of data (2 years only): https://gist.github.com/malmans2/1e38725bcc1c19283ad7c6166cc92b30

If everything looks OK, let me know the combination of parameters for the full runs for both notebooks.
I will populate the cache overnight.

**Comment by malmans2** [comment]
Which interpolation would you like to use for interpolating lsm? nearest or bilinear?

**Comment by lsangelantoni** [comment]
Everything looks good, 

we would need running annual temperature and precipitation for CMIP6 and CORDEX climate/bias and trends as notebook prototypes. 

I would also like to run JJA/DJF as ancillary information linked from the annual-based notebook but we would get a too large number of notebooks, so seasonal analyses are not a priority at the moment.   

bilinear interp is totally fine also for the lsm.

**Comment by malmans2** [comment]
Hi @lsangelantoni,

All combinations of `collection_id`, `variable`, `precipitation` are now cached for this template: [clima_and_bias_cordex_cmip6_regionalised](https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp4/clima_and_bias_cordex_cmip6_regionalised.ipynb)
Let me know if everything is OK. I've changed a little the caching strategy of seasons to avoid memory issues on the VM.

For the trend template, the scripts are still running and should be ready tomorrow. At the moment, only precipitation using CORDEX is cached. I'll let you know when the other combinations are available. Please do not try to run the other combinations before they're cached.

**Comment by lsangelantoni** [comment]
Great, thanks!

**Comment by malmans2** [comment]
All CORDEX trends are now cached (temperature/precipitation for all timeseries).
CMIP6 trends are being computed now. I'll let you know when it's done.

Here is the template: [trend_cordex_cmip6](https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp4/trend_cordex_cmip6.ipynb)

**Comment by malmans2** [comment]
All CMIP6 temperature notebooks are cached.

Only CMIP6 precipitations are missing (they're being computed right now)

**Comment by malmans2** [comment]
All set. Let me know if everything is OK.

**Comment by lsangelantoni** [comment]
Ok, I am running all the notebooks, I let you know in case of any issues. 

Is there a way to run the notebook from the linux shell without opening the browser, and sending the output (the notebook with maps and plot displayed) e.g., in a .HTML file? 

Thanks.

**Comment by malmans2** [comment]
```
jupyter nbconvert --to html --execute notebook.ipynb
```

**Comment by lsangelantoni** [comment]
Hi @malmans2, 

I have noticed that in the clima_and_bias_cordex_cmip6_regionalised notebook for the annual temperature bias, we have the white color bar interval not centred around the zero anymore. It happens only for the CMIP6 ensemble and models t2m biases on an annual basis since the colorbar is extended only for the upper limit.

**Comment by malmans2** [comment]
Should be fixed now: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp4/clima_and_bias_cordex_cmip6_regionalised.ipynb

BTW, I noticed that when using "annual" the very 1st year of yearly chunked data is being invalidated (there's a warning raised by our caching software). I think I know what's happening: the result is an empty dataset (the very first year is only needed for computing DJF), and there's a bug I need to fix in our caching software.

Don't worry too much about it tho, nothing is being re-computed. I'll let you know when it's fixed!

**Comment by malmans2** [comment]
OK, that issue should be fixed. Let me know if you see warnings about checksum mismatch.

**Comment by lsangelantoni** [comment]
Hi @malmans2, 

In the Taylor diagram, we plot all the models but one (for both GCMs and RCMs). Moreover, for CMIP6 precipitation the RMSD value (and label) does not display in the plot. Regarding this latter point, we are in the realm of graphical details so if it comes up to be too complicated to dig into the Taylor diagram code we can justify this issue.

**Comment by malmans2** [comment]
Should be fixed. I'm not familiar with the library used for Taylor Diagrams, but it looks like ERA5 must be the first item.

For the latter, now I'm rounding std and rms contours to the second decimal. Looks good for precipitation as well. If it's not that easy to specify general contours (we previously rounded to integers for another version of the plots), it's probably better if you tune those details yourself before submitting each notebook.

**Comment by malmans2** [comment]
mmm, I might have to install a plugin. I'll try when no one is using the VM.

In the meantime, you should be able to convert from terminal:
```
jupyter nbconvert --to html --execute notebook.ipynb
```
(remove `--execute` if you don't want to execute the notebook)

**Comment by lsangelantoni** [comment]
Hi @malmans2, 

I am wondering why (only) in the precipitation trend notebook (CMIP6 and CORDEX) we have no hatching in the ensemble mean trend meaning a significant trend in all the grid nodes. If we look at the individual members they produce mainly not significant trends for the precipitation, as expected. It is strange having significant trends in an ensemble mean generated by models showing mainly not significant trends especially considering that we need 80% of inter-model agreement on the significance of the trend.

**Comment by malmans2** [comment]
Are you talking about the plot of `is_signif_ratio`?
It goes to this discussion we had the other day, we are flipping hatches for precipitation and temperature: https://github.com/bopen/c3s-eqc-toolbox-template/issues/83#issuecomment-1641811585

Also, checking this I realised that matplotlib needs sorted levels, so the temperature plots might not be correct.

Anyways, do you want hatches to overlap regions where <20% of the models are significant? Does this apply to both temperature and precipiation?

**Comment by lsangelantoni** [comment]
Yes, exactly! 
Now we go for a homogeneous approach for the two variables, namely hatches over not significant grid nodes that for the ensemble translates to what you just mentioned.

**Comment by malmans2** [comment]
OK, makes sense. I misunderstood your original comment.
Should be fixed now: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp4/trend_cordex_cmip6.ipynb

**Comment by lsangelantoni** [comment]
What I cannot understand is why for the temperature the previous  '"levels": [1, 0.8, 0]' worked hatching grid nodes with <80% of models with significant trends.

**Comment by lsangelantoni** [comment]
ah, the "hatches" variable had an inverted order of elements.

**Comment by malmans2** [comment]
I'm not sure how matplotlib handles it, but it looks to me that it does something weird when levels are not sorted.
The plots now should be correct for both temperature and precipitation.

**Comment by lsangelantoni** [comment]
yes, I agree.
