### ISSUE TITLE
Downloading taking too long, subsetting raster

### ISSUE THREAD

**Issue by akankshabalha** [bopen/c3s-eqc-toolbox-template#84]
### Notebook description

 #Define Variables
year_start = 2014
year_stop = 2019

#Define request
collection_id = "satellite-albedo"
request = {
    "format": "zip",
    "variable": "albb_bh",
    "satellite": "proba",
    "sensor": "vgt",
    "product_version": "v2",
    "horizontal_resolution": "1km",
    "year": [str(year) for year in range(year_start, year_stop + 1)],
    "month": [f"{month:02d}" for month in range(1, 12 + 1)],
    "nominal_day": [10, 20],
    "area": [15, 75, 10, 80],
}

#Download and transform
ds_mean = download.download_and_transform(
    collection_id,
    request,
    transform_func=diagnostics.spatial_weighted_mean,
    split_all=True,
    drop_variables=["crs"]
)

With the above code, it is taking a lot of time for me to download the data despite running for more than 8 hours (only 21% is done). How can I speed it up?

Moreover, on a sample data, I am able to create time-series. But I want to download data for a more larger area (I am concerned with the download speed as mentioned above) of same time-period (for say), create a spatial-averaged raster of data. Then, based on that raster, I want to subset 2 or 3 regions. I will do further processing on those regions. Is it possible to perform this? Could you please help.

### Environment

<details>

</details>

**Comment by malmans2** [comment]
It's not the code that is slow, but the CDS queue. As discussed during the meetings, you should use a small subsample (both in time and space) to develop your analysis. When your code is ready and has been reviewed by us, we will execute the notebook for the whole time period.

To speed it up, we usually pre-populate the cache when the CDS is less busy (weekend and/or overnight), and we use concurrent requests (`n_jobs` arguments of `download_and_transform`).
