### ISSUE TITLE
Lake water level temperature Notebook revision 2

### ISSUE THREAD

**Issue by Cri-dei** [bopen/c3s-eqc-toolbox-template#85]
### Notebook description

Hi Mattia,

I received the second revision for this notebook. I have to modify the notebook in this way:

1. In the plot of projected map, delete the statistics of Lake ID  on the right.
2. Select with the ID of the lake the biggest one: Victoria, Malawi and Tanganica and showing the boxplot for these three lakes (so selecting it on the base of the ID)

Currently I am trying to run it again, but I have this error:
![image](https://github.com/bopen/c3s-eqc-toolbox-template/assets/56677048/fe20d6c0-37bc-4f96-8f05-10a244739a10)

Thank you so much

### Notebook link or upload

[lake_water_temperature_outlier_detection_cleaned(2).zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/12094853/lake_water_temperature_outlier_detection_cleaned.2.zip)

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Hi,

It's the same issue of permissions you had before: https://github.com/bopen/c3s-eqc-toolbox-template/issues/19#issuecomment-1457971488

**Comment by Cri-dei** [comment]
Hi Mattia,

I have the cdsapirc at the start, and I restarted the kernel but there is still the issue.
Last time I solved it adding that cdsapirc I think.

![image](https://github.com/bopen/c3s-eqc-toolbox-template/assets/56677048/398cd85e-410f-4aa6-b497-c1da9c053a17)

**Comment by malmans2** [comment]
If you are using your cdsapirc, then it means that you didn't agree to the term and conditions.
You need to do it on the CDS website at the page of the dataset that you are using (you need to log into the CDS)

**Comment by Cri-dei** [comment]
Okay I managed, thank you.
I am checking the code, here we download and process directly the data to have the mean over the area of African Lakes.

The ID lakes are: 3 for Lake Victoria, 7 for Lake Tanganuika and 10 for Lake Malawi. 

```
#Lake Victoria
ID1=da_lakeid.sel(latitude=-0.95,longitude=32.8, method='nearest').values
#Lake Tanganuika
ID2=da_lakeid.sel(latitude=-6.7,longitude=30.1, method='nearest').values
#Lake Malawi
ID3=da_lakeid.sel(latitude=-12.2,longitude=34.4, `method='nearest').values`
```
I don't know what is the best way to modify the code. Maybe computing directly in the download section the mean of temperature of water level for the pixels that have the ID ? like pixel.where(da_lakeid.values==ID1) ? And keep also the median over the all area, so we don't cancel that code that is written now but we just add the boxplot or timeseries for the specific lakes?

**Comment by malmans2** [comment]
Hi @Cri-dei,

Do you need to produce one plot for each lake or a single plot including all lakes?
I.e., for the timeseries and boxplot, do you need 3 lines/boxes or a single one including only data from the 3 major lakes?

**Comment by Cri-dei** [comment]
For the boxplot I think it can be fine having them in the same plot.
For the timeseries it depends on the values, if it fits in the same plot maybe we can put it together.

In the revision they asked just for the boxplot of the three lakes, not the time series, so if they not fit in the same plot I think we can just show the boxplot.

**Comment by malmans2** [comment]
Sorry, I didn't get it, there's no fitting problems.

Let's start with the timeseries. Which line(s) do you want to plot? Options are:
1. The same line plotted before: Spatial weighted mean of all lakes
2. One single line, but instead of plotting the spatial weighted mean of all lakes, plot the spatial weighted mean of the 3 major lakes
3. Three lines, each one corresponding to the spatial weighted mean of the tree major lakes

**Comment by Cri-dei** [comment]
Option 3, three lines one for each lake.
Boxplot: the three boxplot in the same plot.

**Comment by malmans2** [comment]
Got it

**Comment by malmans2** [comment]
Hi @Cri-dei,

I revised the template. Here is the template executed on a small time period: https://gist.github.com/malmans2/b5c31013af49f12ea12b19a20741350c

Please have a look and let me know if everything looks OK.
Unfortunately, we need to re-compute everything. If everything looks OK, I will run it for the whole time period and I will let you know when everything is cached.

**Comment by Cri-dei** [comment]
Hi Mattia,
Thanks so much!

I just have problem to save it as html:
![image](https://github.com/bopen/c3s-eqc-toolbox-template/assets/56677048/60f2d2fa-f116-4b43-a7e3-e995c396bc76)

**Comment by malmans2** [comment]
mmm, I might have to install a plugin. I'll try when no one is using the VM.

In the meantime, you should be able to convert from terminal:
```
jupyter nbconvert --to html --execute notebook.ipynb
```
(remove `--execute` if you don't want to execute the notebook)

**Comment by Cri-dei** [comment]
Okay I am saving it from the machine.
Thanks, now it should be all fine. I will resubmit again this corrected version, for me it is closed this issue now but I don't know if they will ask again some modification and we have to open it again.

**Comment by Cri-dei** [comment]
Hi Mattia, I received some feedback on this notebook. They asked me to include the quality flags and also told me to simplify the code since like this is not easy to use (they said is not user-friendly to compute the avarage directly on the download phase).  I am changing the case study to this boundary box since the data series is better: 
lon_slice = slice(-92.10, -84.80)
lat_slice = slice(46.30, 49.00)

I am trying to change the code in this way:
- Download for the lat and lon slice the original data series (not directly the mean)
- Select the data for which the quality flags are more than 4 or 5 (I was using: 
 ' filtered_temperature = ds['lake_surface_water_temperature'].where(ds['quality_level'] > 3)')
- Comparing the data series with and without quality flag selection

The problem is that I do not manage to download the original data series without doing directly the weighted mean processing and is crashing for some reasons.

Can you help me to do it? Or at least to have a version for which I can do this type of analysis?
Thank you

**Comment by malmans2** [comment]
Hi @Cri-dei,

OK, I think I understand what you need and I'll take a look either later today or tomorrow.
Can I start from [this template](https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/lake_water_temperature_outlier_detection.ipynb) or did your notebook diverge significantly from the template? If the latter, please share here the latest version.

> They asked me to include the quality flags and also told me to simplify the code since like this is not easy to use (they said is not user-friendly to compute the avarage directly on the download phase).

Just one comment about this. We do it so the transformed data is cached. If the computation is quick, that's not a problem and we can easily do it. Otherwise, you would have to wait a long time every time you execute the notebook and we would stress a lot the VM to re-do useless computations. Anyways, if the code is quick and the original data is small, we can easily address the reviewer's comment.

**Comment by Cri-dei** [comment]
Hi Mattia, the template is that one yes. It should be just some little modifications of that code. For the transformation of data I agree and for me the code was very efficient in that way. I am just reporting. Not sure if it is just a comment for this use case or in general or if then they will require a different structure. Thank you again!

**Comment by malmans2** [comment]
Hi @Cri-dei,

I'm working on this. The data is too large to handle as the reviewer requested, so I suggest an intermediate solution. We can apply the cutout during data download, and perform any additional transformations (such as weighted mean) afterward. Hopefully, they'll be happy with this solution.

I'll let you know when the new template is ready.

**Comment by malmans2** [comment]
Hi @Cri-dei,

Please try the latest template and let me know: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/lake_water_temperature_outlier_detection.ipynb

**Comment by malmans2** [comment]
Correct! Closing this.
