### ISSUE TITLE
Unable to plot Spatial time weighted raster plot of albedo

### ISSUE THREAD

**Issue by akankshabalha** [bopen/c3s-eqc-toolbox-template#86]
### Notebook description

Hi Mattia,

I want to create a spatial time average raster, plot it and then I want to create a spatial subset of it. (Rest of the analysis needs to be done on subset. Last step being done first, I am able to do analysis successfully on subset using jupyter. But to provide complete jupyter notebook, I need to carry out subsetting of raster also.) Hence, I have a taken a small data sample. While trying to plot it, it is giving me the following error. Is it because I have taken very small size of area? If I consider bigger size, then it is taking a lot of time and sometimes gives me error too. Kindly advise how to proceed further

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[48], line 24
     22 ax = plt.axes(projection=ccrs.PlateCarree())
     23 ax.coastlines()
---> 24 im = ax.pcolormesh(lon_flat, lat_flat, data_flat, transform=ccrs.PlateCarree())
     25 plt.colorbar(im, ax=ax, label="Surface Albedo")
     26 plt.title("Spatial Time Average Raster Plot")

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py:318, in _add_transform.<locals>.wrapper(self, *args, **kwargs)
    313     raise ValueError(f'Invalid transform: Spherical {func.__name__} '
    314                      'is not supported - consider using '
    315                      'PlateCarree/RotatedPole.')
    317 kwargs['transform'] = transform
--> 318 return func(self, *args, **kwargs)

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py:1784, in GeoAxes.pcolormesh(self, *args, **kwargs)
   1773 """
   1774 Add the "transform" keyword to :func:`~matplotlib.pyplot.pcolormesh`.
   1775 
   (...)
   1780 
   1781 """
   1782 # Add in an argument checker to handle Matplotlib's potential
   1783 # interpolation when coordinate wraps are involved
-> 1784 args, kwargs = self._wrap_args(*args, **kwargs)
   1785 result = super().pcolormesh(*args, **kwargs)
   1786 # Wrap the quadrilaterals if necessary

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py:1813, in GeoAxes._wrap_args(self, *args, **kwargs)
   1811 X = np.asanyarray(args[0])
   1812 Y = np.asanyarray(args[1])
-> 1813 nrows, ncols = np.asanyarray(args[2]).shape
   1814 Nx = X.shape[-1]
   1815 Ny = Y.shape[0]

ValueError: not enough values to unpack (expected 2, got 1)

[SpatialTimeAvgRaster.txt](https://github.com/bopen/c3s-eqc-toolbox-template/files/12105678/SpatialTimeAvgRaster.txt)

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Hi,

I'm not sure I'm understanding what you are trying to do.
You compute and cache spatial mean, but then you are trying to plot a map.
Spatial means remove the lat/lot dimensions, and therefore are timeseries.

You can just do this to plot it:
```python
ds_mean1["AL_BH_BB"].plot()
```

**Comment by akankshabalha** [comment]
I want a spatial plot of albedo like the LST plot (attached)
![LST](https://github.com/bopen/c3s-eqc-toolbox-template/assets/26113845/837c9e33-0c75-4039-94dc-2f2091e7e4d6)

**Comment by malmans2** [comment]
You can not plot a map from a spatial reductions, that's a line.
How did you make that plot? I don't think that's the result of a spatial reduction.

To get a 2D array (lat, lon) from 3D data (time, lat, lon), you'd have to apply some kind of time reduction (e.g., mean, std, median, ...)

**Comment by akankshabalha** [comment]
This spatial plot is of ERA5 LST. I made this using following code

ds = download.download_and_transform(collection_id, request, chunks={"year": 1})
da = ds["t2m"]
with xr.set_options(keep_attrs=True):
    da -= 273.15
da.attrs["units"] = "°C"

 da_time_mean = diagnostics.time_weighted_mean(da)
_ = plot.projected_map(da_time_mean.where(da_time_mean), projection=ccrs.PlateCarree())

**Comment by akankshabalha** [comment]
In t2m, 'ds' has lat long. But in case of albedo, ds_mean1 does not have lat long, so I defined latitude_range and longitude range as given in the code

**Comment by akankshabalha** [comment]
But when I applied the same code as ERA5 on albedo, it gave me the error that it doesn't have lat long dimension

**Comment by malmans2** [comment]
Please send me the code.
That's not the code you sent in the first comment, where you apply a spatial mean.

**Comment by akankshabalha** [comment]
Here is the code:

import os
os.environ["CDSAPI_RC"] = os.path.expanduser("~/Balha_Akanksha/.cdsapirc")
import warnings
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import xarray as xr
import cartopy.crs as ccrs
from c3s_eqc_automatic_quality_control import diagnostics, download, plot,utils
warnings.filterwarnings("ignore")

#Define request
collection_id = "satellite-albedo"
request = {
    "format": "zip",
    "variable": "albb_bh",
    "satellite": "proba",
    "sensor": "vgt",
    "product_version": "v2",
    "horizontal_resolution": "1km",
    "year": "2014",
    "month": ["01", "02"],
    "nominal_day": "10",
    "area": [13.16, 77.46, 12.83, 77.78],
}

ds = download.download_and_transform(collection_id, request, chunks={"year": 1})

ds_time_mean = diagnostics.time_weighted_mean(ds)
_ = plot.projected_map(ds_time_mean.where(ds_time_mean), projection=ccrs.PlateCarree())

**Comment by akankshabalha** [comment]
I think there is some issue with this file. So, I choose only Feb and Mar months, I again faced the same issue with Feb file. So I chose only March and here is the error. I am unable to understand it. Could you please help to resolve this:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[14], line 2
      1 ds = download.download_and_transform(collection_id, request, chunks={"year": 1})
----> 2 ds_time_mean = diagnostics.time_weighted_mean(ds)
      3 _ = plot.projected_map(ds_time_mean.where(ds_time_mean), projection=ccrs.PlateCarree())

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/c3s_eqc_automatic_quality_control/diagnostics.py:169, in time_weighted_mean(obj, time_name, weights, **kwargs)
    143 def time_weighted_mean(
    144     obj: xr.DataArray | xr.Dataset,
    145     time_name: Hashable | None = None,
    146     weights: xr.DataArray | bool = True,
    147     **kwargs: Any,
    148 ) -> xr.DataArray | xr.Dataset:
    149     """
    150     Calculate time weighted mean.
    151 
   (...)
    167         Reduced object
    168     """
--> 169     return _time_weighted.TimeWeighted(obj, time_name, weights).reduce(
    170         "mean", None, **kwargs
    171     )

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/c3s_eqc_automatic_quality_control/utils.py:31, in keep_attrs.<locals>.wrapper(*args, **kwargs)
     28 @functools.wraps(func)
     29 def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
     30     with xr.set_options(keep_attrs=True):  # type: ignore[no-untyped-call]
---> 31         return func(*args, **kwargs)

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/c3s_eqc_automatic_quality_control/_time_weighted.py:73, in TimeWeighted.reduce(self, func_name, group, **kwargs)
     71 if group is not None:
     72     return self.groupby_reduce(func_name, group, **kwargs)
---> 73 obj: xr.DataArray | xr.Dataset = getattr(self.obj_weighted, func_name)(**kwargs)
     74 return obj

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/weighted.py:486, in Weighted.mean(self, dim, skipna, keep_attrs)
    480 def mean(
    481     self,
    482     dim: Dims = None,
    483     skipna: bool | None = None,
    484     keep_attrs: bool | None = None,
    485 ) -> T_Xarray:
--> 486     return self._implementation(
    487         self._weighted_mean, dim=dim, skipna=skipna, keep_attrs=keep_attrs
    488     )

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/weighted.py:543, in DatasetWeighted._implementation(self, func, dim, **kwargs)
    540 def _implementation(self, func, dim, **kwargs) -> Dataset:
    541     self._check_dim(dim)
--> 543     return self.obj.map(func, dim=dim, **kwargs)

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/dataset.py:6437, in Dataset.map(self, func, keep_attrs, args, **kwargs)
   6435 if keep_attrs is None:
   6436     keep_attrs = _get_keep_attrs(default=False)
-> 6437 variables = {
   6438     k: maybe_wrap_array(v, func(v, *args, **kwargs))
   6439     for k, v in self.data_vars.items()
   6440 }
   6441 if keep_attrs:
   6442     for k, v in variables.items():

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/dataset.py:6438, in <dictcomp>(.0)
   6435 if keep_attrs is None:
   6436     keep_attrs = _get_keep_attrs(default=False)
   6437 variables = {
-> 6438     k: maybe_wrap_array(v, func(v, *args, **kwargs))
   6439     for k, v in self.data_vars.items()
   6440 }
   6441 if keep_attrs:
   6442     for k, v in variables.items():

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/weighted.py:284, in Weighted._weighted_mean(self, da, dim, skipna)
    276 def _weighted_mean(
    277     self,
    278     da: DataArray,
    279     dim: Dims = None,
    280     skipna: bool | None = None,
    281 ) -> DataArray:
    282     """Reduce a DataArray by a weighted ``mean`` along some dimension(s)."""
--> 284     weighted_sum = self._weighted_sum(da, dim=dim, skipna=skipna)
    286     sum_of_weights = self._sum_of_weights(da, dim=dim)
    288     return weighted_sum / sum_of_weights

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/weighted.py:274, in Weighted._weighted_sum(self, da, dim, skipna)
    266 def _weighted_sum(
    267     self,
    268     da: DataArray,
    269     dim: Dims = None,
    270     skipna: bool | None = None,
    271 ) -> DataArray:
    272     """Reduce a DataArray by a weighted ``sum`` along some dimension(s)."""
--> 274     return self._reduce(da, self.weights, dim=dim, skipna=skipna)

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/weighted.py:229, in Weighted._reduce(da, weights, dim, skipna)
    225     da = da.fillna(0.0)
    227 # `dot` does not broadcast arrays, so this avoids creating a large
    228 # DataArray (if `weights` has additional dimensions)
--> 229 return dot(da, weights, dims=dim)

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/computation.py:1762, in dot(dims, *arrays, **kwargs)
   1759 # subscripts should be passed to np.einsum as arg, not as kwargs. We need
   1760 # to construct a partial function for apply_ufunc to work.
   1761 func = functools.partial(duck_array_ops.einsum, subscripts, **kwargs)
-> 1762 result = apply_ufunc(
   1763     func,
   1764     *arrays,
   1765     input_core_dims=input_core_dims,
   1766     output_core_dims=output_core_dims,
   1767     join=join,
   1768     dask="allowed",
   1769 )
   1770 return result.transpose(*all_dims, missing_dims="ignore")

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/computation.py:1197, in apply_ufunc(func, input_core_dims, output_core_dims, exclude_dims, vectorize, join, dataset_join, dataset_fill_value, keep_attrs, kwargs, dask, output_dtypes, output_sizes, meta, dask_gufunc_kwargs, *args)
   1195 # feed DataArray apply_variable_ufunc through apply_dataarray_vfunc
   1196 elif any(isinstance(a, DataArray) for a in args):
-> 1197     return apply_dataarray_vfunc(
   1198         variables_vfunc,
   1199         *args,
   1200         signature=signature,
   1201         join=join,
   1202         exclude_dims=exclude_dims,
   1203         keep_attrs=keep_attrs,
   1204     )
   1205 # feed Variables directly through apply_variable_ufunc
   1206 elif any(isinstance(a, Variable) for a in args):

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/computation.py:304, in apply_dataarray_vfunc(func, signature, join, exclude_dims, keep_attrs, *args)
    299 result_coords, result_indexes = build_output_coords_and_indexes(
    300     args, signature, exclude_dims, combine_attrs=keep_attrs
    301 )
    303 data_vars = [getattr(a, "variable", a) for a in args]
--> 304 result_var = func(*data_vars)
    306 out: tuple[DataArray, ...] | DataArray
    307 if signature.num_outputs > 1:

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/computation.py:761, in apply_variable_ufunc(func, signature, exclude_dims, dask, output_dtypes, vectorize, keep_attrs, dask_gufunc_kwargs, *args)
    756     if vectorize:
    757         func = _vectorize(
    758             func, signature, output_dtypes=output_dtypes, exclude_dims=exclude_dims
    759         )
--> 761 result_data = func(*input_data)
    763 if signature.num_outputs == 1:
    764     result_data = (result_data,)

File <__array_function__ internals>:200, in einsum(*args, **kwargs)

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/numpy/core/einsumfunc.py:1371, in einsum(out, optimize, *operands, **kwargs)
   1369     if specified_out:
   1370         kwargs['out'] = out
-> 1371     return c_einsum(*operands, **kwargs)
   1373 # Check the kwargs to avoid a more cryptic error later, without having to
   1374 # repeat default values here
   1375 valid_einsum_kwargs = ['dtype', 'order', 'casting']

TypeError: invalid data type for einsum

**Comment by malmans2** [comment]
Please use proper formatting if you attach code or traceback. It's quite hard to read your messages:
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by malmans2** [comment]
Here is a snippet very similar to the one I sent you the other day:
```python
from c3s_eqc_automatic_quality_control import diagnostics, download

#Define request
collection_id = "satellite-albedo"
request = {
    "format": "zip",
    "variable": "albb_bh",
    "satellite": "proba",
    "sensor": "vgt",
    "product_version": "v2",
    "horizontal_resolution": "1km",
    "year": "2014",
    "month": ["01", "02"],
    "nominal_day": "10",
    "area": [15, 75, 10, 80],
}

# Download and transform
ds_mean = download.download_and_transform(
    collection_id,
    request,
    transform_func=diagnostics.time_weighted_mean,
    transform_chunks=False,
    split_all=True,
    drop_variables=["crs"]
)
```

This is what changed compared to the spatial weighted mean snipped:
1. I added the month of February
2. The transform func is now time_weighted_mean
3. `transform_chunks=False` beacuse both the reduction and the chunks are along the time dimension

**Comment by akankshabalha** [comment]
It has returned an error:

```
2023-07-20 15:18:40,280 INFO Welcome to the CDS
2023-07-20 15:18:40,281 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/satellite-albedo
2023-07-20 15:18:40,429 INFO Request is queued
2023-07-20 15:18:41,437 INFO Request is running
2023-07-20 15:46:59,835 INFO Request is completed
2023-07-20 15:46:59,837 INFO Downloading https://download-0008-clone.copernicus-climate.eu/cache-compute-0008/cache/data4/dataset-satellite-albedo-f97fb73b-e98b-401a-b622-52e4e505c989.zip to dataset-satellite-albedo-f97fb73b-e98b-401a-b622-52e4e505c989.zip (3.6M)
2023-07-20 15:47:00,012 INFO Download rate 20.9M/s  
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[23], line 2
      1 ds = download.download_and_transform(collection_id, request, chunks={"year": 1})
----> 2 ds_time_mean = diagnostics.time_weighted_mean(ds)
      3 _ = plot.projected_map(ds_time_mean.where(ds_time_mean), projection=ccrs.PlateCarree())

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/c3s_eqc_automatic_quality_control/diagnostics.py:169, in time_weighted_mean(obj, time_name, weights, **kwargs)
    143 def time_weighted_mean(
    144     obj: xr.DataArray | xr.Dataset,
    145     time_name: Hashable | None = None,
    146     weights: xr.DataArray | bool = True,
    147     **kwargs: Any,
    148 ) -> xr.DataArray | xr.Dataset:
    149     """
    150     Calculate time weighted mean.
    151 
   (...)
    167         Reduced object
    168     """
--> 169     return _time_weighted.TimeWeighted(obj, time_name, weights).reduce(
    170         "mean", None, **kwargs
    171     )

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/c3s_eqc_automatic_quality_control/utils.py:31, in keep_attrs.<locals>.wrapper(*args, **kwargs)
     28 @functools.wraps(func)
     29 def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
     30     with xr.set_options(keep_attrs=True):  # type: ignore[no-untyped-call]
---> 31         return func(*args, **kwargs)

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/c3s_eqc_automatic_quality_control/_time_weighted.py:73, in TimeWeighted.reduce(self, func_name, group, **kwargs)
     71 if group is not None:
     72     return self.groupby_reduce(func_name, group, **kwargs)
---> 73 obj: xr.DataArray | xr.Dataset = getattr(self.obj_weighted, func_name)(**kwargs)
     74 return obj

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/weighted.py:486, in Weighted.mean(self, dim, skipna, keep_attrs)
    480 def mean(
    481     self,
    482     dim: Dims = None,
    483     skipna: bool | None = None,
    484     keep_attrs: bool | None = None,
    485 ) -> T_Xarray:
--> 486     return self._implementation(
    487         self._weighted_mean, dim=dim, skipna=skipna, keep_attrs=keep_attrs
    488     )

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/weighted.py:543, in DatasetWeighted._implementation(self, func, dim, **kwargs)
    540 def _implementation(self, func, dim, **kwargs) -> Dataset:
    541     self._check_dim(dim)
--> 543     return self.obj.map(func, dim=dim, **kwargs)

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/dataset.py:6437, in Dataset.map(self, func, keep_attrs, args, **kwargs)
   6435 if keep_attrs is None:
   6436     keep_attrs = _get_keep_attrs(default=False)
-> 6437 variables = {
   6438     k: maybe_wrap_array(v, func(v, *args, **kwargs))
   6439     for k, v in self.data_vars.items()
   6440 }
   6441 if keep_attrs:
   6442     for k, v in variables.items():

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/dataset.py:6438, in <dictcomp>(.0)
   6435 if keep_attrs is None:
   6436     keep_attrs = _get_keep_attrs(default=False)
   6437 variables = {
-> 6438     k: maybe_wrap_array(v, func(v, *args, **kwargs))
   6439     for k, v in self.data_vars.items()
   6440 }
   6441 if keep_attrs:
   6442     for k, v in variables.items():

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/weighted.py:284, in Weighted._weighted_mean(self, da, dim, skipna)
    276 def _weighted_mean(
    277     self,
    278     da: DataArray,
    279     dim: Dims = None,
    280     skipna: bool | None = None,
    281 ) -> DataArray:
    282     """Reduce a DataArray by a weighted ``mean`` along some dimension(s)."""
--> 284     weighted_sum = self._weighted_sum(da, dim=dim, skipna=skipna)
    286     sum_of_weights = self._sum_of_weights(da, dim=dim)
    288     return weighted_sum / sum_of_weights

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/weighted.py:274, in Weighted._weighted_sum(self, da, dim, skipna)
    266 def _weighted_sum(
    267     self,
    268     da: DataArray,
    269     dim: Dims = None,
    270     skipna: bool | None = None,
    271 ) -> DataArray:
    272     """Reduce a DataArray by a weighted ``sum`` along some dimension(s)."""
--> 274     return self._reduce(da, self.weights, dim=dim, skipna=skipna)

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/weighted.py:229, in Weighted._reduce(da, weights, dim, skipna)
    225     da = da.fillna(0.0)
    227 # `dot` does not broadcast arrays, so this avoids creating a large
    228 # DataArray (if `weights` has additional dimensions)
--> 229 return dot(da, weights, dims=dim)

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/computation.py:1762, in dot(dims, *arrays, **kwargs)
   1759 # subscripts should be passed to np.einsum as arg, not as kwargs. We need
   1760 # to construct a partial function for apply_ufunc to work.
   1761 func = functools.partial(duck_array_ops.einsum, subscripts, **kwargs)
-> 1762 result = apply_ufunc(
   1763     func,
   1764     *arrays,
   1765     input_core_dims=input_core_dims,
   1766     output_core_dims=output_core_dims,
   1767     join=join,
   1768     dask="allowed",
   1769 )
   1770 return result.transpose(*all_dims, missing_dims="ignore")

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/computation.py:1197, in apply_ufunc(func, input_core_dims, output_core_dims, exclude_dims, vectorize, join, dataset_join, dataset_fill_value, keep_attrs, kwargs, dask, output_dtypes, output_sizes, meta, dask_gufunc_kwargs, *args)
   1195 # feed DataArray apply_variable_ufunc through apply_dataarray_vfunc
   1196 elif any(isinstance(a, DataArray) for a in args):
-> 1197     return apply_dataarray_vfunc(
   1198         variables_vfunc,
   1199         *args,
   1200         signature=signature,
   1201         join=join,
   1202         exclude_dims=exclude_dims,
   1203         keep_attrs=keep_attrs,
   1204     )
   1205 # feed Variables directly through apply_variable_ufunc
   1206 elif any(isinstance(a, Variable) for a in args):

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/computation.py:304, in apply_dataarray_vfunc(func, signature, join, exclude_dims, keep_attrs, *args)
    299 result_coords, result_indexes = build_output_coords_and_indexes(
    300     args, signature, exclude_dims, combine_attrs=keep_attrs
    301 )
    303 data_vars = [getattr(a, "variable", a) for a in args]
--> 304 result_var = func(*data_vars)
    306 out: tuple[DataArray, ...] | DataArray
    307 if signature.num_outputs > 1:

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/xarray/core/computation.py:761, in apply_variable_ufunc(func, signature, exclude_dims, dask, output_dtypes, vectorize, keep_attrs, dask_gufunc_kwargs, *args)
    756     if vectorize:
    757         func = _vectorize(
    758             func, signature, output_dtypes=output_dtypes, exclude_dims=exclude_dims
    759         )
--> 761 result_data = func(*input_data)
    763 if signature.num_outputs == 1:
    764     result_data = (result_data,)

File <__array_function__ internals>:200, in einsum(*args, **kwargs)

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/numpy/core/einsumfunc.py:1371, in einsum(out, optimize, *operands, **kwargs)
   1369     if specified_out:
   1370         kwargs['out'] = out
-> 1371     return c_einsum(*operands, **kwargs)
   1373 # Check the kwargs to avoid a more cryptic error later, without having to
   1374 # repeat default values here
   1375 valid_einsum_kwargs = ['dtype', 'order', 'casting']

TypeError: invalid data type for einsum
```
