### ISSUE TITLE
ERA5 on single level - Mean 

### ISSUE THREAD

**Issue by Yassminaa** [bopen/c3s-eqc-toolbox-template#88]
### Notebook description

'Mean'  diagnostics of the 2-meter temperature of ERA5 on single level

### Notebook link or upload

[UC1_ERA5_t2m_mean.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/12226365/UC1_ERA5_t2m_mean.zip)

### Environment

<details>

**Comment by malmans2** [comment]
Hi @Yassminaa,

I'll be working on this today. 

You are analysing monthly data but you are not computing time weighted averages.
Is that on purpose, or do you prefer to apply weights? I.e., weights are the number of days in each month.

**Comment by Yassminaa** [comment]
Thanks very much, @malmans2 

Yes. As for monthly data, I didn't expect a difference with the time-weighted averages, and also the monthly mean catalog is not a time-weighted average it would be consistent to proceed without it in this particular case.

**Comment by Yassminaa** [comment]
If possible, yes. it would be much better.
Otherwise, the current hardcoded version has to be manually updated with any change in the analyzed data.

**Comment by malmans2** [comment]
No problem, it's very easy to do.
Do you want to cover the full time period (from 1940 to June 2023)?

**Comment by Yassminaa** [comment]
Great. The period will be from Jan. 1940 until Dec. 2022.
Thanks, @malmans2

**Comment by malmans2** [comment]
OK, should be ready after lunch.

**Comment by malmans2** [comment]
Here is the template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/era5_t2m_mean.ipynb
Here is the notebook executed: https://gist.github.com/malmans2/806334ee581e6163e271aba47e8f5db6

You were not caching the diagnostics, which means that you had to re-compute everything from scratch every time you run the notebook.

When you run the template, you'll see that it's now quick to retrieve cached diagnostics.
Still, tt takes some time to run the whole notebook, but the bottleneck is plotting/rendering high-res projected maps.

Please let me know if everything is working as expected:

**Comment by malmans2** [comment]
Hi @Yassminaa,

Can we close this or are you still working on it?

**Comment by Yassminaa** [comment]
Thank you @malmans2 
Yes, you can close it. I made only minor changes to improve the plot visualization but it does not affect your template.
