### ISSUE TITLE
Ocean color timeseries

### ISSUE THREAD

**Issue by chiaravol** [bopen/c3s-eqc-toolbox-template#90]
### Notebook description

Hi Mattia,

I need to modify the template you've shared (https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/ocean_color.ipynb) to download 5 different variables at different latitude slices.

But, as already happened before, the kernel stops working as I modify the request, likely because of their size.

I kept using your template by changing each variable name at a time (and latitude ranges), but I was wondering if it's possibile to create a template to download all 5 variables at once.

Could you please help?

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Which variables do you need to download?

**Comment by malmans2** [comment]
I only see 2 variable options in the CDS form: https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-ocean-colour?tab=form

**Comment by malmans2** [comment]
All you need is to re-run the whole notebook using that slices?

**Comment by chiaravol** [comment]
It took forever, but it worked out.

**Comment by malmans2** [comment]
> It took forever

The running time should be a linear function of the number of months processed, which is in line with the code design. The dataset you are processing is quite big and the VM has limited resources. It takes some time, but it's stable and it's a one-time computation because of the cache.

> but it worked out.

Great. (We've been running the same code simultaneously. As I mentioned yesterday, I was running the notebook overnight to cache the new diagnostics requested yesterday).

Here is the latest template, where lat0/lat1 are now in the parameters section: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/ocean_color.ipynb

**Comment by malmans2** [comment]
@chiaravol, 

You need me to generalise [this notebook](https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/ocean_color.ipynb) to include reflectance variables, right?
Masking should only be applied to chl data, correct?
Anything else?

**Comment by malmans2** [comment]
Looks like you need different regions for Rrs: https://github.com/bopen/c3s-eqc-toolbox-template/issues/92#issuecomment-1671605866

**Comment by chiaravol** [comment]
We can use the same regions as in the ocean color map template. But, again, I might need to run it over different regions.

**Comment by malmans2** [comment]
In this case the region does affect the cache and it's not for plotting purposes only (we are caching spatial averages).
So you'll have to ask us to populate the cache if you'll need different regions.

**Comment by chiaravol** [comment]
ok,I will :)

**Comment by chiaravol** [comment]
Hi Mattia, Could you also add and cache the region lat (50, -50) and long(180, -180).

Thank you in advance!

**Comment by malmans2** [comment]
On it!

**Comment by malmans2** [comment]
Done. chlor_a, Rrs_443, Rrs_560 are cached.
Here is the latest template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/ocean_color_timeseries.ipynb

**Comment by malmans2** [comment]
What do you mean? I added the link to the notebook in my last comment: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/ocean_color_timeseries.ipynb

**Comment by chiaravol** [comment]
Following the link, I cannot run that notebook

**Comment by malmans2** [comment]
I'm not sure I understand.
As always, that's the link to the template stored on GitHub. And as usual, you need to download it to the VM to run it.

**Comment by chiaravol** [comment]
Oh..sorry...my bad.
Just another thing...I guess we have forgotten to not account for chl>100 and chl<0.001 in the maps template.
I've added a line for that, but you want maybe verify and modify the public template
