### ISSUE TITLE
access denied to satellite-humidity-profiles

### ISSUE THREAD

**Issue by gmandorl** [bopen/c3s-eqc-toolbox-template#94]
### What happened?

I am trying to read the dataset "satellite-humidity-profiles".
When executing the function download.download_and_transform() I receive the following message

Exception: Client has not agreed to the required terms and conditions.. To access this resource, you first need to accept the termsof 'EUMETSAT ROM SAF products licence' at https://cds.climate.copernicus.eu/cdsapp/#!/terms/eumetsat-rom-saf

What should I do to read the dataset?

Thank you

### Relevant log output

```Python
Exception: Client has not agreed to the required terms and conditions.. To access this resource, you first need to accept the termsof 'EUMETSAT ROM SAF products licence' at https://cds.climate.copernicus.eu/cdsapp/#!/terms/eumetsat-rom-saf
```

### Environment

<details>

</details>

**Comment by malmans2** [comment]
The default user (probably Vincenzo's account), did not accept the terms of the dataset that you are trying to download.
You should use your own user:

- Go the the CDS website, log in, then accept the terms of the dataset you want to download
- Place the .cdsapirc in your personal directory on the VM
- Add the path to the .cdsapirc file on top of your notebook as explained in the [overview notebook](https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/01-Application_Template_Overview.ipynb)

Here are the instructions on how to use the .cdsapirc: https://cds.climate.copernicus.eu/api-how-to
