### ISSUE TITLE
Ocean color - trends

### ISSUE THREAD

**Issue by chiaravol** [bopen/c3s-eqc-toolbox-template#95]
### Notebook description

Hi Mattia, I'm trying to calculate chlor_a trend matrix, trend p-value and trend significance by modifying the ocean_color_maps notebook. I think the right function is the Mann_Kendall_test (?)

This is the code I've added:
da_mean=da_year.drop_sel(reduction='std').mean(dim='reduction')
coords_name = {"time": "year", "x": "longitude", "y": "latitude"}
MK_trends = Mann_Kendall_test(da_mean, coords_name=coords_name).compute()

which keeps giving me this error message:
MemoryError: Unable to allocate 570. MiB for an array with shape (2, 1, 4320, 8640) and data type float64

Any tips to solve that? Thanks

### Environment

<details>

</details>

**Comment by malmans2** [comment]
I'm currently on leave and I'll be back on Monday September 4th.

**Comment by malmans2** [comment]
@chiaravol Mann Kendall tests are computationally very expensive. You didn't share the full code, but my guess is that your input data is not properly chunked.

I'm caching the trends for the variables you've been working on. I'll let you know when it's ready (it will take a while, they'll probably be ready tomorrow)

**Comment by chiaravol** [comment]
Hi Mattia.

My ultimate goal is make a trend map for chl and reflectances showing significant trends (p<0.05) only. Here, the "dirty" code I was working on.

[ocean_color_maps_MK.ipynb.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/12522070/ocean_color_maps_MK.ipynb.zip)

**Comment by malmans2** [comment]
Hi, the VM is busy again.

I'm gonna make another try today, otherwise I'll have to run the scripts to cache trends over the weekend.

**Comment by chiaravol** [comment]
ok

**Comment by malmans2** [comment]
Hi,

Trend for `chlor_a` and `Rrs_443` are now cached. `Rrs_560` is being cached right now, I'll let you know when it's ready.

I reviewed a bit the maps notebook and added a plot for trends with hatches. Please use the latest template from now on.
Template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/ocean_color_maps.ipynb
Notebook executed: https://gist.github.com/malmans2/30ed3810d2250495308372345f9c89e1

**Comment by malmans2** [comment]
All set!

**Comment by chiaravol** [comment]
Hi Mattia, 

How can I modify the scale limits and cmaps? Maps are now hard to read, especially those for the means. I should be free to chose different scales depending on the variable analyzed.
Additionally, I'd like to used the cmap='RdBu_r', as it's more colorblind friendly.

Cheers

**Comment by malmans2** [comment]
If you check the documentation of `plot.projected_map` you'll see that you can pass any keyword arguments of xarray/matplotlib's plotting functios. Additionally, the function returns the plotting object, so you can change various settings after initializing the plot.

As far as I know, `cmap="RdBu_r"` is the default for plots with positive/negative values. Often we use xarray's `robust` argument instead of hardcoding the limits to obtain oversaturated colorbar.

Here is an example of what you are looking for: `plot.projected_map(..., cmap="RdBu_r", vmin=-1, vmax=1)`

**Comment by chiaravol** [comment]
Thanks, but the problem arises as map parameters are defined all together for both average and standard deviation in all the regions analyzed. As a consequence, I do not have access to each map parameter set and when I try to plot each map separately, the vm runs out of memory...

**Comment by malmans2** [comment]
There's a for loop, so you can parametrize the plot settings using if statements.
For example, `cmap="RdBu_r" if reduction == "std" else "viridis"`

If you run the same exact code but without the for loop (e.g., copying/pasting the same code for various diagnostics), the memory usage is the same.
