### ISSUE TITLE
Error in plotting xch4 anomaly Lev-2

### ISSUE THREAD

**Issue by paolocristofanelli** [bopen/c3s-eqc-toolbox-template#96]
@malmans2

Working on  https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/xch4_satellite_lev2.ipynb

I got the following error on running
_ = plot.projected_map(
    anomaly["xch4"], projection=ccrs.Robinson(), col="season", row="year", robust=True
)

error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[17], line 1
----> 1 _ = plot.projected_map(
      2     anomaly["xch4"], projection=ccrs.Robinson(), col="season", row="year", robust=True
      3 )

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/c3s_eqc_automatic_quality_control/plot.py:209, in projected_map(da, projection, show_stats, stats_weights, plot_func, **kwargs)
    207     subplot_kws.setdefault("projection", projection)
    208 if "x" not in kwargs:
--> 209     kwargs["x"] = utils.get_coord_name(da, "longitude")
    210 if "y" not in kwargs:
    211     kwargs["y"] = utils.get_coord_name(da, "latitude")

File /data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/c3s_eqc_automatic_quality_control/utils.py:45, in get_coord_name(obj, coordinate)
     43 if len(coords) == 1:
     44     return coords[0]
---> 45 raise ValueError(f"Can NOT infer {coordinate!r}: {coords!r}")

ValueError: Can NOT infer 'longitude': []

Originally posted by @malmans2 in https://github.com/bopen/c3s-eqc-toolbox-template/issues/52#issuecomment-1571590996_

**Comment by malmans2** [comment]
On it, looks like some attribute gets lost.

**Comment by malmans2** [comment]
Fixed, you need to use the latest template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/xch4_satellite_lev2.ipynb

![image](https://github.com/bopen/c3s-eqc-toolbox-template/assets/22245117/644a9f33-6925-4ccc-95cf-2d507db4754e)
